-- Generated by tools/build-rosie.mjs; edit the reviewed source or transform.
local Settings = require('rosie.private.pickup.src.settings')
local Utils = require('rosie.private.pickup.utils.utils')
local CustomItems = require('rosie.private.pickup.data.custom_items')
local CurrentItems = require('rosie.data.items')
local ItemLogic = require('rosie.private.pickup.src.item_logic')
local Pickup = require('rosie.private.pickup.src.pickup')
local MythicForm = require('rosie.private.mythic_form')
-- QQT_Warpigz_v2 local patch (Rosie 1.0.8): "Pick up every Unique" and the
-- list of plain Uniques Rosie dropped on purpose.
local Blacklist = require('rosie.private.blacklist')
local UniqueSorter = require('rosie.private.unique_sorter')
local M = {}
-- Every recognized category owns its refusal. It must never enter gear rules.
local policies = {
    event_items={'event_items','equipment'}, boss_items={'boss_items','consumable',99},
    rare_elixirs={'rare_elixirs','consumable',99},basic_elixirs={'basic_elixirs','consumable',99},
    advanced_elixirs={'advanced_elixirs','consumable',99},scroll={'scroll','consumable',20},
    other_consumables={'other_consumables','consumable'},
    heavenly_sigil={'heavenly_sigil','consumable'},sigil={'sigils','sigil'},
    compass={'compass','sigil'},tribute={'tribute','sigil'},rune={'rune','socketable',100},
    gemstone={'gemstone','socketable'},charm={'charm','talisman'},seal={'seal','talisman'},
    splinter={'splinter','socketable'},lair_key={'lair_key','consumable'},fish={'fish','equipment'},
    recipe={'crafting_items','equipment'},cache={'cache','equipment'},quest={'quest_items'},
    crafting={'crafting_items'},cinders={'cinders'},
}
local carry_noted={} -- QQT_Warpigz_v3 (Q9): SNO -> zone of the last "already carrying" line
local function filter_reason(info,enabled)
    if not enabled then return nil end
    local filtered=Utils.call(info,'is_filtered_by_loot_filter')
    if filtered==true then return 'ingame loot filter' end
    if filtered~=false then return 'ingame loot filter unavailable','deferred' end
end
local function is_mythic(rarity,sno,info)
    local known=CurrentItems.by_id[sno]
    -- Some native Unique values need the same exact-SNO mythic fallback as
    -- the legacy list. Metadata never promotes lower or unreadable rarities.
    return rarity>=8 or CustomItems.ubers[sno]~=nil
        or rarity==6 and known~=nil and known.kind=='equipment' and known.quality=='mythic'
        -- QQT_Warpigz_v2 local patch: S14 re-issued iconic Mythics (rarity 6,
        -- catalog "unique") and the S15 Mythic form of an ordinary Unique.
        or rarity==6 and MythicForm.is_mythic_sno(sno)
        or MythicForm.is_mythic_form(info,rarity)
end
M.is_mythic=is_mythic -- QQT_Warpigz_v3: exported; also handed to pickup's suite event (no require cycle)
Pickup.is_mythic=is_mythic
-- QQT_Warpigz_v3 (keep menu): the town keep list a SNO is selected in, or
-- nil (through the sorter's bound town utils; no require cycle).
local function town_named_keep(sno)
    local ok,why=pcall(UniqueSorter.named_keep,sno)
    return ok and type(why)=='string' and why or nil
end
local function equipment_threshold(s,rarity,sno,slot,info)
    local mythic=is_mythic(rarity,sno,info)
    local required,source=0,'common_general'
    if mythic then required,source=s.uber_unique_ga_count,'mythic_general'
    elseif rarity==6 then required,source=s.unique_ga_count,'unique_general'
    elseif rarity==5 then required,source=s.ga_count,'legendary_general'
    elseif rarity==3 or rarity==4 then required,source=s.rare_ga_count or 0,'rare_general'
    elseif rarity==1 or rarity==2 then required,source=s.magic_ga_count or 0,'magic_general' end
    local overridden=false
    if s.custom_toggle and not mythic and (rarity==5 or rarity==6) and slot then
        local key=(rarity==6 and 'unique_' or 'legendary_')..slot
        local override=s[key..'_ga_count']
        -- Newly added slot controls inherit the existing general policy at -1.
        if type(override)=='number' and override>=0 then
            required,source,overridden=override,key..'_override',true
        end
    end
    return required,source,overridden
end
-- QQT_Warpigz_v3 1.0.22 (perf): choose() passes a table of its own for one
-- pulse, so each bag is read once per pulse, not once per ground candidate
-- (nothing is picked up while choose runs). Every other caller reads live.
local function bag_state(bag,bags)
    if not bags then return Utils.bag_state(bag) end
    local hit=bags[bag]
    if not hit then local items,full=Utils.bag_state(bag);hit={items=items,full=full};bags[bag]=hit end
    return hit.items,hit.full
end
local function check_want(item, ignore_distance, bags) -- QQT_Warpigz_v3 1.0.22: bags (see bag_state)
    local player=get_local_player()
    if not player or Utils.call(player,'is_dead')~=false then return false,'character unavailable or dead','deferred' end
    local info=Utils.call(item,'get_item_info')
    if not info or Utils.call(info,'is_valid')~=true then return false,'item data unavailable','deferred' end
    local s=Settings.get()
    if not ignore_distance and Utils.distance_to(item)>s.distance then return false,'outside pickup distance '..s.distance end
    if Utils.host_call(loot_manager.is_gold,item) or Utils.host_call(loot_manager.is_potion,item) then return false,'gold or potion' end
    -- QQT_Warpigz_v3 3.3.2 (live report, Pit: "Murmuring Obols" beside the
    -- fight): obols, like gold, are taken by the game on proximity; interact
    -- never takes them and they go to no bag. Never a pickup target.
    if Utils.host_call(loot_manager.is_obols,item)==true then return false,'obols (the game collects them)' end
    local lootable=Utils.host_call(loot_manager.is_lootable_item,item,true,true)
    if lootable~=true then return false,'host says not lootable or unavailable',lootable~=false and 'deferred' or nil end
    local kind,slot,max_stack,bag=ItemLogic.classify(info)
    local policy=policies[kind]
    if policy then
        if s[policy[1]]~=true then return false,'category disabled: '..kind end
        if kind=='charm' or kind=='seal' then
            local reason,decision=filter_reason(info,s.respect_filter)
            if reason then return false,reason,decision end
        end
        -- QQT_Warpigz_v3 (Q9, live S15): a character may carry one of each
        -- Splinter of Evil (rosie/data/carry_once.lua); the game refuses a
        -- second copy of a kind already carried and Rosie stood on it.
        local once,once_sno=ItemLogic.carry_once(info)
        bag=once and once.bag or bag or policy[2]
        if not bag or bag=='currency' or bag=='materials' then return true,'accepted '..kind end -- QQT_Warpigz_v3 (Q1)
        local inventory,full=bag_state(bag,bags) -- QQT_Warpigz_v3 1.0.22 (perf)
        if not inventory then return false,'bag unavailable: '..bag,'deferred' end
        if once then -- QQT_Warpigz_v3 (Q9)
            local held,readable=Utils.list_has_sno(inventory,once_sno)
            if held then
                local zone=Utils.call(Utils.host_call(rawget(_G,'get_current_world')),'get_current_zone_name') or '?'
                if carry_noted[once_sno]~=zone then
                    carry_noted[once_sno]=zone
                    console.print(string.format('[Rosie pickup] Not picking up %s (sno=%d): already carrying one; the game allows one per character.',
                        tostring(once.name),once_sno))
                end
                return false,'already carrying '..tostring(once.name)..' (one per character)'
            end
            carry_noted[once_sno]=nil
            if not readable then return false,'carried items unreadable: '..bag,'deferred' end
        end
        if not full then return true,'accepted '..kind end
        max_stack=max_stack or policy[3]
        if max_stack and max_stack>1 then
            local fits,readable=Utils.is_lowest_stack_below(inventory,
                Utils.call(info,'get_sno_id'),max_stack,Utils.call(info,'get_stack_count'))
            if fits then return true,'accepted stack' end
            if not readable then return false,'stack data unavailable: '..bag,'deferred' end
        end
        return false,'bag full or unreadable: '..bag -- category refusal is terminal
    end
    if kind~='equipment' then
        local skin=Utils.call(info,'get_skin_name')
        return false,'unrecognized item type',type(skin)~='string' and 'deferred' or nil
    end
    -- QQT_Warpigz_v3 (keep menu, user report: a checked Leoric's Crown): a
    -- drop selected in a town keep list is taken whatever the GA sliders, the
    -- minimum rarity or the in-game loot filter say, and the list of Uniques
    -- Rosie dropped never refuses it (on the ground a Mythic form looks like
    -- its plain Unique; the bag copy decides).
    local keep_list=town_named_keep(Utils.call(info,'get_sno_id'))
    -- QQT_Warpigz_v2 local patch (Rosie 1.0.8): a plain Unique Rosie dropped
    -- on purpose is never taken again (fingerprint, else SNO near the drop spot).
    if not keep_list then
        local listed,dropped,dropped_reason=pcall(Blacklist.match,item,info)
        if listed and dropped then return false,dropped_reason end
    end
    local inventory,full=bag_state('equipment',bags) -- QQT_Warpigz_v3 1.0.22 (perf)
    if not inventory then return false,'equipment bag unavailable','deferred' end
    if full then return false,'equipment bag full or unreadable' end
    if keep_list then return true,'accepted: selected in '..keep_list end
    -- QQT_Warpigz_v2 local patch (Rosie 1.0.7): a mythic never takes the
    -- in-game loot-filter refusal (the town rules exempt it the same way).
    local early=Utils.call(info,'get_rarity')
    local protected=type(early)=='number' and early==early and is_mythic(early,Utils.call(info,'get_sno_id'),info)
    if not protected then
        local reason,decision=filter_reason(info,s.respect_filter)
        if reason then return false,reason,decision end
    end
    -- Legacy heuristic, opt-in only: the host exposes no dropped-by-player flag.
    if s.skip_dropped then
        local affixes=Utils.call(info,'get_affixes')
        if type(affixes)~='table' then return false,'visible affix list unavailable','deferred' end
        if #affixes>0 then return false,'legacy Skip gear with visible affixes setting' end
    end
    local rarity=Utils.call(info,'get_rarity')
    if type(rarity)~='number' or rarity~=rarity then return false,'item rarity unavailable','deferred' end
    -- QQT_Warpigz_v2 local patch (Rosie 1.0.8): "Pick up every Unique (sort
    -- in the bag)": every Unique and every definite Mythic, whatever the GA
    -- sliders and slot overrides say; the bag copy shows which it is. A plain
    -- Unique still took the in-game loot-filter check above; a Mythic never does.
    if UniqueSorter.pick_all() and (rarity==6 or is_mythic(rarity,Utils.call(info,'get_sno_id'),info)) then
        return true,UniqueSorter.PICKUP_REASON
    end
    if rarity<s.rarity then return false,'below minimum rarity or unreadable rarity' end
    local required,threshold,overridden=equipment_threshold(s,rarity,Utils.call(info,'get_sno_id'),slot,info)
    local ga,ga_readable=Utils.get_ga_count(info)
    -- QQT_Warpigz_v2 local patch (live rc.8: fresh Uber drops "Helm",
    -- ancestral, GA 0, no mark): a drop below its threshold whose reading
    -- cannot rule out a Mythic is taken; the bag copy decides in town.
    -- Affixes unreadable or none listed: no GA rule can be judged (a fresh
    -- drop reads GA 0 whatever it carries), so any Unique or mythic is taken,
    -- whichever slider is stricter. An Ancestral Unique listing affixes but
    -- reading 0 GA is taken only when the Unique rule is the stricter one.
    local mythic=is_mythic(rarity,Utils.call(info,'get_sno_id'),info)
    if ga<required and (rarity==6 or mythic) then
        local why=MythicForm.undecided(info,ga_readable and ga or nil)
        local blind=why=='affixes unreadable' or why=='no affixes listed'
        if blind and mythic then
            return true,'accepted: Mythic, Greater Affixes not readable yet ('..why..'; decided in town) [threshold='..threshold..']'
        end
        if why and rarity==6 and not mythic and (blind or required>(s.uber_unique_ga_count or 0)) then
            return true,'accepted: may be a Mythic Unique ('..why..'; decided in town) [threshold='..threshold..']'
        end
    end
    if required>0 and not ga_readable then return false,'Greater Affix count unavailable','deferred' end
    return ga>=required, string.format('%s: GA %d, required %d%s [threshold=%s]',ga>=required and 'accepted' or 'below GA minimum',
        ga,required,overridden and ' (slot override enabled)' or '',threshold)
end
function M.check_want_item(item, ignore_distance) return check_want(item, ignore_distance) end -- QQT_Warpigz_v3 1.0.22: live bag reads
-- QQT_Warpigz_v3 (Q1): where an accepted drop lands (pickup receipt): its
-- kind and bag ('equipment', 'consumable', 'socketable', 'talisman',
-- 'sigil'), or no bag for Materials, currency and anything no bag lists.
function M.destination(item)
    local kind,_,_,bag=ItemLogic.classify(Utils.call(item,'get_item_info'))
    local policy=policies[kind]
    if kind=='equipment' then bag='equipment' elseif policy then bag=bag or policy[2] end
    if bag=='currency' or bag=='materials' then bag=nil end
    return kind,bag
end
local reported={}
function M.describe(item, reason)
    local info=Utils.call(item,'get_item_info')
    local name=tostring(Utils.call(info,'get_display_name') or Utils.call(info,'get_skin_name') or 'unknown'):gsub('[\r\n]',' '):sub(1,120)
    local sno,rarity=Utils.call(info,'get_sno_id'),Utils.call(info,'get_rarity')
    local count,readable,observations=Utils.get_ga_count(info)
    local kind,slot=ItemLogic.classify(info)
    local threshold='category:'..kind
    if kind=='equipment' and type(rarity)=='number' and rarity==rarity then
        local required,source=equipment_threshold(Settings.get(),rarity,sno,slot,info)
        threshold=source..':'..tostring(required)
    end
    local extra=''
    if type(rarity)=='number' and rarity>=6 then
        -- QQT_Warpigz_v2 local patch: the matching mark affix (or false), why
        -- the reading cannot rule out a Mythic, and the listed affix count.
        local okm,mark=pcall(MythicForm.mark_of,info)
        local oku,why=pcall(MythicForm.undecided,info,readable and count or nil)
        local okn,n=pcall(MythicForm.affix_count,info)
        extra=string.format(' mythic_mark=%s undecided=%s affixes=%s',tostring(okm and mark or false),
            tostring(oku and why or 'no'),okn and n~=nil and tostring(n) or 'unreadable')
    end
    return string.format('%s | sno=%s rarity=%s ancestral=%s GA=%d nativeGA=%s displayGA=%s GA_source=%s GA_readable=%s GA_conflict=%s threshold=%s%s distance=%.1f | %s',name,
        tostring(sno),tostring(rarity),tostring(Utils.call(info,'is_ancestral')),count,
        tostring(observations.native_raw),tostring(observations.display_count),observations.source,
        tostring(readable),tostring(observations.conflict),threshold,extra,Utils.distance_to(item),reason or 'unknown decision')
end
function M.report_rejection(item, reason)
    -- QQT_Warpigz_v3 1.0.22 (perf): the cheap early returns (reason, then
    -- distance) before the item's GA reading; all are pure, so the order is free.
    if type(reason)=='string' and reason:find('already carrying',1,true) then return end -- QQT_Warpigz_v3 (Q9): logged at the decision
    if type(reason)=='string' and reason:sub(1,15)=='pickup settled:' then return end -- QQT_Warpigz_v3 (Q1 review): settle() logged it once
    if reason=='pickup yielded to another move' then return end -- QQT_Warpigz_v3 3.3.2: stand_down() logged it
    if Utils.distance_to(item)>60 then return end
    local info=Utils.call(item,'get_item_info')
    local rarity=Utils.call(info,'get_rarity')
    if type(rarity)~='number' or rarity~=rarity then rarity=0 end
    if rarity<6 and Utils.get_ga_count(info)==0 then return end
    local id=Pickup.key(item)
    -- QQT_Warpigz_v3 1.0.29 (scenario sweep R4): once per drop per reason
    -- (numbers such as distances normalised). Only the last reason was kept,
    -- so a drop whose reason flipped (outside distance <-> bag full while the
    -- player walked 6 <-> 10 m) printed a Skipped line on every flip.
    if id then
        local seen=reported[id]
        if type(seen)~='table' then seen={};reported[id]=seen end
        local key=type(reason)=='string' and reason:gsub('%d+%.?%d*','N') or tostring(reason)
        if not seen[key] then
            seen[key]=true
            console.print('[Rosie pickup] Skipped '..M.describe(item,reason))
        end
    end
    if rarity>=6 then pcall(M.probe,item,'skipped') end
end
-- QQT_Warpigz_v2 local patch: every Unique/Mythic equipment drop Rosie skips, or takes as
-- "may be a Mythic", logs its markers (affixes, quality attributes) once per
-- distinct reading, at most three lines per drop and one reading per second,
-- so one live log shows how a Mythic reads on the ground.
local probed={}
function M.probe(item,label)
    if not MythicForm.diagnostics_on() then return end
    local id=Pickup.key(item)
    if not id then return end
    local now=get_time_since_inject()
    local seen=probed[id]
    if seen and (seen.n>=3 or now<seen.next) then return end
    local info=Utils.call(item,'get_item_info')
    if not info or ItemLogic.classify(info)~='equipment' then return end
    seen=seen or {n=0,next=0}; probed[id]=seen
    seen.next=now+1
    local line=MythicForm.probe(info)
    if seen[line] then return end
    seen[line]=true; seen.n=seen.n+1
    console.print(string.format('[Rosie mythic-probe] %s sno=%s rarity=%s | %s',label,
        tostring(Utils.call(info,'get_sno_id')),tostring(Utils.call(info,'get_rarity')),line))
end
function M.observe(items)
    local complete=Pickup.observe(items)
    if not complete then return false end
    local present={}
    for _,item in pairs(items) do local id=Pickup.key(item); if id then present[id]=true end end
    for id in pairs(reported) do if not present[id] then reported[id]=nil end end
    for id in pairs(probed) do if not present[id] then probed[id]=nil end end
end
-- QQT_Warpigz_v2: Season 15 Mythic forms of ordinary Uniques report the
-- same SNO and rarity 6 as the Unique (live: "Condemnation", Ancestral Mythic
-- Unique Dagger, sno=451091 rarity=6). This deep dump shows everything the
-- host exposes on such an item so the real Mythic marker can be found.
local PROBES={'is_mythic','is_uber','is_unique','is_iconic','is_legendary','is_ancestral','is_sacred',
    'get_quality','get_item_quality','get_quality_level','get_rarity','get_rarity_type','get_item_rarity',
    'get_magic_type','get_item_power','get_power','get_level','get_flags','get_item_flags','get_sno_id',
    'get_skin_name','get_name','get_display_name','get_unique_id','get_item_type','get_affix_count',
    'get_greater_affix_count','get_upgrade_level','get_masterwork_rank','get_tempering_count'}
local function method_names(obj)
    local names,seen={},{}
    local ok,mt=pcall(getmetatable,obj)
    local function add(t)
        if type(t)~='table' then return end
        for k in pairs(t) do
            if type(k)=='string' and not seen[k] and k:sub(1,2)~='__' then seen[k]=true;names[#names+1]=k end
        end
    end
    if ok and type(mt)=='table' then add(mt);add(rawget(mt,'__index')) end
    table.sort(names)
    return table.concat(names,',')
end
local function short(v)
    local t=type(v)
    if t=='string' then return string.format('%q',#v>160 and v:sub(1,160)..'...' or v) end
    if t=='table' then local n=0;for _ in pairs(v) do n=n+1 end;return 'table#'..n end
    return tostring(v)
end
function M.deep_dump(label,obj)
    if obj==nil then return end
    local parts={}
    for _,name in ipairs(PROBES) do
        local ok,fn=pcall(function() return obj[name] end)
        if ok and type(fn)=='function' then
            local ok2,v=pcall(fn,obj)
            parts[#parts+1]=name..'='..(ok2 and short(v) or 'error')
        end
    end
    console.print('[Rosie dump] '..label..' | '..table.concat(parts,' '))
    console.print('[Rosie dump] '..label..' methods: '..method_names(obj))
    local ok,affixes=pcall(function() return obj:get_affixes() end)
    if ok and type(affixes)=='table' then
        for i,a in ipairs(affixes) do
            local ok3,line=pcall(function()
                return string.format('affix %d hash=%s name=%s roll=%s greater=%s', i, tostring(a.affix_name_hash),
                    short(a.get_name and a:get_name() or a.name), tostring(a.get_roll and a:get_roll() or a.roll),
                    tostring(a.is_greater_affix and a:is_greater_affix() or a.greater))
            end)
            console.print('[Rosie dump]   '..(ok3 and line or ('affix '..i..' unreadable')))
        end
    end
end
local function dump_rare_items()
    local items=Utils.host_call(actors_manager.get_all_items)
    for _,item in pairs(type(items)=='table' and items or {}) do
        if Utils.distance_to(item)<=20 then
            local info=Utils.call(item,'get_item_info')
            local rarity=Utils.call(info,'get_rarity')
            if type(rarity)=='number' and rarity>=6 then M.deep_dump('ground '..tostring(Utils.call(info,'get_sno_id')),info) end
        end
    end
    local player=get_local_player()
    local ok,inv=pcall(function() return player:get_inventory_items() end)
    for _,item in pairs(ok and type(inv)=='table' and inv or {}) do
        local rarity=Utils.call(item,'get_rarity')
        if type(rarity)=='number' and rarity>=6 then M.deep_dump('inventory '..tostring(Utils.call(item,'get_sno_id')),item) end
    end
end
function M.diagnose()
    -- QQT_Warpigz_v2: Mythic probe lines for the next 5 minutes.
    pcall(function() MythicForm.diag_until=get_time_since_inject()+300 end)
    Settings.update()
    local s=Settings.get()
    console.print(string.format('[Rosie pickup] enabled=%s paused=%s behavior_ready=%s distance=%s respect_filter=%s skip_affixes=%s custom_GA=%s',
        tostring(s.enabled),tostring(Settings.is_paused()),tostring(Settings.should_execute()),tostring(s.distance),
        tostring(s.respect_filter),tostring(s.skip_dropped),tostring(s.custom_toggle)))
    local count=0
    local items=Utils.host_call(actors_manager.get_all_items)
    if type(items)~='table' then
        console.print('[Rosie pickup] Item list unavailable. Try again after the world loads.')
        return 0
    end
    for _,item in pairs(items) do
        if Utils.distance_to(item)<=60 then
            local wanted,reason=M.check_want_item(item,false)
            local blocked,why=Pickup.blocked(item)
            if wanted and blocked then wanted,reason=false,why end
            -- QQT_Warpigz_v3 1.0.26: a drop the fight hold defers is not 'Wanted' now.
            local held,held_by=false,nil
            if wanted then held,held_by=Pickup.fight_deferred(item) end
            if held then wanted,reason=false,held_by=='fight' and 'held by the fight hold (it is taken after the fight)'
                or 'held while Navigator gets the path back (Scavenger stand-in cool-down)' end
            console.print('[Rosie pickup] '..(wanted and 'Wanted ' or held and 'Waiting ' or 'Skipped ')..M.describe(item,reason))
            count=count+1
            if count>=64 then console.print('[Rosie pickup] Diagnostic limited to 64 nearby drops.'); break end
        end
    end
    console.print('[Rosie pickup] Nearby decisions logged: '..count)
    local ok_dump,err=pcall(dump_rare_items)
    if not ok_dump then console.print('[Rosie dump] failed: '..tostring(err)) end
    return count
end
function M.calculate_item_score(item)
    local info=Utils.call(item,'get_item_info')
    local rarity=Utils.call(info,'get_rarity') or 0
    local mythic=is_mythic(rarity,Utils.call(info,'get_sno_id'),info)
    return (mythic and 1000 or rarity>=5 and 500 or rarity>=3 and 300 or rarity>=1 and 100 or 10)
        + Utils.get_ga_count(info)*25
end
local selected_key
local function choose(best_first)
    M.fight_waiting=false -- QQT_Warpigz_v3 3.3.2: a wanted drop waits for the fight
    local items=Utils.host_call(actors_manager.get_all_items)
    M.observe(items)
    if type(items)~='table' then return nil end
    local selected,score,distance
    local previous,previous_score,previous_distance
    local rested,rested_distance
    -- QQT_Warpigz_v3 1.0.22 (perf): each bag read once this pulse; Pickup.blocked
    -- only when its answer is used or a settled drop needs its away mark.
    local bags,tracking={},Pickup.tracking()
    local fight_n=0 -- QQT_Warpigz_v3 1.0.26: drops the fight hold defers this pulse
    for _,item in pairs(items) do
        local wanted,reason=check_want(item,false,bags)
        local blocked,why
        if wanted or tracking then blocked,why=Pickup.blocked(item) end
        -- QQT_Warpigz_v2 local patch (review rc.10): the nearest wanted drop
        -- resting between rounds (woken below when nothing else is wanted).
        if wanted and blocked and Pickup.resting(item,true) and not Pickup.fight_deferred(item) then -- QQT_Warpigz_v3 3.3.2: never a yielded drop, nor one the fight holds
            local d=Utils.distance_to(item)
            if not rested or d<rested_distance then rested,rested_distance=item,d end
        end
        if wanted and blocked and Pickup.resting(item) then Pickup.fight_refresh() end -- QQT_Warpigz_v3 1.0.22: the fight hold stays observed
        if wanted and blocked then wanted,reason=false,why end
        -- QQT_Warpigz_v3 3.3.2: a drop off the feet waits for the fight (pickup.lua header).
        local deferred,held_by=false,nil
        if wanted then deferred,held_by=Pickup.fight_deferred(item) end
        if deferred then wanted=false;M.fight_waiting=true;if held_by=='fight' then fight_n=fight_n+1 end end -- QQT_Warpigz_v3 1.0.26: counted for the line
        if wanted then
            -- QQT_Warpigz_v2 local patch (Rosie 1.0.8): a Unique taken by "Pick up
            -- every Unique" logs its ground reading too (LIVE_CHECKLIST R1/S1).
            if type(reason)=='string' and (reason:find('decided in town',1,true) or reason==UniqueSorter.PICKUP_REASON) then pcall(M.probe,item,'taken') end
            local d=Utils.distance_to(item)
            local value=best_first and M.calculate_item_score(item) or 0
            if Pickup.key(item)==selected_key then previous,previous_score,previous_distance=item,value,d end
            if not selected or value>score or value==score and d<distance then
                selected,score,distance=item,value,d
            end
        elseif item~=rested and not deferred then M.report_rejection(item,reason) end
    end
    -- QQT_Warpigz_v3 1.0.26 (Discord: the fight hold was silent until its 45 s
    -- cap): one line per hold episode, and the count for status().
    if fight_n>0 then Pickup.fight_report(fight_n) else Pickup.fight_waiting_n=nil end
    if not selected and rested and Pickup.wake(rested)~=false then -- QQT_Warpigz_v3 3.3.2: false = not woken
        selected,score,distance=rested,best_first and M.calculate_item_score(rested) or 0,rested_distance
    end
    -- Keep equally valuable nearby targets stable; a better item still wins.
    if previous and previous_score==score and previous_distance<=distance+1.5 then selected,score=previous,previous_score end
    selected_key=selected and Pickup.key(selected) or nil
    return selected,score
end
-- QQT_Warpigz_v3 1.0.24 (owner, live 3.3.5: a Mythic that dropped during the
-- Town Portal cast was left on the ground): the wanted drops a town trip must
-- not leave behind. `fits`: the nearest wanted drop pickup can take now;
-- `room`: the nearest one it would take if the bag had room (a full-bag trip).
function M.trip_drops()
    local items=Utils.host_call(actors_manager.get_all_items)
    if type(items)~='table' then return nil,nil end
    local bags={}
    local roomy=setmetatable({},{__index=function(t,bag)
        local list=Utils.bag_state(bag)
        local hit={items=list,full=false}; rawset(t,bag,hit); return hit
    end})
    local fits,fits_d,room,room_d
    for _,item in pairs(items) do
        if not Pickup.blocked(item) then
            local d=Utils.distance_to(item)
            if check_want(item,false,bags) then
                if not fits or d<fits_d then fits,fits_d=item,d end
            elseif check_want(item,false,roomy) then
                if not room or d<room_d then room,room_d=item,d end
            end
        end
    end
    return fits,room
end
function M.get_nearby_item() return (choose(false)) end
function M.get_best_item()
    local item,score=choose(true)
    return item and {Item=item,Score=score} or nil
end
function M.get_item_based_on_priority()
    if Settings.get().loot_priority==0 then return M.get_nearby_item() end
    return M.get_best_item()
end
return M
