-- Generated by tools/build-rosie.mjs; edit the reviewed source or transform.
local Current = require('rosie.data.items')
local Custom = require('rosie.private.pickup.data.custom_items')
local Utils = require('rosie.private.pickup.utils.utils')
local M = {}
-- Exact SNO mappings precede skin fallbacks; names containing a gear word
-- alone are not enough to turn quest objects or cosmetics into equipment.
local slots = {
    {'quarterstaff','quarterstaff'}, {'crossbow','crossbow'}, {'polearm','2h_polearm'},
    {'glaive','glaive'}, {'2hscythe','2h_scythe'}, {'1hscythe','1h_scythe'},
    {'2hsword','2h_sword'}, {'1hsword','1h_sword'}, {'2hmace','2h_mace'}, {'1hmace','1h_mace'},
    {'2haxe','2h_axe'}, {'1haxe','1h_axe'}, {'flail','flail'},
    {'offhandssorc','focus'}, {'offhandsnecro','focus'}, {'offhandswarlock','focus'},
    {'offhandsdruid','totem'}, {'focus','focus'}, {'book','focus'}, {'totem','totem'},
    {'shield','shield'}, {'dagger','dagger'}, {'wand','wand'}, {'staff','staff'}, {'bow','bow'},
    {'amulet','amulet'}, {'necklace','amulet'}, {'ring','ring'},
    {'helm','helm'}, {'hlm','helm'}, {'chest','chest'}, {'trs','chest'},
    {'gloves','gloves'}, {'glove','gloves'}, {'glv','gloves'}, {'pants','pants'}, {'leg','pants'}, {'boots','boots'}, {'bts','boots'},
}
function M.slot_from_skin(skin)
    local lower=skin:lower()
    if lower:find('cosmetic',1,true) or lower:find('qst',1,true) then return nil end
    for _,rule in ipairs(slots) do
        for token in lower:gmatch('[^_]+') do
            if token==rule[1] or token:gsub('^[12]h','')==rule[1]
                or token:match('^'..rule[1]..'%d+$') then return rule[2] end
        end
    end
    -- Older host skins encode handedness by initial capitalization.
    if skin:match('^Sword[_%d]') then return '2h_sword' end
    if skin:match('^sword[_%d]') then return '1h_sword' end
    if skin:match('^Mace[_%d]') then return '2h_mace' end
    if skin:match('^mace[_%d]') then return '1h_mace' end
    if skin:match('^Axe[_%d]') then return '2h_axe' end
    if skin:match('^axe[_%d]') then return '1h_axe' end
end
local patterns = {
    {'charm', {'Talisman_Charm','Item_Charm'}}, {'seal', {'Talisman_Seal'}},
    {'lair_key', {'LairKey','Lair_Key'}}, {'splinter', {'S15_SoulSplinter'}},
    {'heavenly_sigil', {'S11_Heavenly_Sigil'}},
    {'compass', {'BSK_Sigil','Infernal_Compass'}}, {'tribute', {'Undercity_Tribute'}},
    {'sigil', {'Nightmare_Sigil','DungeonKey','S07_WitcherSigil','S07_DRLG_Sigil'}},
    {'rune', {'Generic_Rune','S07_Socketable','Rune_Condition','Rune_Effect'}},
    {'gemstone', {'Item_Gemstone','Gem_'}}, {'fish', {'X2_Fish_'}},
    {'cinders', {'Test_BloodMoon_Currency'}},
    {'crafting', {'CraftingMaterial','Crafting_Legendary'}},
    {'recipe', {'Tempering_Recipe','Item_Book','MountReins','mnt_amor'}},
    {'scroll', {'Scroll_Of'}}, {'cache', {'Item_Cache','Reward_Cache','WarPlans_Cache'}},
    {'quest', {'QST','DGN','Glyph','pvp_currency','GamblingCurrency_Key','Experience_PowerUp_Actor'}},
}
function M.classify(info)
    local id=Utils.call(info,'get_sno_id')
    local known=Current.by_id[id]
    if known then return known.kind, known.slot, known.stack, known.bag end
    for _,kind in ipairs({'event_items','boss_items','rare_elixirs','basic_elixirs','advanced_elixirs'}) do
        if Custom[kind][id] then return kind end
    end
    local skin=Utils.call(info,'get_skin_name') or ''
    for _,rule in ipairs(patterns) do
        for _,pattern in ipairs(rule[2]) do
            if skin:find(pattern,1,true) then return rule[1] end
        end
    end
    local slot=M.slot_from_skin(skin)
    if slot then return 'equipment',slot end
    return 'unknown'
end
return M
