-- Generated by tools/build-rosie.mjs; edit the reviewed source or transform.
local Current = require('rosie.data.items')
local Custom = require('rosie.private.pickup.data.custom_items')
local Utils = require('rosie.private.pickup.utils.utils')
local CarryOnce = require('rosie.data.carry_once') -- QQT_Warpigz_v3 (Q9)
local M = {}
-- Exact SNO mappings precede skin fallbacks; names containing a gear word
-- alone are not enough to turn quest objects or cosmetics into equipment.
local slots = {
    {'quarterstaff','quarterstaff'}, {'crossbow','crossbow'}, {'polearm','2h_polearm'},
    {'glaive','glaive'}, {'2hscythe','2h_scythe'}, {'1hscythe','1h_scythe'},
    {'2hsword','2h_sword'}, {'1hsword','1h_sword'}, {'2hmace','2h_mace'}, {'1hmace','1h_mace'},
    {'2haxe','2h_axe'}, {'1haxe','1h_axe'}, {'flail','flail'},
    {'offhandssorc','focus'}, {'offhandsnecro','focus'}, {'offhandswarlock','focus'},
    {'offhandsdruid','totem'}, {'focus','focus'}, {'book','focus'}, {'totem','totem'},
    {'shield','shield'}, {'dagger','dagger'}, {'wand','wand'}, {'staff','staff'}, {'bow','bow'},
    {'amulet','amulet'}, {'necklace','amulet'}, {'ring','ring'},
    {'helm','helm'}, {'hlm','helm'}, {'chest','chest'}, {'trs','chest'},
    {'gloves','gloves'}, {'glove','gloves'}, {'glv','gloves'}, {'pants','pants'}, {'leg','pants'}, {'boots','boots'}, {'bts','boots'},
}
function M.slot_from_skin(skin)
    local lower=skin:lower()
    if lower:find('cosmetic',1,true) or lower:find('qst',1,true) then return nil end
    for _,rule in ipairs(slots) do
        for token in lower:gmatch('[^_]+') do
            if token==rule[1] or token:gsub('^[12]h','')==rule[1]
                or token:match('^'..rule[1]..'%d+$') then return rule[2] end
        end
    end
    -- Older host skins encode handedness by initial capitalization.
    if skin:match('^Sword[_%d]') then return '2h_sword' end
    if skin:match('^sword[_%d]') then return '1h_sword' end
    if skin:match('^Mace[_%d]') then return '2h_mace' end
    if skin:match('^mace[_%d]') then return '1h_mace' end
    if skin:match('^Axe[_%d]') then return '2h_axe' end
    if skin:match('^axe[_%d]') then return '1h_axe' end
end
local patterns = {
    {'charm', {'Talisman_Charm','Item_Charm'}}, {'seal', {'Talisman_Seal'}},
    {'lair_key', {'LairKey','Lair_Key'}}, {'splinter', {'S15_SoulSplinter'}},
    {'heavenly_sigil', {'S11_Heavenly_Sigil'}},
    {'compass', {'BSK_Sigil','Infernal_Compass'}}, {'tribute', {'Undercity_Tribute'}},
    {'sigil', {'Nightmare_Sigil','DungeonKey','S07_WitcherSigil','S07_DRLG_Sigil'}},
    {'rune', {'Generic_Rune','S07_Socketable','Rune_Condition','Rune_Effect'}},
    {'gemstone', {'Item_Gemstone','Gem_'}}, {'fish', {'X2_Fish_'}},
    {'cinders', {'Test_BloodMoon_Currency'}},
    {'crafting', {'CraftingMaterial','Crafting_Legendary'}},
    {'recipe', {'Tempering_Recipe','Item_Book','MountReins','mnt_amor'}},
    {'scroll', {'Scroll_Of'}}, {'cache', {'Item_Cache','Reward_Cache','WarPlans_Cache'}},
    {'quest', {'QST','DGN','Glyph','pvp_currency','GamblingCurrency_Key','Experience_PowerUp_Actor'}},
}
-- QQT_Warpigz_v3 (Q1, live Tuning Prism ghost): Horadric Cube Tuning Prisms
-- (d4data X2_HoradricCube_TuningStone_1..8) go to Materials, never to the
-- consumable bag the generated catalog names, so no bag can confirm them
-- and a full consumable bag never refuses them.
-- QQT_Warpigz_v3 3.3.24 (community patch, @RadicalDadical55): their pickup
-- category must also be crafting: changing only the bag leaves these
-- materials controlled by the Other Consumables checkbox.
local MATERIALS={[2533710]=true,[2533715]=true,[2533718]=true,[2533720]=true,
    [2533724]=true,[2533727]=true,[2533731]=true,[2533733]=true}
M.MATERIALS=MATERIALS
function M.classify(info)
    local id=Utils.call(info,'get_sno_id')
    local known=Current.by_id[id]
    if MATERIALS[id] then return 'crafting', nil, known and known.stack, 'materials' end -- QQT_Warpigz_v3 (Q1); 3.3.24: category crafting
    -- QQT_Warpigz_v3 3.3.24 (community patch): Trace of Echoes (X2_EA_KeyItem)
    -- is kind "unknown" in the shipped catalog; it uses the Lair Keys toggle and
    -- its normal bag/capacity policy. QQT_Warpigz_v3 1.0.35 (Auditor, LOW): the
    -- bag (consumable) and the stack (catalog 1) are not live-checked; a full
    -- consumable bag refuses a Trace even onto a stack (Rosie/NOTES.md).
    if id==2409389 then return 'lair_key', nil, known and known.stack end
    if known then return known.kind, known.slot, known.stack, known.bag end -- QQT_Warpigz_v3 (Q1)
    for _,kind in ipairs({'event_items','boss_items','rare_elixirs','basic_elixirs','advanced_elixirs'}) do
        if Custom[kind][id] then return kind end
    end
    local skin=Utils.call(info,'get_skin_name') or ''
    for _,rule in ipairs(patterns) do
        for _,pattern in ipairs(rule[2]) do
            if skin:find(pattern,1,true) then return rule[1] end
        end
    end
    local slot=M.slot_from_skin(skin)
    if slot then return 'equipment',slot end
    return 'unknown'
end
-- QQT_Warpigz_v3 (Q9): a one-per-character item (rosie/data/carry_once.lua,
-- the Season 15 Splinters of Evil): its entry and SNO, else nil. A later
-- build's SNO missing from the data is recognized by its item skin.
function M.carry_once(info)
    local id=Utils.call(info,'get_sno_id')
    if type(id)~='number' then return nil end
    local known=CarryOnce.by_id[id]
    if known then return known,id end
    local skin=Utils.call(info,'get_skin_name')
    if type(skin)~='string' then return nil end
    for _,prefix in ipairs(CarryOnce.skins) do
        if skin:find(prefix,1,true) then return {name=skin,bag='consumable',must_keep=true},id end
    end
    return nil
end
M.carry_once_data=CarryOnce
return M
