-- Generated by tools/build-rosie.mjs; edit the reviewed source or transform.
local Settings = require('rosie.private.pickup.src.settings')
local Utils = require('rosie.private.pickup.utils.utils')
local CustomItems = require('rosie.private.pickup.data.custom_items')
local CurrentItems = require('rosie.data.items')
local ItemLogic = require('rosie.private.pickup.src.item_logic')
local Pickup = require('rosie.private.pickup.src.pickup')
local M = {}
-- Every recognized category owns its refusal. It must never enter gear rules.
local policies = {
    event_items={'event_items','equipment'}, boss_items={'boss_items','consumable',99},
    rare_elixirs={'rare_elixirs','consumable',99},basic_elixirs={'basic_elixirs','consumable',99},
    advanced_elixirs={'advanced_elixirs','consumable',99},scroll={'scroll','consumable',20},
    other_consumables={'other_consumables','consumable'},
    heavenly_sigil={'heavenly_sigil','consumable'},sigil={'sigils','sigil'},
    compass={'compass','sigil'},tribute={'tribute','sigil'},rune={'rune','socketable',100},
    gemstone={'gemstone','socketable'},charm={'charm','talisman'},seal={'seal','talisman'},
    splinter={'splinter','socketable'},lair_key={'lair_key','consumable'},fish={'fish','equipment'},
    recipe={'crafting_items','equipment'},cache={'cache','equipment'},quest={'quest_items'},
    crafting={'crafting_items'},cinders={'cinders'},
}
local function filter_reason(info,enabled)
    if not enabled then return nil end
    local filtered=Utils.call(info,'is_filtered_by_loot_filter')
    if filtered==true then return 'ingame loot filter' end
    if filtered~=false then return 'ingame loot filter unavailable','deferred' end
end
local function is_mythic(rarity,sno)
    local known=CurrentItems.by_id[sno]
    -- Some native Unique values need the same exact-SNO mythic fallback as
    -- the legacy list. Metadata never promotes lower or unreadable rarities.
    return rarity>=8 or CustomItems.ubers[sno]~=nil
        or rarity==6 and known~=nil and known.kind=='equipment' and known.quality=='mythic'
end
local function equipment_threshold(s,rarity,sno,slot)
    local mythic=is_mythic(rarity,sno)
    local required,source=0,'common_general'
    if mythic then required,source=s.uber_unique_ga_count,'mythic_general'
    elseif rarity==6 then required,source=s.unique_ga_count,'unique_general'
    elseif rarity==5 then required,source=s.ga_count,'legendary_general'
    elseif rarity==3 or rarity==4 then required,source=s.rare_ga_count or 0,'rare_general'
    elseif rarity==1 or rarity==2 then required,source=s.magic_ga_count or 0,'magic_general' end
    local overridden=false
    if s.custom_toggle and not mythic and (rarity==5 or rarity==6) and slot then
        local key=(rarity==6 and 'unique_' or 'legendary_')..slot
        local override=s[key..'_ga_count']
        -- Newly added slot controls inherit the existing general policy at -1.
        if type(override)=='number' and override>=0 then
            required,source,overridden=override,key..'_override',true
        end
    end
    return required,source,overridden
end
function M.check_want_item(item, ignore_distance)
    local player=get_local_player()
    if not player or Utils.call(player,'is_dead')~=false then return false,'character unavailable or dead','deferred' end
    local info=Utils.call(item,'get_item_info')
    if not info or Utils.call(info,'is_valid')~=true then return false,'item data unavailable','deferred' end
    local s=Settings.get()
    if not ignore_distance and Utils.distance_to(item)>s.distance then return false,'outside pickup distance '..s.distance end
    if Utils.host_call(loot_manager.is_gold,item) or Utils.host_call(loot_manager.is_potion,item) then return false,'gold or potion' end
    local lootable=Utils.host_call(loot_manager.is_lootable_item,item,true,true)
    if lootable~=true then return false,'host says not lootable or unavailable',lootable~=false and 'deferred' or nil end
    local kind,slot,max_stack,bag=ItemLogic.classify(info)
    local policy=policies[kind]
    if policy then
        if s[policy[1]]~=true then return false,'category disabled: '..kind end
        if kind=='charm' or kind=='seal' then
            local reason,decision=filter_reason(info,s.respect_filter)
            if reason then return false,reason,decision end
        end
        bag=bag or policy[2]
        if not bag or bag=='currency' then return true,'accepted '..kind end
        local inventory,full=Utils.bag_state(bag)
        if not inventory then return false,'bag unavailable: '..bag,'deferred' end
        if not full then return true,'accepted '..kind end
        max_stack=max_stack or policy[3]
        if max_stack and max_stack>1 then
            local fits,readable=Utils.is_lowest_stack_below(inventory,
                Utils.call(info,'get_sno_id'),max_stack,Utils.call(info,'get_stack_count'))
            if fits then return true,'accepted stack' end
            if not readable then return false,'stack data unavailable: '..bag,'deferred' end
        end
        return false,'bag full or unreadable: '..bag -- category refusal is terminal
    end
    if kind~='equipment' then
        local skin=Utils.call(info,'get_skin_name')
        return false,'unrecognized item type',type(skin)~='string' and 'deferred' or nil
    end
    local inventory,full=Utils.bag_state('equipment')
    if not inventory then return false,'equipment bag unavailable','deferred' end
    if full then return false,'equipment bag full or unreadable' end
    local reason,decision=filter_reason(info,s.respect_filter)
    if reason then return false,reason,decision end
    -- Legacy heuristic, opt-in only: the host exposes no dropped-by-player flag.
    if s.skip_dropped then
        local affixes=Utils.call(info,'get_affixes')
        if type(affixes)~='table' then return false,'visible affix list unavailable','deferred' end
        if #affixes>0 then return false,'legacy Skip gear with visible affixes setting' end
    end
    local rarity=Utils.call(info,'get_rarity')
    if type(rarity)~='number' or rarity~=rarity then return false,'item rarity unavailable','deferred' end
    if rarity<s.rarity then return false,'below minimum rarity or unreadable rarity' end
    local required,threshold,overridden=equipment_threshold(s,rarity,Utils.call(info,'get_sno_id'),slot)
    local ga,ga_readable=Utils.get_ga_count(info)
    if required>0 and not ga_readable then return false,'Greater Affix count unavailable','deferred' end
    return ga>=required, string.format('%s: GA %d, required %d%s [threshold=%s]',ga>=required and 'accepted' or 'below GA minimum',
        ga,required,overridden and ' (slot override enabled)' or '',threshold)
end
local reported={}
function M.describe(item, reason)
    local info=Utils.call(item,'get_item_info')
    local name=tostring(Utils.call(info,'get_display_name') or Utils.call(info,'get_skin_name') or 'unknown'):gsub('[\r\n]',' '):sub(1,120)
    local sno,rarity=Utils.call(info,'get_sno_id'),Utils.call(info,'get_rarity')
    local count,readable,observations=Utils.get_ga_count(info)
    local kind,slot=ItemLogic.classify(info)
    local threshold='category:'..kind
    if kind=='equipment' and type(rarity)=='number' and rarity==rarity then
        local required,source=equipment_threshold(Settings.get(),rarity,sno,slot)
        threshold=source..':'..tostring(required)
    end
    return string.format('%s | sno=%s rarity=%s ancestral=%s GA=%d nativeGA=%s displayGA=%s GA_source=%s GA_readable=%s GA_conflict=%s threshold=%s distance=%.1f | %s',name,
        tostring(sno),tostring(rarity),tostring(Utils.call(info,'is_ancestral')),count,
        tostring(observations.native_raw),tostring(observations.display_count),observations.source,
        tostring(readable),tostring(observations.conflict),threshold,Utils.distance_to(item),reason or 'unknown decision')
end
function M.report_rejection(item, reason)
    local info=Utils.call(item,'get_item_info')
    local rarity=Utils.call(info,'get_rarity')
    if type(rarity)~='number' or rarity~=rarity then rarity=0 end
    if rarity<6 and Utils.get_ga_count(info)==0 then return end
    if Utils.distance_to(item)>60 then return end
    local id=Pickup.key(item)
    if id and reported[id]~=reason then
        reported[id]=reason
        console.print('[Rosie pickup] Skipped '..M.describe(item,reason))
    end
end
function M.observe(items)
    local complete=Pickup.observe(items)
    if not complete then return false end
    local present={}
    for _,item in pairs(items) do local id=Pickup.key(item); if id then present[id]=true end end
    for id in pairs(reported) do if not present[id] then reported[id]=nil end end
end
function M.diagnose()
    Settings.update()
    local s=Settings.get()
    console.print(string.format('[Rosie pickup] enabled=%s paused=%s behavior_ready=%s distance=%s respect_filter=%s skip_affixes=%s custom_GA=%s',
        tostring(s.enabled),tostring(Settings.is_paused()),tostring(Settings.should_execute()),tostring(s.distance),
        tostring(s.respect_filter),tostring(s.skip_dropped),tostring(s.custom_toggle)))
    local count=0
    local items=Utils.host_call(actors_manager.get_all_items)
    if type(items)~='table' then
        console.print('[Rosie pickup] Item list unavailable. Try again after the world loads.')
        return 0
    end
    for _,item in pairs(items) do
        if Utils.distance_to(item)<=60 then
            local wanted,reason=M.check_want_item(item,false)
            local blocked,why=Pickup.blocked(item)
            if wanted and blocked then wanted,reason=false,why end
            console.print('[Rosie pickup] '..(wanted and 'Wanted ' or 'Skipped ')..M.describe(item,reason))
            count=count+1
            if count>=64 then console.print('[Rosie pickup] Diagnostic limited to 64 nearby drops.'); break end
        end
    end
    console.print('[Rosie pickup] Nearby decisions logged: '..count)
    return count
end
function M.calculate_item_score(item)
    local info=Utils.call(item,'get_item_info')
    local rarity=Utils.call(info,'get_rarity') or 0
    local mythic=is_mythic(rarity,Utils.call(info,'get_sno_id'))
    return (mythic and 1000 or rarity>=5 and 500 or rarity>=3 and 300 or rarity>=1 and 100 or 10)
        + Utils.get_ga_count(info)*25
end
local selected_key
local function choose(best_first)
    local items=Utils.host_call(actors_manager.get_all_items)
    M.observe(items)
    if type(items)~='table' then return nil end
    local selected,score,distance
    local previous,previous_score,previous_distance
    for _,item in pairs(items) do
        local wanted,reason=M.check_want_item(item,false)
        local blocked,why=Pickup.blocked(item)
        if wanted and blocked then wanted,reason=false,why end
        if wanted then
            local d=Utils.distance_to(item)
            local value=best_first and M.calculate_item_score(item) or 0
            if Pickup.key(item)==selected_key then previous,previous_score,previous_distance=item,value,d end
            if not selected or value>score or value==score and d<distance then
                selected,score,distance=item,value,d
            end
        else M.report_rejection(item,reason) end
    end
    -- Keep equally valuable nearby targets stable; a better item still wins.
    if previous and previous_score==score and previous_distance<=distance+1.5 then selected,score=previous,previous_score end
    selected_key=selected and Pickup.key(selected) or nil
    return selected,score
end
function M.get_nearby_item() return (choose(false)) end
function M.get_best_item()
    local item,score=choose(true)
    return item and {Item=item,Score=score} or nil
end
function M.get_item_based_on_priority()
    if Settings.get().loot_priority==0 then return M.get_nearby_item() end
    return M.get_best_item()
end
return M
