-- Generated by tools/build-rosie.mjs; edit the reviewed source or transform.
-- QQT_Warpigz_v2 local patch (live 2.3.0-rc.8, LooteerV3 mechanics): walk to a
-- drop farther than REACH, interact with it every INTERACT_GAP inside REACH
-- (LooteerV3 main.lua handle_loot). Rosie 1.0.1 gave a drop 5 interactions or
-- 12 s of selection and then skipped it until it left the ground, so a drop
-- that fell during a boss fight (player casting, rotation moving) was lost.
-- Still bounded (C6): a round ends after ROUND_INTERACTS interactions in reach
-- or ROUND_STALL s without getting PROGRESS closer; the drop then rests
-- REST s while other wanted drops go first (with none waiting its next round
-- starts at once) and after MAX_ROUNDS rounds it is skipped until it leaves
-- the ground.
local pathfinder=require('rosie.movement').for_owner('pickup')
local Utils=require('rosie.private.pickup.utils.utils')
local events=require('rosie.private.qqt_events') -- QQT_Warpigz_v3
local M={}
local entries={}
local movement_owned=false
local movement_key=nil
local REACH=2
local INTERACT_GAP=0.15
local MOVE_GAP=0.35
local ROUND_INTERACTS=30
local ROUND_STALL=6
local PROGRESS=0.5
local REST=8
local MAX_ROUNDS=3
-- QQT_Warpigz_v3 (night audit R5, live 12-39 s Helltide waits): a resting
-- drop is woken as soon as nothing else is wanted, so N drops that
-- interaction cannot take kept busy set for about N x 13-18 s in one
-- episode. An episode (pickup busy, ending after EPISODE_QUIET s without a
-- step) gets EPISODE_BUDGET s without a drop leaving the ground; then every
-- remaining drop rests REST x MAX_ROUNDS s (not woken meanwhile), pickup
-- reports not busy and it is logged once. A drop picked up restarts the budget.
local EPISODE_BUDGET=20
local EPISODE_QUIET=2
local episode={since=nil,last=nil,capped_until=0}
-- QQT_Warpigz_v3 (Q1, live Tuning Prism ghost): the host can keep listing a
-- ground actor the game already gave the player (the prism went to
-- Materials on the first interaction) or one the player cannot approach.
-- Only the actor leaving the list used to end a drop, so such a ghost got 3
-- rounds of busy (live: 33.6 s of Helltide yield), again each time it
-- streamed out of the list and back. A drop is now SETTLED (not tried again
-- while listed; same identifier, SNO and spot; forgotten settle_ttl s after
-- it was last listed, on a world change or reset), logged once, when
--  * its bag gained its SNO after an interaction in reach (receipt);
--  * it goes to no bag (Materials, currency, crafting, quest) and was
--    interacted with in reach for nonbag_clear s of CLEAR time ("taken");
--  * a small bag item (rune, gem, splinter, sigil, consumable) stays at the
--    same spot after small_interacts (one full round) CLEAR interactions in
--    reach and no receipt;
--  * a round ends without progress toward it during CLEAR time and it is
--    not gear, or no walkable point within reach of it exists.
-- QQT_Warpigz_v3 (Q1 review, rc.10 R6): CLEAR means the player could act on
-- the drop: not casting, no live enemy within fight_radius m and the host
-- executed Rosie's move. In a fight nothing counts toward a settle and the
-- drop keeps the bounded rounds (still capped by the 20 s episode budget),
-- so drops that fall during a fight are collected after it.
-- Gear (equipment and talisman bags) keeps the bounded rounds (fights, rc.8).
-- A drop settled without a receipt gets ONE more attempt when the player's
-- own route brings it back within reach after being away (Rosie never
-- walks back for it): a fight may have swallowed the interactions.
-- QQT_Warpigz_v3 3.3.2 (live report, Pit elite and Helltide: the player
-- walked back and forth between a drop and the fight): two movers took
-- turns on the one native path. Rosie walked to a drop while the farm plugin
-- (Arkham kill_monster once its 15 s pickup hold ran out, HR after its 15 s
-- loot hold, Batmobile freeroam after 10 s) or the host's combat movement
-- walked the player to the enemy; each overrode the other every pulse, and a
-- failed round was woken at once when nothing else was wanted. Now:
--  * FIGHT: while a live enemy is within fight_radius m (the hold ends only
--    when none is within fight_radius+FIGHT.margin m for FIGHT.calm s),
--    Rosie does not walk to a drop farther than FIGHT.feet m and reports not
--    busy, so the farm plugin fights; the drop is taken after the fight.
--    Drops at the feet are still interacted with. At most FIGHT.max s of
--    continuous hold (C6: an enemy that never dies), logged once.
--  * YIELD: while Rosie works a drop, a move destination that is neither
--    Rosie's last move, the drop nor the player's spot (another mover) for
--    YIELD.confirm s while the player moves YIELD.moved m makes Rosie step back without clearing that path; the
--    drop is not tried (nor woken) for YIELD.rest s, doubling per yield of
--    that drop up to YIELD.max s (its rounds still bound it, C6).
--    QQT_Warpigz_v3 1.0.23: every YIELD.per_round yields of a drop fail one
--    of its rounds.
local G={nonbag_interacts=3,nonbag_clear=3.5,small_interacts=ROUND_INTERACTS,settle_ttl=180,settle_max=128,same_spot=1.0,
    away=REACH+2,settled={},count=0,world=nil,retried={},fight_radius=10,movement=require('rosie.movement')}
M.limits={reach=REACH,round_interacts=ROUND_INTERACTS,round_stall=ROUND_STALL,rest=REST,max_rounds=MAX_ROUNDS,
    episode_budget=EPISODE_BUDGET,nonbag_interacts=G.nonbag_interacts,small_interacts=G.small_interacts,
    nonbag_clear=G.nonbag_clear,fight_radius=G.fight_radius,settle_ttl=G.settle_ttl} -- QQT_Warpigz_v3 (Q1)
local function key(item)
    local ok,id=pcall(loot_manager.get_item_identifier,item)
    if not ok then return nil end
    if type(id)=='number' and id>0 then return tostring(id) end
    local info=Utils.call(item,'get_item_info')
    local position=Utils.call(item,'get_position')
    if not info or not position then return nil end
    -- Ambiguous stacked drops share a finite budget until this location empties.
    local sno=Utils.call(info,'get_sno_id')
    local x,y,z=Utils.call(position,'x'),Utils.call(position,'y'),Utils.call(position,'z')
    if type(sno)~='number' or type(x)~='number' or type(y)~='number' or type(z)~='number' then return nil end
    return tostring(sno)..':'..string.format('%.1f:%.1f:%.1f',x,y,z)
end
-- QQT_Warpigz_v3 (Q1): helpers of the settled drops (see the header).
local function point_of(item)
    local p=Utils.call(item,'get_position')
    local x,y,z=Utils.call(p,'x'),Utils.call(p,'y'),Utils.call(p,'z')
    if type(x)~='number' or type(y)~='number' then return nil end
    return {x=x,y=y,z=type(z)=='number' and z or 0}
end
local function sno_of(item) return Utils.call(Utils.call(item,'get_item_info'),'get_sno_id') end
local function unsettle(id) if G.settled[id] then G.settled[id]=nil;G.count=G.count-1 end end
local function settled_of(id,item)
    local s=G.settled[id]
    if not s then return nil end
    local p=point_of(item)
    if s.sno~=sno_of(item) or not p or math.abs(p.x-s.x)>G.same_spot or math.abs(p.y-s.y)>G.same_spot then
        unsettle(id);G.retried[id]=nil;return nil -- a recycled identifier: another drop
    end
    return s
end
function M.release_movement(clear)
    if movement_owned and clear~=false then pcall(pathfinder.clear_stored_path) end
    movement_owned=false
    movement_key=nil
end
-- QQT_Warpigz_v3: suite 'pickup' event. A drop's description is read once,
-- when Rosie starts on it; the event goes out when a drop Rosie interacted
-- with in reach leaves the ground list in the same world, or a bag receipt
-- (or a no-bag take) settles it. M.is_mythic is set by item_manager.
local announce
function M.observe(items)
    if type(items)~='table' then M.release_movement(); return false end
    local seen,complete={},true
    -- QQT_Warpigz_v3 (Q1): settled drops are forgotten on a world change and
    -- settle_ttl s after they were last listed.
    local now=get_time_since_inject()
    local world=Utils.call(Utils.host_call(rawget(_G,'get_current_world')),'get_world_id')
    world=world~=nil and tostring(world) or G.world -- a failed read is no world change
    if world~=G.world then G.settled,G.count,G.world,G.retried={},0,world,{} end
    for _,item in pairs(items) do
        local id=key(item)
        if id then seen[id]=true;if G.settled[id] then G.settled[id].seen=now end else complete=false end
    end
    for id,s in pairs(G.settled) do
        if now-s.seen>G.settle_ttl or now<s.seen then unsettle(id);G.retried[id]=nil end
    end
    -- An unreadable list or identity cannot prove that a previous drop vanished.
    if complete then
        for id in pairs(entries) do
            if not seen[id] then
                local gone=entries[id] -- QQT_Warpigz_v3: suite event
                if gone and gone.touched and gone.world==world then announce(gone) end
                entries[id]=nil;G.retried[id]=nil -- QQT_Warpigz_v3 (Q1)
                if episode.since then episode.since=get_time_since_inject() end -- QQT_Warpigz_v3: progress
            end
        end
    end
    return complete
end
-- QQT_Warpigz_v2 local patch (Rosie 1.0.7): bounded rounds, then a rest.
function M.blocked(item)
    local id=key(item); if not id then return true,'item identifier unavailable' end
    local s=settled_of(id,item) -- QQT_Warpigz_v3 (Q1): see the header
    if s then
        if s.retry and not G.retried[id] then
            local d=Utils.distance_to(item)
            if d>G.away and d~=math.huge then s.away=true
            elseif s.away and d<=REACH then unsettle(id);G.retried[id]=s.why;return false end
        end
        return true,'pickup settled: '..s.why..' (the host still lists it)'
    end
    local e=entries[id]
    if not e then return false end
    if e.rounds>=MAX_ROUNDS then
        return true,e.why=='stall' and 'pickup approach failed '..MAX_ROUNDS..' times'
            or 'pickup attempts exhausted ('..MAX_ROUNDS..' rounds)'
    end
    -- QQT_Warpigz_v3 3.3.2: stepped back for another mover (see the header).
    if e.yield_until and get_time_since_inject()<e.yield_until then return true,'pickup yielded to another move' end
    -- A stable reason: the rejection log prints once per drop and reason.
    if get_time_since_inject()<e.rest_until then return true,'pickup resting after round '..e.rounds..' ('..REST..'s)' end
    return false
end
M.key=key
-- QQT_Warpigz_v3 1.0.23 (perf): M.blocked changes state only for a settled
-- drop (its away/retry mark). With none settled, a caller that does not use
-- its answer may skip it.
function M.tracking() return next(G.settled)~=nil end
-- QQT_Warpigz_v2 local patch (review rc.10): a drop resting between rounds
-- with rounds left. When no other wanted drop is waiting, the rest ends at
-- once (wake): the busy flag never drops while Rosie still means to take it,
-- so activity loot holds (Reaper, HordeDev, WonderCity, Arkham) keep waiting.
-- QQT_Warpigz_v3 3.3.2: a drop that yielded to another mover rests too
-- (not settled), but only `wakeable` asks whether wake may end it (never).
function M.resting(item,wakeable)
    local id=key(item); local e=id and entries[id]
    if e==nil or e.rounds>=MAX_ROUNDS then return false end
    local now=get_time_since_inject()
    local yielded=e.yield_until~=nil and now<e.yield_until
    if wakeable then return not yielded and now<e.rest_until end
    return yielded or now<e.rest_until
end
function M.wake(item)
    if get_time_since_inject()<episode.capped_until then return false end -- QQT_Warpigz_v3: budget rest
    local id=key(item); local e=id and entries[id]
    if e and e.yield_until and get_time_since_inject()<e.yield_until then return false end -- QQT_Warpigz_v3 3.3.2
    if e then e.rest_until=0 end
    return true
end
-- QQT_Warpigz_v2 local patch (Rosie 1.0.7): end a round (see the header).
local function item_name(item)
    local info=Utils.call(item,'get_item_info')
    return tostring(Utils.call(info,'get_display_name') or Utils.call(info,'get_skin_name') or 'item'):gsub('[\r\n]',' '):sub(1,80)
end
-- QQT_Warpigz_v3: suite event (see M.observe).
local function describe(item)
    local info=Utils.call(item,'get_item_info')
    local rarity=Utils.call(info,'get_rarity')
    if type(rarity)~='number' or rarity~=rarity then rarity=nil end
    local sno=Utils.call(info,'get_sno_id')
    local mythic=false
    if rarity and type(M.is_mythic)=='function' then
        local ok,m=pcall(M.is_mythic,rarity,sno,info); mythic=ok and m==true
    end
    local ok,ga=pcall(Utils.get_ga_count,info)
    return {name=item_name(item),sno=type(sno)=='number' and sno or nil,rarity=rarity,mythic=mythic,
        ancestral=Utils.call(info,'is_ancestral')==true,ga=ok and type(ga)=='number' and ga or nil}
end
announce=function(e)
    if not e.desc or e.announced then return end
    e.announced=true
    events.emit('rosie','pickup',e.desc)
end
local function fail_round(e,now,why,item,d)
    e.rounds=e.rounds+1;e.why=why;e.rest_until=now+REST
    -- QQT_Warpigz_v2 (live rc.13): name the drop Rosie could not take.
    console.print(string.format('[Rosie pickup] %s %s: round %d/%d failed (%s, distance %.1f)',
        e.rounds>=MAX_ROUNDS and 'Gave up on' or 'Retrying',item and item_name(item) or 'item',e.rounds,MAX_ROUNDS,
        why=='stall' and 'no progress toward it' or why=='yield' and 'another move kept taking the player off it' -- QQT_Warpigz_v3 1.0.23
            or 'interactions did not pick it up',d or -1))
    e.interacts=0;e.best=nil;e.best_at=nil;e.working=false;e.next=0
end
-- QQT_Warpigz_v3 (Q1): settle a drop (see the header); one line per drop and outcome.
local function settle(id,item,why,line,retry,d)
    local p=point_of(item) or {x=0,y=0}
    if not G.settled[id] then G.count=G.count+1 end
    if G.count>G.settle_max then G.settled,G.count={},1 end
    local now=get_time_since_inject()
    local before=G.retried[id]
    -- QQT_Warpigz_v3 (Q1 review): a second retry is already blocked by G.retried;
    -- receipt = a bag receipt proved the take (the only verdict that never carries over).
    G.settled[id]={sno=sno_of(item),x=p.x,y=p.y,seen=now,why=why,retry=retry==true,away=d>REACH,
        receipt=why=='taken' and retry~=true}
    if why=='taken' and entries[id] then announce(entries[id]) end -- QQT_Warpigz_v3: suite event
    entries[id]=nil
    if episode.since and why=='taken' then episode.since=now end -- only a pickup is progress (20 s budget)
    if before==why then return end
    local ok,interactable=pcall(function() return item:is_interactable() end)
    console.print(string.format('[Rosie pickup] %s %s%s [interactable=%s]',why=='taken' and 'Took' or 'Leaving',
        item_name(item),line,ok and tostring(interactable) or '?'))
end
-- QQT_Warpigz_v3 (Q9): a drop the game refused (or Rosie could not reach)
-- is remembered by SNO and spot too, not only by identifier: if the host
-- lists it again under a new identifier after it streamed out and back in,
-- the verdict carries over (no new attempts, no new line) until settle_ttl.
-- A drop a bag receipt proved taken never carries over: a second copy of the
-- same SNO at the same spot is a real drop. QQT_Warpigz_v3 (Q1 review): a
-- no-bag 'taken' (no receipt, the live prism ghost) carries over like
-- 'refused' and 'unreachable'. The spot must match within
-- G.same_actor m (a re-listed actor keeps its position; drops of one kill
-- scatter farther apart and each gets its own verdict).
G.same_actor=0.2
local function settled_spot(id,item)
    if G.count<=0 or G.retried[id] then return nil end
    local sno=sno_of(item)
    if type(sno)~='number' then return nil end
    local p
    for _,s in pairs(G.settled) do
        if not s.receipt and s.sno==sno then -- QQT_Warpigz_v3 (Q1 review)
            p=p or point_of(item)
            if not p then return nil end
            if math.abs(p.x-s.x)<=G.same_actor and math.abs(p.y-s.y)<=G.same_actor then
                G.count=G.count+1
                G.settled[id]={sno=sno,x=s.x,y=s.y,seen=get_time_since_inject(),why=s.why,retry=false,away=false}
                return G.settled[id]
            end
        end
    end
    return nil
end
-- QQT_Warpigz_v3: true when this episode's budget is spent (see the header).
local function episode_spent(now,e)
    if not episode.last or now-episode.last>=EPISODE_QUIET or now<(episode.last or now) then episode.since=now end
    episode.last=now
    if now-episode.since<EPISODE_BUDGET then return false end
    local rest=REST*MAX_ROUNDS
    local count=0
    for _,entry in pairs(entries) do
        if entry.rounds<MAX_ROUNDS then entry.rest_until=math.max(entry.rest_until or 0,now+rest);count=count+1 end
    end
    if e.rounds<MAX_ROUNDS and e.rest_until<now+rest then e.rest_until=now+rest;count=count+1 end
    e.interacts=0;e.best=nil;e.best_at=nil;e.working=false;e.next=0
    episode.capped_until=now+rest
    episode.since,episode.last=nil,nil
    console.print(string.format('[Rosie pickup] busy %ds without picking anything up; resting %d drop(s) for %ds',
        EPISODE_BUDGET,count,rest))
    return true
end
-- QQT_Warpigz_v3 (Q1 review): true while the player cannot act on a drop
-- (see the header): casting, a live enemy within fight_radius m, or the host
-- kept its current move instead of Rosie's pickup move. Read at most every 0.25 s.
local function fighting(now)
    if G.fight_at and now>=G.fight_at and now-G.fight_at<0.25 then return G.fight end
    G.fight_at=now
    local spell=Utils.call(Utils.host_call(rawget(_G,'get_local_player')),'get_active_spell_id')
    local fight=type(spell)=='number' and spell>0
    if not fight then
        local st=Utils.host_call(G.movement.status)
        fight=type(st)=='table' and st.owner=='pickup' and type(st.detail)=='string'
            and st.detail:find('host kept',1,true)~=nil
    end
    G.fight=fight or Utils.enemy_near(G.fight_radius)
    return G.fight
end
-- QQT_Warpigz_v3 3.3.2: FIGHT hold and YIELD to another mover (see the header).
local FIGHT={feet=REACH+1,margin=4,calm=1.0,max=45,on=false}
local YIELD={confirm=0.3,rest=4,max=30,far=REACH+0.5,sent=1.5,moved=0.5,per_round=2}
M.limits.fight_feet,M.limits.fight_calm,M.limits.fight_max=FIGHT.feet,FIGHT.calm,FIGHT.max
M.limits.yield_rest,M.limits.yield_max=YIELD.rest,YIELD.max
M.limits.yield_per_round=YIELD.per_round -- QQT_Warpigz_v3 1.0.23
-- QQT_Warpigz_v3 1.0.22: a drop that waits for the fight is published as
-- LooteerPlugin.has_pending_loot(). Until every exit guard (Arkham, Reaper,
-- HordeDev, WonderCity, HelltideRevamped, SilentRaven, WarPigs) also reads
-- it, the wait still reports busy too, or those exits would leave the drop.
-- Set to false once they do (audit/BOARD.md): the farm plugin then fights.
M.fight_wait_busy=true
local function xy(v)
    local x,y=Utils.call(v,'x'),Utils.call(v,'y')
    if type(x)~='number' or type(y)~='number' then return nil end
    return {x=x,y=y}
end
local function flat(a,b) return math.sqrt((a.x-b.x)^2+(a.y-b.y)^2) end
local function fight_hold(now)
    if FIGHT.at and now>=FIGHT.at and now-FIGHT.at<0.25 then return FIGHT.on and not FIGHT.capped end
    -- QQT_Warpigz_v3 1.0.23: only a waiting drop evaluates the hold. Unread
    -- for longer than FIGHT.calm (+ the 0.25 s cache), the last fight's hold is
    -- stale: a later fight starts its own FIGHT.max instead of being capped at once.
    -- A drop resting after a yield is not read either: its rest keeps the
    -- hold fresh (FIGHT.keep), so each yield does not restart FIGHT.max.
    if FIGHT.at and (now<FIGHT.at or now-math.max(FIGHT.at,FIGHT.keep or -math.huge)>=FIGHT.calm+0.25) then
        FIGHT.on,FIGHT.since,FIGHT.last,FIGHT.capped,FIGHT.keep=false,nil,nil,nil,nil
    end
    FIGHT.at=now
    if Utils.enemy_near(FIGHT.on and G.fight_radius+FIGHT.margin or G.fight_radius) then
        FIGHT.last=now
        if not FIGHT.on then FIGHT.on,FIGHT.since,FIGHT.capped=true,now,nil end
    elseif FIGHT.on and not (FIGHT.last and now>=FIGHT.last and now-FIGHT.last<FIGHT.calm) then
        FIGHT.on,FIGHT.since,FIGHT.capped=false,nil,nil
    end
    if FIGHT.on and not FIGHT.capped and (now-FIGHT.since>=FIGHT.max or now<FIGHT.since) then
        FIGHT.capped=true
        console.print(string.format('[Rosie pickup] A fight kept pickup waiting %ds; picking up during it',FIGHT.max))
    end
    return FIGHT.on and not FIGHT.capped
end
-- True while a drop farther than FIGHT.feet m waits for the fight to end.
function M.fight_deferred(item,now)
    local d=Utils.distance_to(item)
    return d>FIGHT.feet and d~=math.huge and fight_hold(now or get_time_since_inject())
end
local function foreign_move(e,item,now)
    if not e.working then e.foreign=nil;return false end
    local player=Utils.host_call(rawget(_G,'get_local_player'))
    local dest,here,spot=xy(Utils.call(player,'get_move_destination')),xy(Utils.call(player,'get_position')),xy(Utils.call(item,'get_position'))
    if not dest or not here or not spot or flat(dest,here)<=YIELD.far or flat(dest,spot)<=YIELD.far then e.foreign=nil;return false end
    local st=movement_owned and Utils.host_call(G.movement.status)
    local sent=type(st)=='table' and st.owner=='pickup' and st.sent
    if sent and flat(dest,sent)<=YIELD.sent then e.foreign=nil;return false end
    if not e.foreign or now<e.foreign then e.foreign,e.foreign_from=now,here end
    -- the player must also move meanwhile: a stale destination of a player
    -- standing at the drop is nobody's move
    return now-e.foreign>=YIELD.confirm and flat(here,e.foreign_from)>=YIELD.moved
end
local function stand_down(e,item,now)
    e.yields=(e.yields or 0)+1
    local rest=math.min(YIELD.rest*2^(e.yields-1),YIELD.max)
    e.yield_until=now+rest;e.working=false;e.next=0;e.foreign=nil;e.best=nil;e.best_at=nil
    FIGHT.keep=math.max(FIGHT.keep or -math.huge,e.yield_until) -- QQT_Warpigz_v3 1.0.22: see fight_hold
    if movement_owned then pcall(G.movement.yield,'pickup') end -- never clears the other mover's path
    movement_owned=false;movement_key=nil
    if e.yields<=3 then
        console.print(string.format('[Rosie pickup] Another move took the player off %s; leaving it for %ds (yield %d)',
            item_name(item),rest,e.yields))
    end
    -- QQT_Warpigz_v3 1.0.23: a yield counted no round, so a drop that kept
    -- losing the path came back every YIELD.max s forever. Every
    -- YIELD.per_round yields of a drop fail a round; its rounds bound it (C6).
    if e.yields%YIELD.per_round==0 then fail_round(e,now,'yield',item,Utils.distance_to(item)) end
end
function M.step(item,kind,bag) -- QQT_Warpigz_v3 (Q1): kind and bag from ItemManager.destination
    if M.blocked(item) then M.release_movement(); return false end
    local id=key(item); local now=get_time_since_inject()
    if not id then M.release_movement(); return false end
    local e=entries[id]
    if not e and settled_spot(id,item) then M.release_movement(); return false end -- QQT_Warpigz_v3 (Q9)
    if not e then
        -- QQT_Warpigz_v3 (Q1): gear keeps the rounds; 'nonbag' has no receipt.
        e={rounds=0,rest_until=0,interacts=0,next=0,bag=bag,sno=sno_of(item),reach=0,
            class=(kind==nil or bag=='equipment' or bag=='talisman') and 'gear' or bag and 'small' or 'nonbag'}
        if events.bus() then -- QQT_Warpigz_v3: suite event (no bus: no describe cost)
            local ok_desc,desc=pcall(describe,item)
            e.desc=ok_desc and desc or nil
        end
        e.world=G.world
        entries[id]=e
    end
    -- QQT_Warpigz_v3 (Q1): another drop went first meanwhile (it may share
    -- this SNO): read this drop's bag baseline again before its next interaction.
    if G.last~=id then e.receipt=nil;G.last=id end
    -- QQT_Warpigz_v3 3.3.2: no walk out of a fight, no tug of war (see the header).
    if M.fight_deferred(item,now) then e.working=false;e.foreign=nil;e.best=nil;M.release_movement();return false end
    if foreign_move(e,item,now) then stand_down(e,item,now);return false end
    if episode_spent(now,e) then M.release_movement(); return false end
    if movement_owned and movement_key~=id then M.release_movement() end
    local d=Utils.distance_to(item)
    if d==math.huge then M.release_movement(); return false end
    -- QQT_Warpigz_v3 (Q1 review): CLEAR time in reach (see the header).
    local fight=fighting(now)
    if fight then e.fight_at=now end
    if d<=REACH and not fight then
        if e.clear_last and now>=e.clear_last and now-e.clear_last<=0.5 then e.clear=(e.clear or 0)+now-e.clear_last end
        e.clear_last=now
    else e.clear_last=nil end
    -- QQT_Warpigz_v3 (Q1): receipts and settle rules (see the header).
    if e.receipt then
        local n=Utils.sno_count(e.bag,e.sno)
        if n and n>e.receipt then
            settle(id,item,'taken',' (now in the '..e.bag..' bag; the host still lists it on the ground, ignoring it)',false,d)
            M.release_movement();return false
        end
    end
    if e.class=='nonbag' and e.reach>=G.nonbag_interacts and (e.clear or 0)>=G.nonbag_clear then -- QQT_Warpigz_v3 (Q1 review)
        settle(id,item,'taken',' (it goes to no bag; the host still lists it on the ground, ignoring it)',true,d)
        M.release_movement();return false
    end
    if e.class=='small' and e.reach>=G.small_interacts then
        settle(id,item,'refused',string.format(': still on the ground after %d interactions in reach (the game did not take it)',e.reach),true,d)
        M.release_movement();return false
    end
    -- Progress is measured toward the drop, not as selection time: a fight
    -- that keeps the player busy ends a round, never the drop. A pause, a
    -- town trip or another drop first restarts the measurement.
    if e.seen_at and now-e.seen_at>1 then e.best=nil end
    e.seen_at=now
    if not e.best or d<e.best-PROGRESS or d<=REACH then e.best=math.min(d,e.best or d);e.best_at=now end
    -- QQT_Warpigz_v2 local patch: a round that ends with rounds left keeps the busy flag for this frame
    -- (the next pulse wakes it or serves another drop; review rc.10).
    if d>REACH and now-e.best_at>=ROUND_STALL then
        -- QQT_Warpigz_v3 (Q1): not gear, or no walkable point within reach of
        -- it: no more rounds. QQT_Warpigz_v3 (Q1 review): only a CLEAR window
        -- settles; a fight in it keeps the bounded rounds.
        if not (e.fight_at and e.fight_at>=e.best_at) then
            local p=e.class=='gear' and point_of(item)
            local proof=p and Utils.walkable_near(p.x,p.y,p.z,REACH)==false and 'not walkable' or nil
            if e.class~='gear' or proof then
                settle(id,item,'unreachable',string.format(': cannot reach it (%s, distance %.1f)',proof or 'no progress',d),true,d)
                M.release_movement();return false
            end
        end
        fail_round(e,now,'stall',item,d);M.release_movement();return e.rounds<MAX_ROUNDS
    end
    if e.interacts>=ROUND_INTERACTS then fail_round(e,now,'interact',item,d);M.release_movement();return e.rounds<MAX_ROUNDS end
    if now<e.next then return e.working==true end
    if d>REACH then
        e.next=now+MOVE_GAP
        local position=Utils.call(item,'get_position')
        if not position then M.release_movement(); return false end
        local ok,result=pcall(pathfinder.request_move,position)
        if not ok or result==false then
            M.release_movement()
            e.working=false
            return false
        end
        movement_owned=true
        movement_key=id
    else
        e.next=now+INTERACT_GAP
        M.release_movement()
        -- QQT_Warpigz_v3 (Q1): the bag reading before the first interaction
        -- in reach, and the spot the in-reach count belongs to.
        local p=point_of(item)
        if p and e.spot and (math.abs(p.x-e.spot.x)>G.same_spot or math.abs(p.y-e.spot.y)>G.same_spot) then
            e.reach=0;e.clear=0;e.spot=nil -- QQT_Warpigz_v3 (Q1 review): another spot, another count
        end
        if not e.spot then e.spot=p end
        if e.bag and e.receipt==nil then e.receipt=Utils.sno_count(e.bag,e.sno) end
        if not fight then e.reach=e.reach+1 end -- QQT_Warpigz_v3 (Q1 review): only CLEAR interactions count
        e.interacts=e.interacts+1
        e.touched=true -- QQT_Warpigz_v3: suite event
        pcall(interact_object,item)
    end
    e.working=true
    return true
end
function M.reset(clear_movement)
    M.release_movement(clear_movement); entries={}
    G.settled,G.count,G.retried,G.last=({}),0,({}),nil -- QQT_Warpigz_v3 (Q1)
    G.fight_at,G.fight=nil,nil -- QQT_Warpigz_v3 (Q1 review)
    episode.since,episode.last,episode.capped_until=nil,nil,0 -- QQT_Warpigz_v3
    FIGHT.on,FIGHT.at,FIGHT.since,FIGHT.last,FIGHT.capped,FIGHT.keep=false,nil,nil,nil,nil,nil -- QQT_Warpigz_v3 3.3.2 (keep: 1.0.22)
end
return M
