-- Generated by tools/build-rosie.mjs; edit the reviewed source or transform.
local gui = require("rosie.private.pickup.gui")

local Settings = {}
local paused = false
local pause_owners = {}

local settings = {
   enabled = false,
   looting = false,
   custom_toggle = false,
   isArmor = false ,
   behavior = 0,
   rarity = 0,
   distance = 2,
   skip_dropped = false,
   loot_priority = 0,
   ga_count = 0,
   unique_ga_count = 0,
   uber_unique_ga_count = 0,
   quest_items = false,
   crafting_items = false,
   cinders = false,
   heavenly_sigil = false,
   boss_items = false,
   rare_elixirs = false,
   advanced_elixirs = false,
   basic_elixirs = false,
   other_consumables = false,
   sigils = false,
   compass = false,
   rune = false,
   tribute = false,
   scroll = false,
   event_items = true,
   --jewerly
   legendary_amulet_ga_count = 0,
   legendary_ring_ga_count = 0,
   unique_amulet_ga_count = 0,
   unique_ring_ga_count = 0,
   --armors
   legendary_helm_ga_count = 0,
   legendary_chest_ga_count = 0,
   legendary_gloves_ga_count = 0,
   legendary_pants_ga_count = 0,
   legendary_boots_ga_count = 0,
   unique_helm_ga_count = 0,
   unique_chest_ga_count = 0,
   unique_gloves_ga_count = 0,
   unique_pants_ga_count = 0,
   unique_boots_ga_count = 0,
   --offhand
   legendary_focus_ga_count = 0,
   legendary_totem_ga_count = 0,
   unique_focus_ga_count = -1,
   unique_totem_ga_count = -1,
   legendary_shield_ga_count = -1,
   unique_shield_ga_count = -1,
   legendary_1h_scythe_ga_count = -1,
   unique_1h_scythe_ga_count = -1,
   legendary_2h_scythe_ga_count = -1,
   unique_2h_scythe_ga_count = -1,
   legendary_flail_ga_count = -1,
   unique_flail_ga_count = -1,

   --wepeons
   --1h
   legendary_1h_mace_ga_count = 0,
   legendary_1h_sword_ga_count = 0,
   legendary_1h_axe_ga_count = 0,
   legendary_dagger_ga_count = 0,
   legendary_wand_ga_count = 0,
   unique_1h_mace_ga_count = 0,
   unique_1h_sword_ga_count = 0,
   unique_1h_axe_ga_count = 0,
   unique_dagger_ga_count = 0,
   unique_wand_ga_count = 0,
   --2h
   legendary_2h_mace_ga_count = 0,
   legendary_2h_sword_ga_count = 0,
   legendary_2h_axe_ga_count = 0,
   legendary_2h_polearm_ga_count = 0,
   legendary_staff_ga_count = 0,
   legendary_bow_ga_count = 0,
   legendary_crossbow_ga_count = 0,
   legendary_glaive_ga_count = 0,
   legendary_quarterstaff_ga_count = 0,
   unique_2h_mace_ga_count = 0,
   unique_2h_sword_ga_count = 0,
   unique_2h_axe_ga_count = 0,
   unique_2h_polearm_ga_count = 0,
   unique_staff_ga_count = 0,
   unique_bow_ga_count = 0,
   unique_crossbow_ga_count = 0,
   unique_glaive_ga_count = 0,
   unique_quarterstaff_ga_count = 0,

   draw_wanted_items = false
}

function Settings.update()
   local next_settings = {
      enabled = gui.elements.main_toggle:get(),
      
      -- General Settings
      behavior = gui.elements.general.behavior_combo:get(),
      rarity = gui.elements.general.rarity_combo:get(),
      distance = gui.elements.general.distance_slider:get(),
      skip_dropped = gui.elements.general.skip_dropped_toggle:get(),
      respect_filter = gui.elements.general.respect_filter_toggle:get(),
      loot_priority = gui.elements.general.loot_priority_combo:get(),
      
      -- Affix Settings
      ga_count = gui.elements.affix_settings.greater_affix_slider:get(),
      unique_ga_count = gui.elements.affix_settings.unique_greater_affix_slider:get(),
      uber_unique_ga_count = gui.elements.affix_settings.uber_unique_greater_affix_slider:get(),
      magic_ga_count = gui.elements.affix_settings.magic_greater_affix_slider:get(),
      rare_ga_count = gui.elements.affix_settings.rare_greater_affix_slider:get(),
      legendary_amulet_ga_count = gui.elements.affix_settings.legendary_amulet_slider:get(),
      unique_amulet_ga_count = gui.elements.affix_settings.unique_amulet_slider:get(),
      unique_ring_ga_count = gui.elements.affix_settings.unique_ring_slider:get(),
      legendary_ring_ga_count = gui.elements.affix_settings.legendary_ring_slider:get(),
      
      -- Armors Settings
      custom_toggle = gui.elements.affix_settings.custom_toggle:get(),
      legendary_helm_ga_count = gui.elements.affix_settings.legendary_helm_slider:get(),
      legendary_chest_ga_count = gui.elements.affix_settings.legendary_chest_slider:get(),
      legendary_gloves_ga_count = gui.elements.affix_settings.legendary_gloves_slider:get(),
      legendary_pants_ga_count = gui.elements.affix_settings.legendary_pants_slider:get(),
      legendary_boots_ga_count = gui.elements.affix_settings.legendary_boots_slider:get(),
      unique_helm_ga_count = gui.elements.affix_settings.unique_helm_slider:get(),
      unique_chest_ga_count = gui.elements.affix_settings.unique_chest_slider:get(),
      unique_gloves_ga_count = gui.elements.affix_settings.unique_gloves_slider:get(),
      unique_pants_ga_count = gui.elements.affix_settings.unique_pants_slider:get(),
      unique_boots_ga_count = gui.elements.affix_settings.unique_boots_slider:get(),
      --offhand
      legendary_focus_ga_count = gui.elements.affix_settings.legendary_focus_slider:get(),
      legendary_totem_ga_count = gui.elements.affix_settings.legendary_totem_slider:get(),
      unique_focus_ga_count = gui.elements.affix_settings.unique_focus_slider:get(),
      unique_totem_ga_count = gui.elements.affix_settings.unique_totem_slider:get(),
      legendary_shield_ga_count = gui.elements.affix_settings.legendary_shield_slider:get(),
      unique_shield_ga_count = gui.elements.affix_settings.unique_shield_slider:get(),

      --Wepeons Settings
         --1h
         legendary_1h_mace_ga_count = gui.elements.affix_settings.legendary_1h_mace_slider:get(),
         legendary_1h_sword_ga_count = gui.elements.affix_settings.legendary_1h_sword_slider:get(),
         legendary_1h_axe_ga_count = gui.elements.affix_settings.legendary_1h_axe_slider:get(),
         legendary_dagger_ga_count = gui.elements.affix_settings.legendary_dagger_slider:get(),
         legendary_wand_ga_count = gui.elements.affix_settings.legendary_wand_slider:get(),
         unique_1h_mace_ga_count = gui.elements.affix_settings.unique_1h_mace_slider:get(),
         unique_1h_sword_ga_count = gui.elements.affix_settings.unique_1h_sword_slider:get(),
         unique_1h_axe_ga_count = gui.elements.affix_settings.unique_1h_axe_slider:get(),
         unique_dagger_ga_count = gui.elements.affix_settings.unique_dagger_slider:get(),
         unique_wand_ga_count = gui.elements.affix_settings.unique_wand_slider:get(),
         legendary_1h_scythe_ga_count = gui.elements.affix_settings.legendary_1h_scythe_slider:get(),
         unique_1h_scythe_ga_count = gui.elements.affix_settings.unique_1h_scythe_slider:get(),
         legendary_flail_ga_count = gui.elements.affix_settings.legendary_flail_slider:get(),
         unique_flail_ga_count = gui.elements.affix_settings.unique_flail_slider:get(),
         --2h
         legendary_2h_mace_ga_count = gui.elements.affix_settings.legendary_2h_mace_slider:get(),
         legendary_2h_sword_ga_count = gui.elements.affix_settings.legendary_2h_sword_slider:get(),
         legendary_2h_axe_ga_count = gui.elements.affix_settings.legendary_2h_axe_slider:get(),
         legendary_2h_polearm_ga_count = gui.elements.affix_settings.legendary_2h_polearm_slider:get(),
         legendary_staff_ga_count = gui.elements.affix_settings.legendary_staff_slider:get(),
         legendary_bow_ga_count = gui.elements.affix_settings.legendary_bow_slider:get(),
         legendary_crossbow_ga_count = gui.elements.affix_settings.legendary_crossbow_slider:get(),
         legendary_glaive_ga_count = gui.elements.affix_settings.legendary_glaive_slider:get(),
         legendary_quarterstaff_ga_count = gui.elements.affix_settings.legendary_quarterstaff_slider:get(),
         unique_2h_mace_ga_count = gui.elements.affix_settings.unique_2h_mace_slider:get(),
         unique_2h_sword_ga_count = gui.elements.affix_settings.unique_2h_sword_slider:get(),
         unique_2h_axe_ga_count = gui.elements.affix_settings.unique_2h_axe_slider:get(),
         unique_2h_polearm_ga_count = gui.elements.affix_settings.unique_2h_polearm_slider:get(),
         unique_staff_ga_count = gui.elements.affix_settings.unique_staff_slider:get(),
         unique_bow_ga_count = gui.elements.affix_settings.unique_bow_slider:get(),
         unique_crossbow_ga_count = gui.elements.affix_settings.unique_crossbow_slider:get(),
         unique_glaive_ga_count = gui.elements.affix_settings.unique_glaive_slider:get(),
         unique_quarterstaff_ga_count = gui.elements.affix_settings.unique_quarterstaff_slider:get(),
         legendary_2h_scythe_ga_count = gui.elements.affix_settings.legendary_2h_scythe_slider:get(),
         unique_2h_scythe_ga_count = gui.elements.affix_settings.unique_2h_scythe_slider:get(),

      
      -- Item Types
      quest_items = gui.elements.item_types.quest_items_toggle:get(),
      crafting_items = gui.elements.item_types.crafting_items_toggle:get(),
      boss_items = gui.elements.item_types.boss_items_toggle:get(),
      rare_elixirs = gui.elements.item_types.rare_elixir_items_toggle:get(),
      basic_elixirs = gui.elements.item_types.basic_elixir_items_toggle:get(),
      advanced_elixirs = gui.elements.item_types.advanced_elixir_items_toggle:get(),
      other_consumables = gui.elements.item_types.other_consumable_items_toggle:get(),
      sigils = gui.elements.item_types.sigil_items_toggle:get(),
      compass = gui.elements.item_types.compass_items_toggle:get(),
      rune = gui.elements.item_types.rune_items_toggle:get(),
      cinders = gui.elements.item_types.cinders_toggle:get(),
      tribute = gui.elements.item_types.tribute_items_toggle:get(),
      scroll = gui.elements.item_types.scroll_items_toggle:get(),
      event_items = gui.elements.item_types.event_items_toggle:get(),
      heavenly_sigil = gui.elements.item_types.heavenly_sigil_toggle:get(),
      charm = gui.elements.item_types.charm_items_toggle:get(),
      seal = gui.elements.item_types.seal_items_toggle:get(),
      splinter = gui.elements.item_types.splinter_items_toggle:get(),
      lair_key = gui.elements.item_types.lair_key_items_toggle:get(),
      gemstone = gui.elements.item_types.gemstone_items_toggle:get(),
      fish = gui.elements.item_types.fish_items_toggle:get(),
      cache = gui.elements.item_types.cache_items_toggle:get(),

      -- Debug
      draw_wanted_items = gui.elements.debug.draw_wanted_toggle:get()
   }
   for key,value in pairs(next_settings) do settings[key]=value end
   if not settings.enabled then settings.looting=false end
end

function Settings.is_paused() return paused or next(pause_owners)~=nil end
function Settings.acquire_pause(caller)
   if type(caller)~='string' or caller=='' then return false end
   pause_owners[caller]=true; settings.looting=false; return true
end
function Settings.release_pause(caller)
   if type(caller)~='string' or caller=='' then return false end
   pause_owners[caller]=nil; return true
end
function Settings.pause_state()
   local owners={}; for caller in pairs(pause_owners) do owners[caller]=true end
   return {paused=paused,owners=owners}
end
function Settings.restore_pause_state(state)
   if type(state)~='table' then return end
   paused=state.paused==true
   if type(state.owners)=='table' then
      for caller in pairs(state.owners) do
         if type(caller)=='string' and caller~='' then pause_owners[caller]=true end
      end
   end
end

function Settings.set(key,value)
   if type(value)~='boolean' then return false end
   if key=='looting' then
      -- Rosie's existing protocol: false pauses; true releases the pause.
      -- Active pickup is an observation, never forced true by a town callback.
      paused=not value
      settings.looting=false
      return true
   end
   local elements=gui.elements
   local map={enabled=elements.main_toggle,custom_toggle=elements.affix_settings.custom_toggle,
      skip_dropped=elements.general.skip_dropped_toggle,respect_filter=elements.general.respect_filter_toggle,
      draw_wanted_items=elements.debug.draw_wanted_toggle}
   local aliases={quest_items='quest_items',crafting_items='crafting_items',boss_items='boss_items',
      rare_elixirs='rare_elixir_items',basic_elixirs='basic_elixir_items',advanced_elixirs='advanced_elixir_items',other_consumables='other_consumable_items',
      sigils='sigil_items',compass='compass_items',rune='rune_items',tribute='tribute_items',scroll='scroll_items',
      event_items='event_items',cinders='cinders',heavenly_sigil='heavenly_sigil',charm='charm_items',
      seal='seal_items',splinter='splinter_items',lair_key='lair_key_items',gemstone='gemstone_items',
      fish='fish_items',cache='cache_items'}
   local element=map[key] or aliases[key] and elements.item_types[aliases[key]..'_toggle']
   if not element then return false end
   element:set(value)
   Settings.update()
   return true
end

function Settings.get()
   return settings
end

function Settings.should_execute()
   return settings.behavior == 0 or
       (settings.behavior == 1 and orbwalker.get_orb_mode() == orb_mode.clear)
end

return Settings
