-- Generated by tools/build-rosie.mjs; edit the reviewed source or transform.
local gui_options = {
    rarities = {
        "Common",
        "Magic",
        "Magic (variant 2)",
        "Rare",
        "Rare (variant 2)",
        "Legendary",
        "Unique or higher",
    },
    behaviors = {
        "Always",
        "Orbwalk"
    }
}

return gui_options
