-- Generated by tools/build-rosie.mjs; edit the reviewed source or transform.
local gui          = require 'rosie.private.town.gui'
local settings     = require 'rosie.private.town.core.settings'
local task_manager = require 'rosie.private.town.core.task_manager'
local tracker      = require 'rosie.private.town.core.tracker'
local lifecycle    = require 'rosie.private.town.core.lifecycle'

-- QQT_Warpigz_v3 (Q10, live: host crash while hovering a bag item with the
-- menu open): the overlay no longer reads every item's slot from the host on
-- every frame. A census entry reads its row/column at most every
-- SLOT_MAX_AGE s, and the six layout sliders are read once per frame.
-- QQT_Warpigz_v3 (review): the cached slot ages out on its own. With the town
-- service off (pickup only) and the menu closed no census runs, and a slot
-- cached until the next census kept the box on the old slot after the user
-- moved the item.
local SLOT_MAX_AGE = 0.5
local function slot_of(cache)
    local now = get_time_since_inject()
    if cache.slot_row ~= nil and (cache.slot_at == nil or now - cache.slot_at > SLOT_MAX_AGE or now < cache.slot_at) then
        cache.slot_row = nil
    end
    if cache.slot_row == nil then
        cache.slot_at = now
        local item=cache.item
        local ok,row,col=pcall(function() return item:get_inventory_row(),item:get_inventory_column() end)
        if not ok or type(row)~='number' or type(col)~='number' or row~=row or col~=col
            or row<0 or col<0 or row==math.huge or col==math.huge then
            cache.slot_row=false
        else
            cache.slot_row,cache.slot_col=row,col
        end
    end
    if not cache.slot_row then return nil end
    return cache.slot_row,cache.slot_col
end
local function get_affix_screen_position(cache, layout)
    local row,col=slot_of(cache)
    if not row then return nil end
    local x = layout.origin_x + col * layout.slot_w
    local y = layout.origin_y + row * layout.slot_h

    return x, y, layout.box_width, layout.box_height
end

local FONT        = 14
local FONT_HDR    = 17
local LINE_H      = 18
local HDR_H       = 26
local PAD_X       = 10
local PAD_Y       = 6

local COL_BG      = color.new(5, 5, 5, 5)
local COL_BORDER  = color.new(255, 130, 0, 230)
local COL_DIVIDER = color.new(255, 140, 0, 100)
local COL_HEADER  = color_orange(255)
local COL_TEXT    = color_white(255)
local COL_DIM     = color_white(140)
local COL_GREEN   = color_green(255)
local COL_ORANGE  = color_orange(255)
local COL_RED     = color_red(255)

local function status_color(s)
    local sl = string.lower(s)
    if sl:match('fail') or sl:match('stuck') then return COL_RED end
    if sl:match('retry') or sl:match('re%-try') or sl:match('reset') then return COL_ORANGE end
    if sl:match('wait') then return COL_ORANGE end
    if sl:match('paused') then return COL_DIM end
    if sl:match('idle') or sl:match('done') then return COL_GREEN end
    return COL_GREEN
end

local drawing = {}

function drawing.draw_status()
    local current_task = task_manager.get_current_task()
    local status = lifecycle.status_text()
    if lifecycle.busy() and not tracker.external_pause and not tracker.failure_reason
        and status:find('Servicing',1,true)==1 and current_task then
        status=status..' - '..tostring(current_task.status)
    end

    local max = settings.max_stash_items or 350
    local stash_text, stash_col
    if tracker.stash_item_count_cached then
        local pct = tracker.stash_item_count_cached / max * 100
        stash_text = string.format('Stash     : %d/%d (%.0f%%)', tracker.stash_item_count_cached, max, pct)
        stash_col  = pct >= 90 and COL_RED or pct >= 70 and COL_ORANGE or COL_TEXT
    else
        stash_text = 'Stash     : --/-- (open stash to scan)'
        stash_col  = COL_DIM
    end

    local lines = {
        { text = 'Status    : ' .. status,                      col = status_color(status), bold = true },
        { text = 'Inventory : ' .. tracker.inventory_count,     col = COL_TEXT },
        { text = stash_text,                                     col = stash_col },
        { text = 'Keep      : ' .. tracker.stash_count,         col = COL_TEXT },
        { text = 'Salvage   : ' .. tracker.salvage_count,       col = COL_TEXT },
        { text = 'Sell      : ' .. tracker.sell_count,          col = COL_TEXT },
        { text = 'Tal Keep  : ' .. tracker.stash_talisman_count,    col = COL_TEXT },
        { text = 'Tal Salvage: ' .. tracker.salvage_talisman_count, col = COL_TEXT },
    }

    local max_w = #'Rosie' * FONT_HDR * 0.55
    for _, l in ipairs(lines) do
        local w = #l.text * FONT * 0.55
        if w > max_w then max_w = w end
    end

    local panel_w = max_w + PAD_X * 2
    local panel_h = HDR_H + #lines * LINE_H + PAD_Y * 2
    local x = 8 + gui.elements.draw_status_offset_x:get()
    local y = 50 + gui.elements.draw_status_offset_y:get()

    graphics.rect_filled(vec2:new(x, y), vec2:new(x + panel_w, y + panel_h), COL_BG)
    graphics.rect(vec2:new(x, y), vec2:new(x + panel_w, y + panel_h), COL_BORDER, 1, 3)
    graphics.text_2d('Rosie', vec2:new(x + PAD_X + 2, y + PAD_Y), FONT_HDR, COL_HEADER)
    graphics.text_2d('Rosie', vec2:new(x + PAD_X + 1, y + PAD_Y), FONT_HDR, COL_HEADER)
    graphics.text_2d('Rosie', vec2:new(x + PAD_X,     y + PAD_Y), FONT_HDR, COL_HEADER)
    graphics.line(vec2:new(x + 4, y + HDR_H), vec2:new(x + panel_w - 4, y + HDR_H), COL_DIVIDER, 1)

    local ty = y + HDR_H + PAD_Y
    for _, l in ipairs(lines) do
        if l.bold then
            graphics.text_2d(l.text, vec2:new(x + PAD_X + 1, ty), FONT, l.col)
        end
        graphics.text_2d(l.text, vec2:new(x + PAD_X, ty), FONT, l.col)
        ty = ty + LINE_H
    end
end


function drawing.draw_inventory_boxes()
    if not is_inventory_open() then return end
    local items = tracker.cached_inventory
    if type(items)~='table' or next(items)==nil then return end
    local e=gui.elements -- QQT_Warpigz_v3 (Q10): widgets read once per frame
    local layout={origin_x=e.draw_inventory_origin_x:get(),origin_y=e.draw_inventory_origin_y:get(),
        slot_w=e.draw_offset_x:get(),slot_h=e.draw_offset_y:get(),
        box_width=e.draw_box_width:get(),box_height=e.draw_box_height:get()}
    local draw_stash,draw_sell,draw_salvage=e.draw_stash:get(),e.draw_sell:get(),e.draw_salvage:get()
    for _,cache in pairs(items) do
        local x, y, box_width, box_height
        if (draw_stash and cache.is_stash) or (draw_sell and cache.is_sell) or (draw_salvage and cache.is_salvage) then
            x, y, box_width, box_height = get_affix_screen_position(cache, layout)
        end
        local draw_affix = false
        if x and draw_stash and cache.is_stash then
            graphics.rect(vec2:new(x, y), vec2:new(x + box_width, y + box_height), color_blue(255), 1, 4)
            draw_affix = true
        elseif x and draw_sell and cache.is_sell then
            graphics.rect(vec2:new(x, y), vec2:new(x + box_width, y + box_height), color_pink(255), 1, 3)
            draw_affix = true
        elseif x and draw_salvage and cache.is_salvage then
            graphics.rect(vec2:new(x, y), vec2:new(x + box_width, y + box_height), color_orange_red(255), 1, 3)
            draw_affix = true
        end
        if draw_affix then
            if cache.is_max_aspect and cache.affix_count > 0 then
                graphics.text_2d(tostring(cache.affix_count) .. "*", vec2:new(x + box_width - 24, y + box_height - 25), 20, color_white(255))
            elseif cache.is_max_aspect then
                graphics.text_2d("*", vec2:new(x + box_width - 15, y + box_height - 25), 20, color_white(255))
            elseif cache.affix_count > 0 then
                graphics.text_2d(tostring(cache.affix_count), vec2:new(x + box_width - 15, y + box_height - 25), 20, color_white(255))
            end
        end
        
    end

end


return drawing
