-- Generated by tools/build-rosie.mjs; edit the reviewed source or transform.
local pathfinder=require('rosie.movement').for_owner('town')
-- Town tasks own their target. No autonomous exploration, revival or host mutation.
local tracker=require 'rosie.private.town.core.tracker'
local settings=require 'rosie.private.town.core.settings'
local utils=require 'rosie.private.town.core.utils'
local M={}
local target=nil
function M:set_custom_target(position) target=position end
function M:move_to_target()
    local player=get_local_player()
    if not target or not player or player:is_dead() or not settings.enabled
        or tracker.external_pause or not tracker.trigger_tasks or not utils.is_in_town() then return false end
    return pathfinder.request_move(target)
end
function M:clear_path_and_target() target=nil end
function M:reset_exploration() target=nil end
return M
