-- Generated by tools/build-rosie.mjs; edit the reviewed source or transform.
local task_manager = {}
local tasks = {}
local current_task = { name = 'Idle', status = 'Idle' } -- Default state when no task is active
local finished_time = 0
local lifecycle = require 'rosie.private.town.core.lifecycle'
local tracker = require 'rosie.private.town.core.tracker'
local generation=nil

function task_manager.set_finished_time(time)
    finished_time = time
end
function task_manager.get_finished_time()
    return finished_time
end
function task_manager.register_task(task)
    table.insert(tasks, task)
end

local last_call_time = 0.0
function task_manager.suspend()
    for _,task in ipairs(tasks) do if task.suspend then task.suspend() end end
end
function task_manager.execute_tasks()
    if not lifecycle.tick() then
        task_manager.suspend()
        return
    end
    if generation~=tracker.request_id then
        generation=tracker.request_id
        for _,task in ipairs(tasks) do if task.reset_session then task.reset_session() end end
    end
    local current_core_time = get_time_since_inject()
    if current_core_time - last_call_time < 0.05 then
        return -- quick ej slide frames
    end
    last_call_time = current_core_time

    current_task = { name = 'Idle', status = 'Idle' }
    for _, task in ipairs(tasks) do
        if task.shouldExecute() then
            current_task = task
            task:Execute()
            break -- Execute only one task per pulse
        end
    end

    -- The if statement has been removed, and current_task is always assigned
    current_task = current_task or { name = 'Idle', status = 'Idle' }
end

function task_manager.get_current_task()
    return current_task
end

local task_files = {'status', 'sell', 'salvage', 'repair', 'salvage_talisman', 'stash', 'stash_pull', 'teleport'}
for _, file in ipairs(task_files) do
    local task = require('rosie.private.town.tasks.' .. file)
    task_manager.register_task(task)
end

return task_manager
