-- Generated by tools/build-rosie.mjs; edit the reviewed source or transform.
local pathfinder=require('rosie.movement').for_owner('town')
local BatmobilePlugin=nil -- Rosie owns native movement.
-- Shared town navigation observations; never retain mutable host vectors.
local utils=require 'rosie.private.town.core.utils'
local M={}
function M.snapshot(position)
    local ok,x,y,z=pcall(function() return position:x(),position:y(),position:z() end)
    if not ok then return nil end
    for _,v in ipairs({x,y,z}) do
        if type(v)~='number' or v~=v or math.abs(v)==math.huge then return nil end
    end
    if x==nil or y==nil or z==nil then return nil end
    return {x=x,y=y,z=z}
end
function M.progressed(before,now)
    if not before or not now then return false end
    return (before.x-now.x)^2+(before.y-now.y)^2+(before.z-now.z)^2>=0.16
end
function M.target(key)
    local actor=utils.get_npc(utils.npc_enum[key])
    local ok,position=pcall(function() return actor and actor:get_position() or utils.get_npc_location(key) end)
    local point=ok and M.snapshot(position)
    if not point then return nil end
    return utils.compute_move_target(vec3:new(point.x,point.y,point.z))
end
function M.stop()
    local ok,result=pcall(function()
        if BatmobilePlugin then return BatmobilePlugin.clear_target('alfred_the_butler') end
        return pathfinder.clear_stored_path()
    end)
    return ok and result~=false
end
return M
