-- Generated by tools/build-rosie.mjs; edit the reviewed source or transform.
local json = require 'rosie.private.town.core.json'
local tracker = require 'rosie.private.town.core.tracker'
local town = require 'rosie.private.town.core.town'
local catalog_ok, catalog = pcall(require, 'rosie.data.items')
local current_items = catalog_ok and type(catalog)=='table' and type(catalog.by_id)=='table' and catalog.by_id or {}

local utils    = {
    settings = {},
    last_dump_time = 0,
}

function utils.vendor_action(action,item)
    local ok,open=pcall(function() return loot_manager:is_in_vendor_screen() end)
    if not ok or open~=true then return false end
    if item~=nil then return action(item) end
    return action()
end

function utils.get_town()
    return town.get(utils.settings.town_choice)
end
function utils.is_in_town()
    local world=get_current_world()
    return world~=nil and world:get_current_zone_name() == utils.get_town().zone_name
end
local affix_slot_names = {
    'helm', 'chest', 'gloves', 'pants', 'boots',
    'amulet', 'ring', 'offhand',
    'weapon_1h', 'weapon_2h',
    'talisman_seal', 'talisman_charm',
}
local aspect_slot_names = {
    'weapon', 'helm', 'chest', 'gloves', 'pants', 'boots',
    'amulet', 'ring', 'offhand',
    'talisman_seal', 'talisman_charm',
}
local item_affix = {}
local item_aspect = {}
local item_unique = {}
local item_unique_charm = {}
local item_set_charm = {}
local legacy_unique_items = {}
local item_mythic = {}
local item_special_seal = {}
-- npc_enum / npc_loc_enum / npc_via_loc_enum / walls are sourced from the
-- active town config (see core/town.lua). __index delegates per-key reads to
-- whichever town is selected so existing call sites like
-- `utils.npc_enum['GAMBLER']` keep working without changes.
utils.npc_enum = setmetatable({}, {
    __index = function(_, key) return utils.get_town().npc_enum[key] end,
})
utils.npc_loc_enum = setmetatable({}, {
    __index = function(_, key) return utils.get_town().npc_loc_enum[key] end,
})
utils.npc_via_loc_enum = setmetatable({}, {
    __index = function(_, key) return utils.get_town().npc_via_loc_enum[key] end,
})
-- Subzones where a wall forces routing through a middleman waypoinhow to checkt.
-- Player must pass through `via` to enter or leave the area within `radius` of `inside_anchor`.
function utils.get_walls()
    return utils.get_town().walls or {}
end
utils.item_enum = {
    KEEP = 0,
    SALVAGE = 1,
    SELL = 2
}
utils.stash_extra_enum = {
    NEVER = 0,
    FULL = 1,
    ALWAYS = 2
}
utils.failed_action_enum = {
    LOG = 0,
    RETRY = 1
}
local function rarity_conflicts_with_catalog(meta,rarity,legacy_mythic)
    if meta and meta.quality=='set' and rarity~=7 and rarity<8 then return true end
    if not meta or (meta.quality~='unique' and meta.quality~='mythic') then return false end
    if rarity~=6 and rarity<8 then return true end
    return meta.quality=='mythic' and rarity<8 and not legacy_mythic
end
-- Every destructive path, including sigils and explicit pulls, must observe a
-- live wrapper and an affirmative unlocked flag before issuing a host command.
function utils.can_modify_item(item)
    local ok,valid,locked,id=pcall(function()
        return item:is_valid(),item:is_locked(),item:get_sno_id()
    end)
    return ok and valid==true and locked==false and type(id)=='number'
        and id>0 and id<math.huge and id==math.floor(id)
end
local function valid_rarity(value)
    return type(value)=='number' and value>=0 and value<math.huge and value==math.floor(value)
end
-- QQT_Warpigz_v2 local patch (H3): unique (6) and mythic (8+) charms and
-- seals never take the plain in-game-filter action; they always follow the
-- unique/mythic selection rules below, and "Always keep mythics" (default on,
-- the old WarPigz Alfred key) keeps every mythic one.
local function protected_talisman(item)
    local item_type = utils.get_item_type(item)
    if item_type ~= 'talisman_seal' and item_type ~= 'talisman_charm' then return false, false end
    local ok, r = pcall(function() return item:get_rarity() end)
    if not ok or not valid_rarity(r) then return true, true end -- unreadable: keep
    local okm, mythic_seal = pcall(function() return item_type == 'talisman_seal' and utils.is_mythic_seal(item) end)
    local mythic = r >= 8 or (okm and mythic_seal == true)
    return r == 6 or mythic, mythic
end
local function talisman_should_act(item, requested_action)
    if not utils.can_modify_item(item) then return false end
    local s = utils.settings
    local protected, mythic = protected_talisman(item)
    if mythic and s.mythic_always_keep ~= false then return false end

    if s.loot_filter_mode and not protected then
        local ok, filtered = pcall(function() return item:is_filtered_by_loot_filter() end)
        if ok then
            if filtered~=true then return false end
            local item_type = utils.get_item_type(item)
            if item_type == 'talisman_seal' then
                return s.talisman_seal_action == requested_action
            elseif item_type == 'talisman_charm' then
                return s.talisman_charm_action == requested_action
            end
            return false
        end
        return false -- unreadable native filter must keep the item
    end

    local item_type_early = utils.get_item_type(item)
    local lf_active = not protected and ((item_type_early == 'talisman_seal' and s.loot_filter_seal)
                   or (item_type_early == 'talisman_charm' and s.loot_filter_charm))
    if lf_active then
        local ok, filtered = pcall(function() return item:is_filtered_by_loot_filter() end)
        if ok then
            if filtered~=true then return false end
            if item_type_early == 'talisman_seal' then
                return s.talisman_seal_action == requested_action
            elseif item_type_early == 'talisman_charm' then
                return s.talisman_charm_action == requested_action
            end
            return false
        end
        return false -- unreadable category filter must keep the item
    end

    local item_type = utils.get_item_type(item)
    local ok, r = pcall(function() return item:get_rarity() end)
    if not ok or not valid_rarity(r) then return false end
    local rarity = r
    local meta=current_items[item:get_sno_id()]
    if rarity_conflicts_with_catalog(meta,rarity,utils.mythic_seals[item:get_sno_id()]~=nil) then
        return false -- conflicting metadata must not authorize a destructive default
    end

    local action, affix_filter, affix_count, affix_selected
    if item_type == 'talisman_seal' then
        -- Unique and mythic seals share the saved seal selection controls.
        if rarity==6 or utils.is_mythic_seal(item) then
            if s.talisman_seal_mythic_filter then
                if utils.is_correct_mythic_seal(item) then return false end
            else
                return false
            end
        end
        action         = s.talisman_seal_action
        affix_filter   = s.talisman_seal_affix_filter
        affix_count    = s.talisman_seal_affix_count
        affix_selected = s.talisman_seal_affix
    elseif item_type == 'talisman_charm' then
        -- Unique and mythic charms: keep always, or apply the named selection.
        if rarity == 6 or rarity >= 8 then
            if s.talisman_charm_unique_filter then
                if utils.is_correct_unique_charm(item) then return false end
            else
                return false
            end
        end
        -- Set charm (rarity 7): set filter gates which ones to keep; filter off = default action
        if rarity == 7 then
            if s.talisman_charm_set_filter then
                if not utils.is_correct_set_charm(item) then
                    return s.talisman_charm_action == requested_action
                end
                if not s.talisman_charm_affix_filter then return false end
                -- in set list: affix filter applies below (AND logic — fall through)
            end
            -- set filter off: fall through to default action
        end
        action         = s.talisman_charm_action
        affix_filter   = s.talisman_charm_affix_filter
        affix_count    = s.talisman_charm_affix_count
        affix_selected = s.talisman_charm_affix
    else
        return false
    end
    -- Affix filter: keep if matched >= count
    if affix_filter and affix_selected then
        local matched = 0
        for _, affix in pairs(item:get_affixes()) do
            if affix_selected[affix.affix_name_hash] then matched = matched + 1 end
        end
        if matched >= (affix_count or 1) then return false end
    end
    return action == requested_action
end

-- QQT_Warpigz_v2 (M2): a host error reading one item keeps that item; it
-- never escapes into the census, a task or the service pulse.
local function safe_talisman_should_act(item, requested_action)
    local ok, result = pcall(talisman_should_act, item, requested_action)
    return ok and result == true
end
function utils.should_salvage_talisman(item)
    return safe_talisman_should_act(item, utils.item_enum['SALVAGE'])
end

function utils.should_sell_talisman(item)
    return safe_talisman_should_act(item, utils.item_enum['SELL'])
end

utils.mythics = {
    [1901484] = "Tyrael's Might",
    [223271] = 'The Grandfather',
    [241930] = "Andariel's Visage",
    [359165] = 'Ahavarion, Spear of Lycander',
    [221017] = 'Doombringer',
    [609820] = 'Harlequin Crest',
    [1275935] = 'Melted Heart of Selig',
    [1306338] = 'Ring of Starless Skies',
    [2059803] = 'Shroud of False Death',
    [1982241] = 'Nesekem, the Herald',
    [2059799] = 'Heir of Perdition',
    [2059813] = 'Shattered Vow',
    [2603733] = "El'Druin, Sword of Justice",
}

utils.mythic_seals = {
    [2609259] = 'Mythic Unique Horadric Seal',
    [2622265] = 'Seal of the Severed Finger',
    [2622267] = 'Seal of the Golden Epiphany',
    [2622269] = 'Seal of the Diamond Mind',
}

local function get_plugin_root_path()
    local plugin_root = string.gmatch(package.path, '.*?\\?')()
    plugin_root = plugin_root:gsub('?','')
    return plugin_root
end
-- QQT_Warpigz_v2 (L2): a missing or corrupt data file is logged and skipped;
-- it never aborts Rosie's load.
local function decode_json(raw,filename)
    local ok,data=pcall(json.decode,raw)
    if ok and type(data)=='table' then return data end
    utils.log('error decoding file ' .. tostring(filename))
    return nil
end
local function normalize_class(c)
    return (not c or #c == 0) and {'all'} or c
end

local function load_affix_slot(slot_name)
    local filename = get_plugin_root_path() .. 'data\\affix\\affix_' .. slot_name .. '.json'
    local file = io.open(filename, 'r')
    if not file then utils.log('error opening file ' .. filename); return end
    local raw = file:read('*all')
    io.close(file)
    raw = raw:match('[%[%{].*') or raw
    local data = decode_json(raw, filename)
    if not data then return end
    local group = { name = slot_name, data = {} }
    for _, affix in pairs(data) do
        affix.sno_id      = affix.sno_id or affix.id
        affix.class       = normalize_class(affix.class)
        affix.description = affix.description or affix.name or ''
        group.data[#group.data+1] = affix
    end
    item_affix[#item_affix+1] = group
end

local function load_aspect_slot(slot_name)
    local filename = get_plugin_root_path() .. 'data\\affix\\aspect_' .. slot_name .. '.json'
    local file = io.open(filename, 'r')
    if not file then utils.log('error opening file ' .. filename); return end
    local raw = file:read('*all')
    io.close(file)
    raw = raw:match('[%[%{].*') or raw
    local data = decode_json(raw, filename)
    if not data then return end
    for _, affix in pairs(data) do
        affix.sno_id      = affix.sno_id or affix.id
        affix.class       = normalize_class(affix.class)
        affix.description = affix.description or affix.name or ''
        if not item_aspect[affix.sno_id] then
            item_aspect[affix.sno_id] = affix
        end
    end
end
local function load_unique_file(filename)
    local file, err = io.open(filename,'r')
    if not file then
        utils.log('error opening file' .. filename)
        return
    end
    local raw = file:read('*all')
    io.close(file)
    raw = raw:match('[%[%{].*') or raw
    local data = decode_json(raw, filename)
    if not data then return end
    for _,item in pairs(data) do
        local classes = item.playerClassNames or item.class or {}
        if #classes == 0 then classes = { 'all' } end
        local entry = {
            sno_id      = item.id or item.sno_id,
            name        = item.name,
            description = item.name,
            item_type   = item.itemTypeName or item.item_type or '',
            class       = classes,
        }
        local t = entry.item_type
        if t == 'Charm' then
            item_unique_charm[#item_unique_charm+1] = entry
        else
            item_unique[#item_unique+1] = entry
        end
    end
end
local function load_set_charm_file(filename)
    local file = io.open(filename, 'r')
    if not file then utils.log('error opening file' .. filename); return end
    local raw = file:read('*all')
    io.close(file)
    raw = raw:match('[%[%{].*') or raw
    local data = decode_json(raw, filename)
    if not data then return end
    for _, item in pairs(data) do
        local classes = item.class or {}
        if #classes == 0 then classes = { 'all' } end
        item_set_charm[#item_set_charm+1] = {
            sno_id      = item.sno_id,
            name        = item.name,
            description = item.name,
            item_type   = 'Charm',
            set         = item.set or '',
            class       = classes,
        }
    end
end
local function get_uniques()
    local root = get_plugin_root_path()
    load_unique_file(root .. 'data\\affix\\unique-item.json')
    load_unique_file(root .. 'data\\affix\\unique-charm.json')
    load_set_charm_file(root .. 'data\\affix\\set-charm.json')
end
local equipment_types = {
    Axe=true,Dagger=true,Flail=true,FocusBookOffHand=true,Focus=true,Mace=true,Scythe=true,
    Shield=true,Sword=true,OffHandTotem=true,Wand=true,Axe2H=true,Bow=true,Crossbow2H=true,
    Mace2H=true,Polearm=true,Scythe2H=true,Staff=true,Sword2H=true,Amulet=true,Boots=true,
    ChestArmor=true,Glaive=true,Gloves=true,Helm=true,Legs=true,Quarterstaff=true,Ring=true,
}
local catalog_slots = {
    helm='helm',chest='chest',gloves='gloves',pants='pants',boots='boots',amulet='amulet',ring='ring',
    focus='offhand',totem='offhand',shield='offhand',dagger='weapon_1h',wand='weapon_1h',flail='weapon_1h',
    ['1h_mace']='weapon_1h',['1h_sword']='weapon_1h',['1h_axe']='weapon_1h',['1h_scythe']='weapon_1h',
    ['2h_mace']='weapon_2h',['2h_sword']='weapon_2h',['2h_axe']='weapon_2h',['2h_scythe']='weapon_2h',
    ['2h_polearm']='weapon_2h',staff='weapon_2h',bow='weapon_2h',crossbow='weapon_2h',
    glaive='weapon_2h',quarterstaff='weapon_2h',
}
local function named_item(name)
    return type(name)=='string' and name~='' and name:lower()~='ph'
        and not name:lower():find('[ph',1,true) and not name:lower():find('placeholder',1,true)
end
local function build_picker_catalog()
    -- Keep legacy source IDs available for saved widgets even when their rows
    -- belong in another picker, or are not equipment at all.
    legacy_unique_items=item_unique
    local groups={unique={},mythic={},charm={},set={},seal={}}
    local function add(row,kind,quality)
        local id=row.sno_id
        local meta=current_items[id] or {}
        kind=meta.kind or kind
        quality=meta.quality or quality
        if kind=='equipment' and not (catalog_slots[meta.slot] or equipment_types[row.item_type] or utils.mythics[id]) then return end
        if kind=='equipment' and utils.mythics[id] then quality='mythic' end
        local group=kind=='equipment' and (quality=='unique' or quality=='mythic') and quality
            or kind=='charm' and (quality=='unique' or quality=='mythic') and 'charm'
            or kind=='charm' and quality=='set' and 'set'
            or kind=='seal' and (quality=='unique' or quality=='mythic') and 'seal'
        if not group then return end
        local name=named_item(meta.name) and meta.name or row.name
        if not named_item(name) then return end
        local previous=groups[group][id]
        local classes=meta.classes or row.class or previous and previous.class
        if type(classes)~='table' or #classes==0 then classes={'all'} end
        local item_type=kind=='charm' and 'Charm' or kind=='seal' and 'Seal'
            or meta.slot or row.item_type or 'Equipment'
        groups[group][id]={sno_id=id,name=name,description=name,item_type=item_type,class=classes,
            set=row.set or previous and previous.set or '',quality=quality}
    end
    for _,row in ipairs(legacy_unique_items) do
        add(row,equipment_types[row.item_type] and 'equipment' or 'other','unique')
    end
    for id,name in pairs(utils.mythics) do add({sno_id=id,name=name,class={'all'}},'equipment','mythic') end
    for _,row in ipairs(item_unique_charm) do add(row,'charm','unique') end
    for _,row in ipairs(item_set_charm) do add(row,'charm','set') end
    for id,name in pairs(utils.mythic_seals) do add({sno_id=id,name=name,class={'all'}},'seal','mythic') end
    for id,meta in pairs(current_items) do
        -- Internal assets without a real localized name do not become new picks.
        if named_item(meta.name) and (meta.quality=='unique' or meta.quality=='mythic' or meta.quality=='set') then
            add({sno_id=id,name=meta.name,class=meta.classes},meta.kind,meta.quality)
        end
    end
    local function list(group)
        local result={}
        for _,row in pairs(groups[group]) do result[#result+1]=row end
        table.sort(result,function(a,b)
            if a.name==b.name then return a.sno_id<b.sno_id end
            return a.name<b.name
        end)
        return result
    end
    item_unique,item_mythic=list('unique'),list('mythic')
    item_unique_charm,item_set_charm,item_special_seal=list('charm'),list('set'),list('seal')
end
function utils.get_item_affixes()
    return item_affix
end
function utils.get_item_aspects()
    return item_aspect
end
function utils.get_unique_items()
    return item_unique
end
function utils.get_legacy_unique_items()
    return legacy_unique_items
end
function utils.get_unique_charm_items()
    return item_unique_charm
end
function utils.get_set_charm_items()
    return item_set_charm
end
function utils.get_mythic_seal_items()
    -- Public helper name and widget IDs retained for existing saved selections.
    return item_special_seal
end
function utils.get_mythic_items()
    return item_mythic
end
function utils.log(msg)
    -- console.print(utils.settings.plugin_label .. ': ' .. tostring(msg))
end

function utils.get_character_class()
    local local_player = get_local_player();
    if not local_player then return 'default' end
    local class_id = local_player:get_character_class_id()
    local character_classes = {
        [0] = 'sorcerer',
        [1] = 'barbarian',
        [3] = 'rogue',
        [5] = 'druid',
        [6] = 'necromancer',
        [7] = 'spiritborn',
        [9] = 'paladin',
        [10] = 'warlock',
    }
    if character_classes[class_id] then
        return character_classes[class_id]
    else
        return 'default'
    end
end

function utils.player_in_zone(zname)
    local world=get_current_world()
    return world~=nil and world:get_current_zone_name() == zname
end
function utils.reset_all_task()
    local previous = {}
    for key,data in pairs(tracker) do
        if key ~= 'previous' then
            previous[key] = data
        end
    end
    tracker.previous = previous
    tracker.last_reset = 0
    tracker.teleport = false
    tracker.teleport_done = false
    tracker.teleport_failed = false
    tracker.sell_failed = false
    tracker.sell_done = false
    tracker.salvage_failed = false
    tracker.salvage_done = false
    tracker.salvage_talisman_failed = false
    tracker.salvage_talisman_done = false
    tracker.repair_failed = false
    tracker.repair_done = false
    tracker.stash_failed = false
    tracker.stash_done = false
    tracker.stash_full = false
    tracker.stash_pull_done = false
    tracker.stash_pull_failed = false
    tracker.all_task_done = false
    tracker.need_trigger = false
    tracker.inventory_full = false
    tracker.stash_socketables     = false
    tracker.stash_keys            = false
    tracker.stash_sigils          = false
    tracker.salvage_sigils        = false
    tracker.stash_boss_materials  = false
    tracker.stash_talisman_seal    = false
    tracker.stash_talisman_charm   = false
    tracker.salvage_talisman_seal  = false
    tracker.salvage_talisman_charm = false
    tracker.talisman_inventory_full    = false
    tracker.stash_talisman_count       = 0
    tracker.salvage_talisman_count     = 0
    tracker.trigger_tasks = false
    tracker.failure_reason=nil
end
function utils.get_npc(name)
    local actors = actors_manager:get_all_actors()
    for _, actor in pairs(actors) do
        if actor:get_skin_name() == name then return actor end
    end
    -- fallback: interactable objects (stash etc.) may not be in actors_manager
    for _, actor in pairs(get_actors_list()) do
        if actor:get_skin_name() == name then return actor end
    end
    return nil
end
function utils.get_npc_location(name)
    return utils.npc_loc_enum[name]
end
function utils.distance_to(target)
    local player_pos = get_player_position()
    local target_pos

    if target.get_position then
        target_pos = target:get_position()
    elseif target.x then
        target_pos = target
    end

    return player_pos:dist_to(target_pos)
end
function utils.is_same_position(pos1, pos2)
    return pos1:x() == pos2:x() and pos1:y() == pos2:y() and pos1:z() == pos2:z()
end

local move_state = { last_target_key = nil, via_passed = false }
function utils.compute_move_target(target_pos)
    if not target_pos then return target_pos end
    local player_pos = get_player_position()
    if not player_pos then return target_pos end

    local target_key = string.format('%.4f,%.4f,%.4f', target_pos:x(), target_pos:y(), target_pos:z())
    if move_state.last_target_key ~= target_key then
        move_state.last_target_key = target_key
        move_state.via_passed = false
    end

    for _, wall in ipairs(utils.get_walls()) do
        local player_inside = player_pos:dist_to(wall.inside_anchor) < wall.radius
        local target_inside = target_pos:dist_to(wall.inside_anchor) < wall.radius
        if player_inside ~= target_inside then
            if move_state.via_passed then
                return target_pos
            end
            if player_pos:dist_to(wall.via) < 2.5 then
                move_state.via_passed = true
                return target_pos
            end
            return wall.via
        end
    end

    return target_pos
end

function utils.get_greater_affix_count(display_name)
    if type(display_name)~='string' then return 0 end
    local count = 0
    for _ in display_name:gmatch('GreaterAffix') do
       count = count + 1
    end
    return count
end
function utils.get_item_ga_count(item)
    local ok,value=pcall(function() return item:get_attribute('Item_Greater_Affix_Count') end)
    local native_readable=ok and type(value)=='number' and value>=0 and value<100
    local native=native_readable and math.floor(value) or 0
    local display_ok,display=pcall(function() return item:get_display_name() end)
    local display_readable=display_ok and type(display)=='string'
    local marked=display_readable and utils.get_greater_affix_count(display) or 0
    -- Positive host-rendered GA markers must not be erased by a zero attribute.
    -- Ancestral status alone never invents a greater affix.
    return math.max(native,marked),native_readable or display_readable
end
function utils.is_max_aspect(affix)
    local affix_id = affix.affix_name_hash
    if item_aspect[affix_id] ~= nil then
        -- if ascending
        if affix:get_roll_max() > affix:get_roll_min() then
            -- simple direct comparison
            if affix:get_roll() == affix:get_roll_max() then return true end

            -- dealing with int value of max_roll
            if affix:get_roll_max() == math.floor(affix:get_roll_max()) then
                -- 0.5 for rounding instead of floor
                return math.floor(affix:get_roll() + 0.5) >= affix:get_roll_max()
            end

            -- dealing with decimals up to 2 places
            return math.floor((affix:get_roll() * 100) + 0.5) >= affix:get_roll_max() * 100
        else
            -- simple direct comparison
            if affix:get_roll() == affix:get_roll_max() then return true end

            -- dealing with int value of min_roll
            if affix:get_roll_max() == math.floor(affix:get_roll_max()) then
                -- 0.5 for rounding instead of floor
                return math.floor(affix:get_roll() + 0.5) <= affix:get_roll_max()
            end
            -- dealing with decimals up to 2 places
            return math.floor((affix:get_roll() * 100) + 0.5) <= affix:get_roll_max() * 100
        end

    end
    return false
end
function utils.is_correct_unique(item)
    local item_id = item:get_sno_id()
    return utils.settings.ancestral_unique[item_id] ~= nil or utils.settings.ancestral_mythic[item_id] ~= nil
end
function utils.is_correct_mythic(item)
    local item_id = item:get_sno_id()
    return utils.settings.ancestral_mythic[item_id] ~= nil or utils.settings.ancestral_unique[item_id] ~= nil
end
function utils.is_correct_unique_charm(item)
    local item_id = item:get_sno_id()
    return utils.settings.talisman_charm_unique[item_id] ~= nil
end
function utils.is_correct_set_charm(item)
    local item_id = item:get_sno_id()
    return utils.settings.talisman_charm_set[item_id] ~= nil
end
function utils.is_mythic_seal(item)
    local ok,rarity=pcall(function() return item:get_rarity() end)
    return ok and type(rarity)=='number' and rarity>=8 or utils.mythic_seals[item:get_sno_id()] ~= nil
end
function utils.is_correct_mythic_seal(item)
    local item_id = item:get_sno_id()
    return utils.settings.talisman_seal_mythic[item_id] ~= nil
end
function utils.is_correct_affix(item_type, affix)
    if not utils.settings.ancestral_affix then return false end
    local affix_id = affix.affix_name_hash
    local t = utils.settings.ancestral_affix[item_type]
    return t and t[affix_id] or false
end
function utils.is_correct_aspect(affix)
    local affix_id = affix.affix_name_hash
    return utils.settings.ancestral_aspect[affix_id] ~= nil
end
local legacy_asset_types = {
    helm='helm',hlm='helm',chest='chest',trs='chest',gloves='gloves',glove='gloves',glv='gloves',
    pants='pants',leg='pants',boots='boots',bts='boots',amulet='amulet',necklace='amulet',ring='ring',
    focus='offhand',book='offhand',totem='offhand',shield='offhand',
    offhandssorc='offhand',offhandsnecro='offhand',offhandswarlock='offhand',offhandsdruid='offhand',
    quarterstaff='weapon_2h',glaive='weapon_2h',polearm='weapon_2h',bow='weapon_2h',crossbow='weapon_2h',staff='weapon_2h',
    ['2hsword']='weapon_2h',['2hmace']='weapon_2h',['2haxe']='weapon_2h',['2hscythe']='weapon_2h',
    ['2hpolearm']='weapon_2h',['2hstaff']='weapon_2h',
    sword='weapon_1h',mace='weapon_1h',axe='weapon_1h',scythe='weapon_1h',wand='weapon_1h',flail='weapon_1h',dagger='weapon_1h',
    ['1hsword']='weapon_1h',['1hmace']='weapon_1h',['1haxe']='weapon_1h',['1hscythe']='weapon_1h',
    ['1hwand']='weapon_1h',['1hflail']='weapon_1h',['1hdagger']='weapon_1h',
}
function utils.get_item_type(item)
    local ok,id=pcall(function() return item:get_sno_id() end)
    if not ok or type(id)~='number' or id<=0 or id>=math.huge or id~=math.floor(id) then return 'unknown' end
    local meta=current_items[id]
    if meta then
        if meta.kind=='equipment' then return catalog_slots[meta.slot] or 'unknown' end
        if meta.kind=='charm' then return 'talisman_charm' end
        if meta.kind=='seal' then return 'talisman_seal' end
        if meta.kind=='cache' then return 'cache' end
        -- A known fish/quest/recipe is never gear merely because of a name fragment.
        return 'unknown'
    end
    local readable,name=pcall(function() return item:get_name() end)
    if not readable or type(name)~='string' then return 'unknown' end
    name=string.lower(name)
    if name:match('cache') then return 'cache' end
    if name:match('tempering') then return 'tempering' end
    -- A gear word anywhere in an unknown asset name is not a category witness.
    -- Accept only explicit legacy asset prefixes; catalogued non-gear never
    -- reaches this compatibility fallback.
    if name:find('qst',1,true) or name:find('quest',1,true) or name:find('cosmetic',1,true)
        or name:find('recipe',1,true) then return 'unknown' end
    if name:match('^talisman_seal[_%d]') then return 'talisman_seal' end
    if name:match('^talisman_charm[_%d]') then return 'talisman_charm' end
    local token=name:match('^([%w]+)_') or name:match('^([%w]+)$')
    token=token and token:gsub('%d+$','') or ''
    return legacy_asset_types[token] or 'unknown'
end
function utils.is_salvage_or_sell(item,action)
    local is_salvage_or_sell, _, _ = utils.is_salvage_or_sell_with_data(item, action)
    return is_salvage_or_sell
end
local classify_equipment
function utils.is_salvage_or_sell_with_data(item,action)
    local ok, is_salvage_or_sell, affix_count, is_max_aspect = pcall(classify_equipment, item, action)
    if not ok then return false, 0, false end
    return is_salvage_or_sell == true, affix_count or 0, is_max_aspect == true
end
classify_equipment = function(item,action)
    if not utils.can_modify_item(item) then return false,0,false end

    local item_id = item:get_sno_id()

    local item_type = utils.get_item_type(item)
    if item_type == 'cache' then return false, 0, false end
    if item_type == 'unknown' then return false, 0, false end
    if item_type == 'tempering' then return false, 0, false end

    local rarity = item:get_rarity()
    if not valid_rarity(rarity) then return false,0,false end
    local is_unique  = rarity == 6
    local is_mythic  = rarity>=8 or utils.mythics[item_id] ~= nil
    local ga_count,ga_readable = utils.get_item_ga_count(item)

    -- QQT_Warpigz_v2 local patch (H3): "Always keep mythics" (default on; the
    -- old WarPigz Alfred's mythic_always_keep key) overrides every rule, the
    -- loot filter included. Switched off, mythics still never take the
    -- loot-filter or junk action: only the GA, name-list and mythic rules.
    if is_mythic and utils.settings.mythic_always_keep ~= false then return false, 0, false end

    -- loot filter mode: in-game filter is the sole rule
    if utils.settings.loot_filter_mode and not is_mythic then
        local ok, filtered = pcall(function() return item:is_filtered_by_loot_filter() end)
        if ok and filtered==true then return action == utils.item_enum['SALVAGE'], 0, false end
        return false, 0, false
    end

    -- loot filter equipment mode: in-game filter decides equipment, Rosie handles the rest
    if utils.settings.loot_filter_equipment and not is_mythic then
        local ok, filtered = pcall(function() return item:is_filtered_by_loot_filter() end)
        if ok and filtered==true then return action==utils.item_enum['SALVAGE'],0,false end
        return false,0,false
    end

    if not ga_readable then return false,0,false end

    local meta=current_items[item_id]
    if rarity_conflicts_with_catalog(meta,rarity,is_mythic) then
        return false,0,false -- metadata never substitutes a destructive rarity decision
    end

    local ancestry_ok,is_ancestral=pcall(function() return item:is_ancestral() end)
    local junk_ok,is_junk=pcall(function() return item:is_junk() end)
    if not ancestry_ok or type(is_ancestral)~='boolean' or not junk_ok or type(is_junk)~='boolean' then return false,0,false end

    -- non-ancestral path
    if not is_ancestral and not is_mythic then
        if is_junk then
            return utils.settings.item_junk == action, 0, false
        elseif is_unique then
            return utils.settings.item_unique == action, 0, false
        else
            return utils.settings.item_legendary_or_lower == action, 0, false
        end
    end

    -- ancestral path
    if is_junk and not is_mythic then
        return utils.settings.ancestral_item_junk == action, 0, false
    end

    -- mythic
    if is_mythic then
        if utils.settings.ancestral_mythic_ga_count > 0 and ga_count >= utils.settings.ancestral_mythic_ga_count then
            return false, 0, false  -- GA override: keep
        end
        if utils.settings.ancestral_unique_filter and utils.is_correct_mythic(item) then
            return false, 0, false  -- name filter: keep
        end
        return utils.settings.ancestral_item_mythic == action, 0, false
    end

    -- unique
    if is_unique then
        if utils.settings.ancestral_unique_ga_count > 0 and ga_count >= utils.settings.ancestral_unique_ga_count then
            return false, 0, false  -- GA override: keep
        end
        if utils.settings.ancestral_unique_filter and utils.is_correct_unique(item) then
            return false, 0, false  -- name filter: keep
        end
        return utils.settings.ancestral_item_unique == action, 0, false
    end

    -- non-unique, non-mythic (rare/magic/legendary)
    if utils.settings.ancestral_ga_count > 0 and ga_count >= utils.settings.ancestral_ga_count then
        if utils.settings.ancestral_filter and utils.settings.ancestral_affix then
            local matched = 0
            for _, affix in pairs(item:get_affixes()) do
                if utils.is_correct_affix(item_type, affix) then matched = matched + 1 end
            end
            if matched >= utils.settings.ancestral_affix_count then
                return false, matched, false
            end
        else
            return false, 0, false
        end
    end
    return utils.settings.ancestral_item_legendary == action, 0, false
end
function utils.is_mounted()
    local local_player = get_local_player()
    return local_player~=nil and local_player:get_attribute(attributes.CURRENT_MOUNT) < 0
end
local update_debounce_time = get_time_since_inject()
local update_debounce_timeout = 0.5
-- QQT_Warpigz_v2 (M3): a forced recount (every service pulse, every menu
-- frame) runs at most every FORCED_INTERVAL; force == 'now' (a request) is
-- immediate.
local FORCED_INTERVAL = 0.25
-- QQT_Warpigz_v2 (M2): one unreadable item is skipped (kept), it never ends
-- the census or the trip.
local function census_entry(item)
    if utils.settings.skip_favorite and item:is_locked() then return nil end
    local is_salvage, affix_count, is_max_aspect = utils.is_salvage_or_sell_with_data(item,utils.item_enum['SALVAGE'])
    local is_sell = utils.is_salvage_or_sell(item,utils.item_enum['SELL'])
    local is_stash = not is_salvage and not is_sell
    if is_stash then
        local item_type = utils.get_item_type(item)
        if (item_type == 'cache' and utils.settings.skip_cache) then
            is_stash = false
        end
    end
    return {
        is_salvage = is_salvage,
        is_sell = is_sell,
        is_stash = is_stash,
        affix_count = affix_count,
        is_max_aspect = is_max_aspect,
        item = item
    }
end
local function talisman_census(item)
    if utils.settings.skip_favorite and item:is_locked() then return nil end
    if utils.should_sell_talisman(item) then return 'sell' end
    if utils.should_salvage_talisman(item) then return 'salvage' end
    return 'stash'
end
local census_errors = {}
local function census_error(why)
    local message = tostring(why)
    if census_errors[message] then return end
    census_errors[message] = true
    console.print('[Rosie] Item skipped this census (unreadable): ' .. message)
end
function utils.update_tracker_count(local_player,force)
    if not local_player then return end
    local now = get_time_since_inject()
    if not force and update_debounce_time + update_debounce_timeout > now then return end
    if force == true and now >= update_debounce_time and now - update_debounce_time < FORCED_INTERVAL then return end
    update_debounce_time = now


    local items = local_player:get_inventory_items()
    local cached_inventory = {}
    local salvage_counter = 0
    local sell_counter = 0
    local stash_counter = 0
    for _, item in pairs(items) do
        if item then
            local ok, entry = pcall(census_entry, item)
            if not ok then
                census_error(entry)
            elseif entry then
                if entry.is_salvage then
                    salvage_counter = salvage_counter + 1
                elseif entry.is_sell then
                    sell_counter = sell_counter + 1
                elseif entry.is_stash then
                    stash_counter = stash_counter + 1
                end
                cached_inventory[#cached_inventory+1] = entry
            end
        else
            utils.log('no item??')
        end
    end
    local salvage_talisman_counter = 0
    local stash_talisman_counter = 0
    local sell_equipment_counter = sell_counter
    local sell_talisman_counter = 0
    local talisman_items = local_player:get_talisman_items()
    for _, item in pairs(talisman_items) do
        local ok, kind = pcall(talisman_census, item)
        if not ok then
            census_error(kind)
        elseif kind == 'sell' then
            sell_counter = sell_counter + 1
            sell_talisman_counter = sell_talisman_counter + 1
        elseif kind == 'salvage' then
            salvage_talisman_counter = salvage_talisman_counter + 1
        elseif kind == 'stash' then
            stash_talisman_counter = stash_talisman_counter + 1
        end
    end
    tracker.cached_inventory = cached_inventory
    tracker.inventory_count = local_player:get_item_count()
    tracker.talisman_inventory_count = #talisman_items
    tracker.salvage_count = salvage_counter
    tracker.salvage_talisman_count = salvage_talisman_counter
    tracker.stash_talisman_count = stash_talisman_counter
    tracker.sell_count = sell_counter
    tracker.sell_equipment_count = sell_equipment_counter
    tracker.sell_talisman_count = sell_talisman_counter
    tracker.stash_count = stash_counter
    tracker.inventory_full = tracker.inventory_count >= utils.settings.max_inventory

    local need_repair = false
    local items = local_player:get_equipped_items()
    for _, item in pairs(items) do
        local ok, durability = pcall(function() return item:get_durability() end)
        if not ok then census_error(durability)
        elseif type(durability) == 'number' and durability <= 10 then
            need_repair = true
        end
    end
    tracker.need_repair = need_repair
    tracker.need_stash_socketables = utils.settings.stash_socketables == utils.stash_extra_enum['FULL'] and #local_player:get_socketable_items() >= utils.settings.max_inventory
    tracker.need_stash_consumables = utils.settings.stash_consumables == utils.stash_extra_enum['FULL'] and #local_player:get_consumable_items() >= utils.settings.max_inventory
    tracker.need_stash_keys        = utils.settings.stash_keys        == utils.stash_extra_enum['FULL'] and #local_player:get_dungeon_key_items() >= utils.settings.max_inventory
    tracker.talisman_inventory_full    = #talisman_items >= utils.settings.max_inventory

    tracker.need_trigger = tracker.inventory_full or
        tracker.need_repair or
        tracker.need_stash_socketables or
        tracker.need_stash_consumables or
        tracker.need_stash_keys or
        tracker.talisman_inventory_full

    tracker.name = utils.settings.plugin_label
    tracker.version = utils.settings.plugin_version
end
-- QQT_Warpigz_v2 (L1): the unused import/export helpers were removed; they
-- redirected the process-wide io.output and had no caller.
function utils.dump_tracker_info(tracker_data)
    local keys={}
    for key,data in pairs(tracker_data) do
        if type(key)=='string' and (type(data)=='string' or type(data)=='number' or type(data)=='boolean') then
            keys[#keys+1]=key
        end
    end
    table.sort(keys)
    console.print('[Rosie] Current service diagnostics:')
    for _,key in ipairs(keys) do console.print('[Rosie] '..key..': '..tostring(tracker_data[key])) end
end

for _, slot in ipairs(affix_slot_names) do load_affix_slot(slot) end
for _, slot in ipairs(aspect_slot_names) do load_aspect_slot(slot) end
get_uniques()
build_picker_catalog()

return utils
