-- Generated by tools/build-rosie.mjs; edit the reviewed source or transform.
-- Observe the active vendor role; an accepted interaction is not an open UI.
local utils=require 'rosie.private.town.core.utils'
local M={}
local function try(fn)
    local ok,value=pcall(fn)
    if ok then return value end
end
-- NPC vendors: the identity check is live-proven (rc.8 Blacksmith repair).
-- QQT_Warpigz_v2 local patch (Rosie 1.0.7): 'STASH' is not an NPC vendor;
-- it never gates on the vendor identity (stash_signals below).
function M.is_open(key)
    if key=='STASH' then return (M.stash_signals(nil)) end -- nil base: an open NPC panel vetoes every signal
    local expected=utils.npc_enum[key]
    if type(expected)~='string' then return false end
    local ok,matched=pcall(function()
        if loot_manager.is_in_vendor_screen()~=true then return false end
        local current=loot_manager.get_current_vendor()
        return current~=nil and current:get_skin_name()==expected
    end)
    return ok and matched==true
end
function M.action(key,action,item)
    -- Recheck before every item: a previous command can close or change the UI.
    if not M.is_open(key) then return false end
    return utils.vendor_action(action,item)
end
-- QQT_Warpigz_v2 local patch (live 2.3.0-rc.8): the stash chest is not an NPC
-- vendor. Its panel is observed through the vendor-screen flag (Alfred), the
-- inventory panel it opens (RootDriver) or a stable non-empty stash list
-- (Alfred/WonderCity). get_current_vendor() is only a hint: a readable other
-- NPC vetoes the flag; signals already up before the interaction (baseline)
-- are ignored.
function M.sdk_open()
    local value=try(function() return loot_manager:is_in_vendor_screen() end)
    if value==nil then value=try(function() return loot_manager.is_in_vendor_screen() end) end
    return value==true
end
function M.current_skin()
    local skin=try(function()
        local current=loot_manager.get_current_vendor()
        return current and current:get_skin_name() or nil
    end)
    return type(skin)=='string' and skin~='' and skin or nil
end
-- QQT_Warpigz_v2 local patch (review rc.10): the signals read just before a
-- session's first chest interaction. A signal already up then proves nothing
-- about the chest (a cached stash list, an inventory panel opened by the
-- player or next to an NPC panel, a flag raised by another panel).
function M.stash_baseline()
    local n=try(function() return #get_local_player():get_stash_items() end)
    return {sdk=M.sdk_open(),inv=try(function() return is_inventory_open() end)==true,
        n=type(n)=='number' and n or nil,skin=M.current_skin()}
end
-- An NPC panel that read open through the identity gate before the chest
-- interaction still reads open: no deposit (probe included) may go to it.
function M.npc_panel_held(base)
    if type(base)~='table' or not base.sdk or base.skin==nil or base.skin==utils.npc_enum.STASH then return false end
    return M.sdk_open() and M.current_skin()==base.skin
end
-- seen: the caller's previous stash count (nil: no count evidence).
-- base: M.stash_baseline() from before the first interaction; nil (no
-- session) lets a readable other NPC with the flag up veto every signal.
-- Returns open, count, diagnostic text, and the deciding signal.
function M.stash_signals(seen,base)
    local sdk,skin=M.sdk_open(),M.current_skin()
    local inv=try(function() return is_inventory_open() end)==true
    local n=try(function() return #get_local_player():get_stash_items() end)
    if type(n)~='number' then n=nil end
    local other=skin~=nil and skin~=utils.npc_enum.STASH
    local diag=string.format('sdk=%s inv=%s vendor=%s stash_n=%s',
        tostring(sdk),tostring(inv),tostring(skin),tostring(n))
    if base==nil and sdk and other then return false,n,diag,nil end
    local b=type(base)=='table' and base or {}
    local why=(inv and not b.inv) and 'inv'
        or (seen~=nil and n~=nil and n>0 and n==seen and not (b.n and b.n>0)) and 'count'
        or (sdk and not other and not b.sdk) and 'sdk' or nil
    return why~=nil,n,diag,why
end
return M
