-- Generated by tools/build-rosie.mjs; edit the reviewed source or transform.
-- Observe the active vendor role; an accepted interaction is not an open UI.
local utils=require 'rosie.private.town.core.utils'
local M={}
function M.is_open(key)
    local expected=utils.npc_enum[key]
    if type(expected)~='string' then return false end
    local ok,matched=pcall(function()
        if loot_manager.is_in_vendor_screen()~=true then return false end
        local current=loot_manager.get_current_vendor()
        return current~=nil and current:get_skin_name()==expected
    end)
    return ok and matched==true
end
function M.action(key,action,item)
    -- Recheck before every item: a previous command can close or change the UI.
    if not M.is_open(key) then return false end
    return utils.vendor_action(action,item)
end
return M
