-- Generated by tools/build-rosie.mjs; edit the reviewed source or transform.
local utils = require 'rosie.private.town.core.utils'
local settings = require 'rosie.private.town.core.settings'
local tracker = require 'rosie.private.town.core.tracker'
local town_movement = require 'rosie.private.town.core.town_movement'

-- actions need to be overwritten
local extension = {
    get_npc = function () end,
    move = function () end,
    interact = function () end,
    execute = function () end,
    reset = function () end,
    is_done = function () return false end,
    done = function () end,
    failed = function () end,
    is_in_vendor_screen = function () return false end
}

-- status_enum needs to be overwritten
local status_enum = {
    IDLE = 'Idle',
    EXECUTE = 'Action',
    MOVING = 'Moving to npc',
    INTERACTING = 'Interacting with npc',
    RESETTING = 'Re-trying action',
    FAILED = 'Action failed'
}

-- shouldExecute needs to be overwritten
local function shouldExecute()
    return false
end

local base = {}
function base.new_task()
    local task = {
        name = 'base',
        status = status_enum['IDLE'],
        last_interaction = 0,
        retry = 0,
        interaction_timeout = 2,
        max_retries = 2,
        last_location = nil,
        last_stuck_location = nil,
        reset_state = nil,
    }

    task.extension = extension
    task.status_enum = status_enum
    task.shouldExecute = shouldExecute

    function task.set_status(status)
        local status_prefix = ''
        if tracker.external_caller then
            status_prefix = '(' .. tostring(tracker.external_caller) .. ') '
        end
        task.status = status_prefix .. status
    end

    function task.check_status(status)
        local status_prefix = ''
        if tracker.external_caller then
            status_prefix = '(' .. tostring(tracker.external_caller) .. ') '
        end
        return task.status == status_prefix .. status
    end
    function task.reset_session()
        task.set_status(task.status_enum.IDLE)
        task.last_interaction,task.retry=0,0
        task.last_location,task.last_stuck_location,task.reset_state=nil,nil,nil
        task.progress_at=nil
        task.elapsed,task.last_tick,task.next_action=0,nil,0
    end
    function task.suspend()
        task.last_tick=nil
        task.progress_at=nil
        -- Preserve a vendor interaction phase through a long recovery wait.
        task.last_interaction=get_time_since_inject()
    end

    function task.Execute()
        local current_time = get_time_since_inject()
        local player=get_local_player()
        if not player or player:is_dead() or tracker.external_pause then task.suspend(); return end
        task.elapsed=(task.elapsed or 0)+(task.last_tick and current_time-task.last_tick or 0)
        task.last_tick=current_time
        if task.elapsed>=45 then task.extension.failed(); task.set_status(task.status_enum.FAILED); return end
        if current_time<(task.next_action or 0) then return end
        task.next_action=current_time+0.3
        -- A completed reset must re-enter approach/interaction even when it
        -- already arrived beside the NPC. Otherwise the final else fails it.
        if task.check_status(task.status_enum.RESETTING)
            and task.last_interaction+task.interaction_timeout<current_time then
            task.set_status(task.status_enum.IDLE)
        end
        if task.name~='teleport' and task.check_status(task.status_enum.EXECUTE)
            and not task.extension.is_in_vendor_screen() then
            task.set_status(task.status_enum.IDLE)
        end
        local npc = task.extension.get_npc()
        local npc_bugged = false
        local player_stuck = false
        local player_position = town_movement.snapshot(get_player_position())
        if not player_position then task.suspend(); return end

        if npc then
            local npc_pos = npc:get_position()
            if npc_pos:x() == 0 and npc_pos:y() == 0 and npc_pos:z() == 0 then
                npc_bugged = true
            end
        end

        if not task.last_location or town_movement.progressed(task.last_location,player_position) then
            task.last_location=player_position
            task.progress_at=current_time
        end
        task.progress_at=task.progress_at or current_time
        player_stuck=task.check_status(task.status_enum.MOVING) and current_time-task.progress_at>=2

        if task.extension.is_done() then
            if not town_movement.stop() then return end
            task.set_status(task.status_enum['IDLE'])
            task.retry = 0
            task.last_interaction = 0
            task.extension.done()
        elseif task.check_status(task.status_enum.IDLE) then
            task.last_interaction=current_time
            if npc and (npc_bugged or utils.distance_to(npc)<2) then
                if not town_movement.stop() then return end
                task.set_status(task.status_enum.INTERACTING); task.extension.interact()
            else
                task.set_status(task.status_enum.MOVING); task.extension.move()
            end
        elseif task.check_status(task.status_enum['MOVING']) and
            player_stuck and
            task.last_stuck_location == nil and
            task.last_interaction + task.interaction_timeout < current_time
        then
            task.set_status(task.status_enum['RESETTING'])
            task.last_interaction = current_time
            task.retry = task.retry + 1
            task.reset_state = task.status_enum['MOVING']
            task.extension.reset()
            task.last_stuck_location = player_position
        elseif task.check_status(task.status_enum['RESETTING']) and
            task.last_interaction + task.interaction_timeout >= current_time
        then
            task.set_status(task.status_enum['RESETTING'])
            task.extension.reset()
        elseif (not npc or (not npc_bugged and utils.distance_to(npc) >= 2)) and
            task.last_interaction + task.interaction_timeout < current_time
        then
            task.set_status(task.status_enum['MOVING'])
            task.last_interaction = current_time
            task.last_stuck_location = nil
            task.extension.move()
        elseif task.check_status(task.status_enum['MOVING']) and
            (not npc or (not npc_bugged and utils.distance_to(npc) >= 2)) and
            task.last_interaction + task.interaction_timeout >= current_time
        then
            task.set_status(task.status_enum['MOVING'])
            task.extension.move()
        elseif (npc_bugged or (npc and utils.distance_to(npc) < 2)) and
            (task.check_status(task.status_enum['MOVING']) or
            task.check_status(task.status_enum['IDLE']))
        then
            if not town_movement.stop() then return end
            task.set_status(task.status_enum['INTERACTING'])
            task.last_interaction = current_time
            task.extension.interact()
        elseif task.check_status(task.status_enum['INTERACTING']) and
            task.last_interaction + task.interaction_timeout >= current_time and
            not (task.extension.is_in_vendor_screen())
        then
            task.set_status(task.status_enum['INTERACTING'])
            task.extension.interact()
        elseif task.check_status(task.status_enum['INTERACTING']) and
            task.name~='teleport' and not task.extension.is_in_vendor_screen() and
            task.last_interaction + task.interaction_timeout < current_time
        then
            task.retry=task.retry+1
            if task.retry>task.max_retries then
                task.extension.failed(); task.set_status(task.status_enum.FAILED)
            else
                task.set_status(task.status_enum.RESETTING); task.last_interaction=current_time
                task.extension.reset()
            end
        elseif task.check_status(task.status_enum['INTERACTING']) and
            (task.extension.is_in_vendor_screen() or
            task.last_interaction + task.interaction_timeout < current_time)
        then
            task.set_status(task.status_enum['EXECUTE'])
            task.last_interaction = current_time
            task.extension.execute()
        elseif task.check_status(task.status_enum['EXECUTE']) and
            task.last_interaction + task.interaction_timeout >= current_time and
            not task.extension.is_done()
        then
            task.set_status(task.status_enum['EXECUTE'])
            task.extension.execute()
        elseif task.check_status(task.status_enum['EXECUTE']) and
            task.last_interaction + task.interaction_timeout < current_time and
            not task.extension.is_done() and
            task.retry < task.max_retries
        then
            task.set_status(task.status_enum['RESETTING'])
            task.last_interaction = current_time
            task.retry = task.retry + 1
            task.reset_state = task.status_enum['EXECUTE']
            task.extension.reset()
        else
            task.extension.failed()
            task.set_status(task.status_enum['FAILED'])
            task.retry = 0
        end
    end

    return task
end

return base
