-- Generated by tools/build-rosie.mjs; edit the reviewed source or transform.
local BatmobilePlugin=nil -- Rosie owns native movement.
local plugin_label = 'alfred_the_butler'

local utils        = require 'rosie.private.town.core.utils'
local tracker      = require 'rosie.private.town.core.tracker'
local explorerlite = require 'rosie.private.town.core.explorerlite'
local town_movement = require 'rosie.private.town.core.town_movement'
local vendor = require 'rosie.private.town.core.vendor'

local DEBUG = false -- QQT_Warpigz_v2: release build, no per-step console output
local function dbg(msg)
    if DEBUG then console.print('[Rosie:stash_pull] ' .. tostring(msg)) end
end

-- -----------------------------------------------------------------------
-- State
-- -----------------------------------------------------------------------
local phase  = 'PULL'    -- PULL | SALVAGE | SALVAGE_TALISMAN | SELL | DONE
local sub    = 'IDLE'    -- IDLE | MOVING | INTERACTING | EXECUTE
local last_int   = 0
local int_tout   = 2.5
local retry      = 0
local max_retry  = 3
local last_pos   = nil
local debounce   = nil
local deb_tout   = 0.8

-- Built from pending_pulls once per run; {[sno_id] = true}
local to_salvage_snos  = {}
local to_sell_snos     = {}
local pull_initialized = false
local stash_seen_count = -1   -- for stash-screen fallback detection
local stash_interacted = false -- QQT_Warpigz_v2: stash signals count only after this session interacted
-- QQT_Warpigz_v2 local patch (review rc.10): signals before the first chest
-- interaction, kept copies (mythics) and the PULL progress clock.
local stash_base, kept, execute_at, pull_progress, pull_left = nil, {}, 0, 0, math.huge
local selected, matched_snos, elapsed, last_tick, next_step = {},{},0,nil,0
local initial_bag_items = {}
local unstable_initial_items = {}
local function identity(item)
    local ok,id=pcall(function() return item:get_acd() end)
    if ok and type(id)=='number' and id>0 then return 'acd:'..tostring(id),true end
    return item,false -- require the same handle when no stable host identity is available
end
local function unlocked(item)
    return utils.can_modify_item(item)
end

local function bag_items(player)
    local items={}
    for _,item in pairs(player:get_inventory_items()) do items[#items+1]=item end
    for _,item in pairs(player:get_talisman_items()) do items[#items+1]=item end
    return items
end

local function next_work_phase()
    for _,name in ipairs({'SALVAGE','SALVAGE_TALISMAN','SELL'}) do
        for _,entry in pairs(selected) do
            if entry.phase==name and not entry.completed then return name end
        end
    end
    return 'DONE'
end

local function reset_state()
    phase = 'PULL'
    sub   = 'IDLE'
    last_int   = 0
    retry      = 0
    last_pos   = nil
    debounce   = nil
    to_salvage_snos  = {}
    to_sell_snos     = {}
    pull_initialized = false
    stash_seen_count = -1
    stash_interacted = false
    stash_base, kept, execute_at, pull_progress, pull_left = nil, {}, 0, 0, math.huge
    selected,matched_snos,elapsed,last_tick,next_step={},{},0,nil,0
    initial_bag_items={}
    unstable_initial_items={}
end

local function build_sno_tables()
    to_salvage_snos = {}
    to_sell_snos    = {}
    for _, entry in ipairs(tracker.pending_pulls) do
        if entry.action == 'salvage' then
            to_salvage_snos[entry.sno_id] = true
        elseif entry.action == 'sell' then
            to_sell_snos[entry.sno_id] = true
        end
    end
    local ns, nv = 0, 0
    for _ in pairs(to_salvage_snos) do ns = ns + 1 end
    for _ in pairs(to_sell_snos)    do nv = nv + 1 end
    dbg(string.format('build_sno_tables: salvage_snos=%d sell_snos=%d', ns, nv))
end

-- -----------------------------------------------------------------------
-- NPC helpers
-- -----------------------------------------------------------------------
local function npc_key_for_phase()
    if phase == 'SALVAGE' then return 'BLACKSMITH' end
    if phase == 'SALVAGE_TALISMAN' then return 'OCCULTIST' end
    if phase == 'SELL'    then return 'GAMBLER' end
    return 'STASH'
end

local function get_npc(key)
    return utils.get_npc(utils.npc_enum[key])
end

local function move_to(key)
    local loc = town_movement.target(key)
    if not loc then return false end
    if BatmobilePlugin then
        BatmobilePlugin.set_target(plugin_label, loc)
        BatmobilePlugin.move(plugin_label)
    else
        explorerlite:set_custom_target(loc)
        explorerlite:move_to_target()
    end
end

local function clear_bat()
    return town_movement.stop()
end

-- -----------------------------------------------------------------------
-- Vendor-screen detection
-- -----------------------------------------------------------------------
local function sdk_vendor_open()
    return vendor.is_open(npc_key_for_phase())
end

-- QQT_Warpigz_v2 local patch (live 2.3.0-rc.8): the stash chest is not an NPC
-- vendor; vendor.is_open('STASH') required get_current_vendor() to name it.
local function is_stash_open(player)
    if not stash_interacted then return false end
    local open,n=vendor.stash_signals(stash_seen_count,stash_base)
    stash_seen_count=n or -1
    return open
end

-- -----------------------------------------------------------------------
-- Task
-- -----------------------------------------------------------------------
local task = {}
task.name   = 'stash_pull'
task.status = 'Idle'
task.reset_session=function()
    reset_state()
    -- The normal stash task runs before this queue. Its KEEP items must not
    -- become newly authorized just because they share a queued stash SNO.
    local player=get_local_player()
    if player then
        for _,item in ipairs(bag_items(player)) do
            local id,stable=identity(item)
            initial_bag_items[id]=true
            if not stable then unstable_initial_items[id]=item:get_sno_id() end
        end
    end
end
task.suspend=function() last_tick=nil; last_int=get_time_since_inject() end

local function finish_disposition(player)
    local observed={}
    for _,item in ipairs(bag_items(player)) do observed[identity(item)]=item end
    local pending=false
    for id,entry in pairs(selected) do
        if entry.phase==phase and not entry.completed then
            local item=observed[id]
            if not item then
                if not entry.issued then
                    tracker.stash_pull_failed=true
                    tracker.failure_reason='Queued item disappeared before '..entry.action..': '..tostring(entry.sno_id)
                    return false
                end
                entry.completed=true
            else
                if not entry.arrived or item:get_sno_id()~=entry.sno_id or not unlocked(item) then
                    tracker.stash_pull_failed=true
                    tracker.failure_reason='Queued item identity or lock changed before '..entry.action
                    return false
                end
                -- QQT_Warpigz_v2 local patch (review rc.10): the bag copy
                -- may now read as a Mythic (affixes loaded after the pull).
                local keep=utils.pull_protected(item)
                if keep then
                    tracker.stash_pull_failed=true
                    tracker.failure_reason='Queued item kept after the pull ('..keep..'): '..tostring(entry.sno_id)
                    return false
                end
                pending=true
                local action=entry.action=='sell' and loot_manager.sell_specific_item or loot_manager.salvage_specific_item
                local result=vendor.action(npc_key_for_phase(),function(target)
                    -- A refused return can still accompany an observed effect;
                    -- only an actually issued host call authorizes that evidence.
                    entry.issued=true
                    return action(target)
                end,item)
                dbg(string.format('%s sno=%d -> %s',entry.action,entry.sno_id,tostring(result)))
            end
        end
    end
    return not pending
end

task.shouldExecute = function()
    if not tracker.trigger_tasks   then return false end
    if tracker.service_pulls==false then return false end
    if not utils.is_in_town()      then return false end
    if tracker.stash_pull_done     then return false end
    if tracker.stash_pull_failed   then return false end
    if not (tracker.stash_done or tracker.stash_failed) then return false end
    if #tracker.pending_pulls == 0 then return false end
    return true
end

task.Execute = function()
    local now    = get_time_since_inject()
    local player = get_local_player()
    if not player or player:is_dead() or tracker.external_pause then task.suspend(); return end
    elapsed=elapsed+(last_tick and now-last_tick or 0); last_tick=now
    if elapsed>=60 then
        tracker.stash_pull_failed=true; clear_bat(); task.status='Stash pull timed out'; return
    end
    if now<next_step then return end
    next_step=now+0.2

    -- ----------------------------------------------------------------
    -- DONE
    -- ----------------------------------------------------------------
    if phase == 'DONE' then
        dbg('complete — stash_pull_done=true, clearing pending_pulls')
        clear_bat()
        tracker.stash_pull_done = true
        tracker.pending_pulls   = {}
        reset_state()
        return
    end

    local key = npc_key_for_phase()
    local npc = get_npc(key)
    local pos = town_movement.snapshot(get_player_position())
    if not pos then task.suspend(); return end

    -- ----------------------------------------------------------------
    -- IDLE → MOVING
    -- ----------------------------------------------------------------
    if sub == 'IDLE' then
        task.status = phase .. ': moving to ' .. key
        sub      = 'MOVING'
        last_int = now
        last_pos = pos
        move_to(key)
        return
    end

    -- ----------------------------------------------------------------
    -- MOVING
    -- ----------------------------------------------------------------
    if sub == 'MOVING' then
        if npc and utils.distance_to(npc) < 2 then
            if not clear_bat() then return end
            sub      = 'INTERACTING'
            task.status = phase .. ': interacting'
            last_int = now
            if phase == 'PULL' and not stash_base then stash_base = vendor.stash_baseline() end
            interact_vendor(npc)
            if phase == 'PULL' then stash_interacted = true end
            return
        end
        if phase == 'PULL' then stash_interacted = false; stash_base = nil end
        if not last_pos or town_movement.progressed(last_pos,pos) then
            last_pos=pos;last_int=now;retry=0
        end
        if now - last_int > int_tout then
            retry = retry + 1
            dbg(string.format('MOVING stuck retry=%d/%d', retry, max_retry))
            if retry >= max_retry then
                dbg('MOVING max retries — failing')
                clear_bat()
                tracker.stash_pull_failed = true
                reset_state()
                return
            end
            last_int = now
        end
        move_to(key)
        return
    end

    -- ----------------------------------------------------------------
    -- INTERACTING
    -- ----------------------------------------------------------------
    if sub == 'INTERACTING' then
        local open = (phase == 'PULL') and is_stash_open(player) or sdk_vendor_open()
        -- QQT_Warpigz_v2 local patch (review rc.10): like Alfred, a pull goes
        -- ahead int_tout after the interaction whatever the signals say. A pull
        -- from a closed chest moves nothing; EXECUTE re-interacts (retry-bounded)
        -- when nothing arrives.
        if phase == 'PULL' and not open and now - last_int > int_tout then open = true end
        if open then
            if phase == 'PULL' then
                execute_at, pull_progress, pull_left = now, now, math.huge
                for _,entry in pairs(selected) do entry.calls = 0 end
            end
            sub      = 'EXECUTE'
            task.status = phase .. ': executing'
            last_int = now
            debounce = nil
            return
        end
        if now - last_int > int_tout then
            retry = retry + 1
            dbg(string.format('INTERACTING timeout retry=%d/%d', retry, max_retry))
            if retry >= max_retry then
                dbg('INTERACTING max retries — failing')
                clear_bat()
                tracker.stash_pull_failed = true
                reset_state()
                return
            end
            if npc then interact_vendor(npc) end
            last_int = now
        end
        return
    end

    if sub ~= 'EXECUTE' then return end
    -- The stash has no EXECUTE re-gate (Alfred): its pulls are verified by the
    -- identity checks below and the 60 s bound. NPC phases keep the proven gate.
    if phase ~= 'PULL' and not sdk_vendor_open() then sub='INTERACTING'; last_int=now; return end

    -- ----------------------------------------------------------------
    -- EXECUTE (debounced)
    -- ----------------------------------------------------------------
    if debounce and now - debounce < deb_tout then return end
    debounce = now

    -- ---- PULL phase ----
    if phase == 'PULL' then
        if not pull_initialized then
            build_sno_tables()
            pull_initialized = true
        end

        local stash_items  = player:get_stash_items()
        local remaining = 0
        -- Back to INTERACTING with a fresh interaction, bounded by max_retry.
        local function reinteract(reason)
            retry = retry + 1
            if retry >= max_retry then
                tracker.stash_pull_failed=true; tracker.failure_reason=reason; return
            end
            sub='INTERACTING'; last_int=now; stash_seen_count=-1
            if npc then interact_vendor(npc) end
        end

        -- An initial bag handle may be replaced by the host during ordinary
        -- stashing. Without a stable ACD, a same-SNO replacement cannot safely
        -- be distinguished from the separately queued stash item.
        local observed_initial={}
        for _,item in ipairs(bag_items(player)) do observed_initial[identity(item)]=true end
        for _,item in ipairs(stash_items) do observed_initial[identity(item)]=true end
        for id,sno in pairs(unstable_initial_items) do
            if (to_salvage_snos[sno] or to_sell_snos[sno]) and not observed_initial[id] then
                tracker.stash_pull_failed=true
                tracker.failure_reason='Cannot distinguish a queued SNO from an initial bag item without stable identity: '..tostring(sno)
                return
            end
        end

        for _, item in ipairs(stash_items) do
            local sno = item:get_sno_id()
            local id=identity(item)
            -- QQT_Warpigz_v2 local patch (review rc.10): a queued SNO never
            -- takes a stashed Mythic (an S15 form shares its Unique's SNO).
            local keep=(to_salvage_snos[sno] or to_sell_snos[sno]) and not initial_bag_items[id]
                and not selected[id] and utils.pull_protected(item)
            if keep then
                if not kept[sno] then
                    kept[sno]=keep
                    console.print('[Rosie:stash_pull] Kept in the stash: sno='..tostring(sno)..' ('..keep..').')
                end
            elseif (to_salvage_snos[sno] or to_sell_snos[sno]) and not initial_bag_items[id] then
                if not unlocked(item) then
                    tracker.stash_pull_failed=true; tracker.failure_reason='Queued stash item is locked or unreadable'; return
                end
                remaining = remaining + 1
                local entry=selected[id]
                if not entry then
                    -- Capture metadata before a transfer can expire this handle.
                    local kind=utils.get_item_type(item)
                    local action=to_salvage_snos[sno] and 'salvage' or 'sell'
                    local work_phase=action=='sell' and 'SELL' or
                        (kind=='talisman_seal' or kind=='talisman_charm') and 'SALVAGE_TALISMAN' or 'SALVAGE'
                    entry={sno_id=sno,action=action,phase=work_phase,arrived=false,issued=false,completed=false,calls=0}
                end
                selected[id]=entry
                matched_snos[sno]=true
                -- A direct call (Alfred): the stash is not an NPC vendor. At
                -- most 3 calls per item per interaction (the deposit's bound).
                if (entry.calls or 0) < 3 then
                    entry.calls=(entry.calls or 0)+1
                    local _,ok = pcall(loot_manager.move_item_from_stash,item)
                    dbg(string.format('move_item_from_stash sno=%d -> %s', sno, tostring(ok)))
                end
            end
        end

        if remaining > 0 then
            if remaining < pull_left then pull_left, pull_progress = remaining, now end
            if now - pull_progress > int_tout then
                reinteract('The stash did not hand over the queued items after '..max_retry..' interactions')
            end
            return
        end
        local missing=nil
        for _,entry in ipairs(tracker.pending_pulls) do
            if not matched_snos[entry.sno_id] and not kept[entry.sno_id] then missing=entry.sno_id; break end
        end
        -- QQT_Warpigz_v2 local patch (review rc.10): the stash list can lag the
        -- panel; re-read it for 3 s before judging a queued SNO absent.
        if (missing or not next(selected)) and now - execute_at < 3 then return end
        if not next(selected) then
            if not missing and next(kept) then
                local list={}
                for sno,why in pairs(kept) do list[#list+1]=tostring(sno)..' ('..why..')' end
                table.sort(list)
                tracker.stash_pull_failed=true
                tracker.failure_reason='Queued items kept in the stash: '..table.concat(list,', ')
                return
            end
            -- Nothing arrived and nothing matched: the chest may not be open.
            reinteract(missing and 'Queued SNO not found: '..tostring(missing) or 'Queued items were not found in the stash')
            return
        end
        if missing then
            tracker.stash_pull_failed=true; tracker.failure_reason='Queued SNO not found: '..tostring(missing); return
        end
        -- A host return is acceptance; observe the selected handles in the bag.
        local observed={}
        for _,item in ipairs(bag_items(player)) do observed[identity(item)]=true end
        for id,entry in pairs(selected) do
            if not observed[id] then return end
            entry.arrived=true
        end
        dbg('PULL complete — nothing left in stash from queue')
        phase = next_work_phase()
        sub   = 'IDLE'
        retry = 0
        return
    end

    -- Verify the selected identity after a real native action, in its actual bag.
    if phase=='SALVAGE' or phase=='SALVAGE_TALISMAN' or phase=='SELL' then
        if finish_disposition(player) then
            dbg(phase..' complete')
            phase = next_work_phase()
            sub   = 'IDLE'
            retry = 0
        end
        return
    end
end

return task
