-- Generated by tools/build-rosie.mjs; edit the reviewed source or transform.
local pathfinder=require('rosie.movement').for_owner('town')
local BatmobilePlugin=nil -- Rosie owns native movement.
-- Stash movement and transfers share one observed session. Commands are not receipts.
local utils = require 'rosie.private.town.core.utils'
local settings = require 'rosie.private.town.core.settings'
local tracker = require 'rosie.private.town.core.tracker'
local explorerlite = require 'rosie.private.town.core.explorerlite'
local task = require('rosie.private.town.tasks.base').new_task()
local plugin_label = 'alfred_the_butler'
local state

task.name = 'stash'
task.status_enum = {
    IDLE = 'Idle', MOVING = 'Moving to stash', INTERACTING = 'Opening stash',
    EXECUTE = 'Depositing into stash', FAILED = 'Failed to stash',
}

local function log(message) console.print('[Rosie:stash] '..message) end
local function release_movement()
    if BatmobilePlugin then BatmobilePlugin.clear_target(plugin_label) end
    explorerlite:clear_path_and_target()
    pathfinder.clear_stored_path()
end

function task.reset_session()
    state = { time=0, progress=0, next_action=0, next_interact=0, interactions=0 }
    task.set_status(task.status_enum.IDLE)
end
function task.suspend()
    if state then state.last_tick=nil end
end
task.reset_session()

local function eligible(item)
    return item~=nil and (not settings.skip_favorite or not item:is_locked())
end
local function should_stash_item(item)
    if not eligible(item) then return false end
    return not utils.is_salvage_or_sell(item,utils.item_enum.SELL)
        and not utils.is_salvage_or_sell(item,utils.item_enum.SALVAGE)
        and not (settings.skip_cache and utils.get_item_type(item)=='cache')
end

-- Rebuild from fresh bags after each receipt; never retain a transferred wrapper.
local function next_item(player)
    for _,item in pairs(player:get_inventory_items()) do
        if should_stash_item(item) then return item,'get_inventory_items' end
    end
    if tracker.stash_boss_materials then
        for _,item in pairs(player:get_consumable_items()) do
            if eligible(item) then return item,'get_consumable_items' end
        end
    end
    if tracker.stash_keys then
        for _,item in pairs(player:get_dungeon_key_items()) do
            local sigil=string.lower(item:get_name() or ''):match('dungeonsigil')
            if eligible(item) and (not sigil or tracker.stash_sigils and item:is_locked()) then
                return item,'get_dungeon_key_items'
            end
        end
    end
    if tracker.stash_socketables then
        for _,item in pairs(player:get_socketable_items()) do
            if eligible(item) then return item,'get_socketable_items' end
        end
    end
    if tracker.stash_talisman_seal or tracker.stash_talisman_charm then
        for _,item in pairs(player:get_talisman_items()) do
            if eligible(item) and not utils.should_salvage_talisman(item) and not utils.should_sell_talisman(item) then
                return item,'get_talisman_items'
            end
        end
    end
end

local function units(item)
    local n=item:get_stack_count()
    if type(n)~='number' or n~=n or n<0 or n==math.huge then return nil end
    return math.max(1,n) -- Non-stackable host items may report zero.
end
local function quantity(player,bag,sno)
    local ok,result=pcall(function()
        local items=player[bag](player)
        if type(items)~='table' then return nil end
        local count=0
        for _,item in pairs(items) do
            local id=item:get_sno_id()
            if type(id)~='number' or id<=0 then return nil end
            if id==sno then
                local n=units(item); if not n then return nil end
                count=count+n
            end
        end
        return count
    end)
    if ok then return result end
end

-- QQT_Warpigz_v2 local patch (live 2.3.0-rc.8): the stash opened but Rosie
-- reported "Stash window did not open after 4 interactions" at 1.9 m. The
-- stash is not a vendor: the live host does not report it through
-- get_current_vendor(), which Rosie required. Alfred's proven check is used
-- instead: the host's vendor-screen flag, or stash contents that read the
-- same on two consecutive checks (the stash panel is open).
local last_stash_count=-1
local function other_vendor_open()
    -- A readable current vendor that is another NPC (the Blacksmith after a
    -- repair) is not the stash. The stash itself reads as nil on the live host.
    local ok,skin=pcall(function()
        local current=loot_manager.get_current_vendor()
        return current and current:get_skin_name() or nil
    end)
    return ok and type(skin)=='string' and skin~='' and skin~=utils.npc_enum.STASH
end
local function stash_open()
    if other_vendor_open() then last_stash_count=-1; return false end
    local ok,open=pcall(function() return loot_manager:is_in_vendor_screen() end)
    if not (ok and open==true) then ok,open=pcall(loot_manager.is_in_vendor_screen) end
    if ok and open==true then return true end
    local counted,count=pcall(function() return #get_local_player():get_stash_items() end)
    local stable=counted and type(count)=='number' and count>0 and count==last_stash_count
    last_stash_count=counted and type(count)=='number' and count or -1
    return stable==true
end

local function stash_actor()
    local best,best_distance,selected=nil,math.huge,nil
    local origin=get_player_position()
    local function scan(list)
        for _,actor in pairs(list or {}) do
            local ok,pos,id=pcall(function()
                if actor:get_skin_name()~=utils.npc_enum.STASH then return nil end
                return actor:get_position(),actor:get_id()
            end)
            if ok and pos and (pos:x()~=0 or pos:y()~=0 or pos:z()~=0) then
                local distance=origin:dist_to(pos)
                if state.actor_id and id==state.actor_id then selected=actor end
                if distance<best_distance then best,best_distance=actor,distance end
            end
        end
    end
    scan(actors_manager:get_all_actors()); scan(get_actors_list())
    local actor=selected or best
    if actor then
        state.actor_id=actor:get_id()
        local pos=actor:get_position()
        state.position=vec3:new(pos:x(),pos:y(),pos:z())
    end
    return actor
end

local function fail(reason)
    release_movement()
    tracker.stash_failed=true
    tracker.failure_reason='Stash: '..reason
    task.set_status(task.status_enum.FAILED)
    log(reason)
end
local function finish()
    release_movement()
    tracker.stash_done=true
    task.set_status(task.status_enum.IDLE)
    log('All selected deposits observed; continuing town service.')
end

local function pending_receipt(player)
    local p=state.pending
    if not p then return false end
    local source=quantity(player,p.bag,p.sno)
    local destination=quantity(player,'get_stash_items',p.sno)
    if source and destination and source<=p.source-p.amount and destination>=p.destination+p.amount then
        log('Deposited '..p.name..' (sno='..p.sno..'); source and stash updated.')
        state.pending=nil; state.progress=state.time; state.interactions=0; state.deposited=true
        return false
    end
    if state.time-p.sent<3 then return true end
    if source~=p.source or destination~=p.destination then
        -- A partial or unreadable receipt is not permission to repeat a move.
        task.set_status('Waiting for stash transfer confirmation: '..p.name)
        return true
    end
    if p.attempts>=3 then
        fail('No transfer observed for '..p.name..' (sno='..p.sno..', host return='..tostring(p.result)..') after 3 attempts.')
        return true
    end
    -- Fresh item selection below; a failed native handle is never reused.
    state.retry=p; state.pending=nil
    return false
end

function task.Execute()
    local player=get_local_player()
    if not player or player:is_dead() or tracker.external_pause then task.suspend(); return end
    local now=get_time_since_inject()
    state.time=state.time+(state.last_tick and math.max(0,now-state.last_tick) or 0)
    state.last_tick=now
    if state.time<state.next_action then return end
    state.next_action=state.time+0.3
    local waiting=pending_receipt(player)
    if tracker.stash_failed then return end
    if waiting then
        if state.time-state.progress>=45 then
            fail('Transfer confirmation timed out for '..state.pending.name..'; item kept unresolved.')
            return
        end
    end
    local item,bag
    if not waiting then item,bag=next_item(player) end
    if not waiting and not item then finish(); return end
    if state.deposited and #player:get_stash_items()>=settings.max_stash_items then
        tracker.stash_full=true; fail('Configured stash capacity reached.'); return
    end
    if state.time-state.progress>=45 then
        fail('No stash progress for 45 active seconds; check the chest and available space.')
        return
    end
    local actor=stash_actor()
    if not stash_open() then
        local distance=actor and utils.distance_to(actor)
        if actor and distance<=3 then
            release_movement()
            task.set_status(task.status_enum.INTERACTING)
            if state.time>=state.next_interact then
                if state.interactions>=4 then fail('Stash window did not open after 4 interactions.'); return end
                state.interactions=state.interactions+1; state.next_interact=state.time+3
                local ok,result=pcall(interact_vendor,actor)
                log(string.format('Open stash: attempt=%d distance=%.1f host=%s',state.interactions,distance,tostring(ok and result)))
            end
        else
            task.set_status(task.status_enum.MOVING)
            local target=utils.compute_move_target(state.position or utils.get_npc_location('STASH'))
            if BatmobilePlugin then
                BatmobilePlugin.set_target(plugin_label,target); BatmobilePlugin.move(plugin_label)
            else
                explorerlite:set_custom_target(target); explorerlite:move_to_target()
            end
        end
        return
    end
    -- The open stash is stronger evidence than a center-distance estimate.
    release_movement()
    -- Reopen a closed stash for observation, without issuing a second command
    -- for a transfer whose source or destination has already changed.
    if waiting then return end
    task.set_status(task.status_enum.EXECUTE)
    local stash_count=#player:get_stash_items()
    tracker.stash_item_count_cached=stash_count
    if stash_count>=settings.max_stash_items then
        tracker.stash_full=true; fail('Configured stash capacity reached ('..stash_count..'/'..settings.max_stash_items..').'); return
    end
    local ok,sno,amount,name=pcall(function() return item:get_sno_id(),units(item),item:get_name() end)
    if not ok or type(sno)~='number' or sno<=0 or not amount then
        fail('Item metadata unavailable; deposit left unresolved.'); return
    end
    local source=quantity(player,bag,sno)
    local destination=quantity(player,'get_stash_items',sno)
    if not source or not destination then
        task.set_status('Waiting for readable stash and bag contents'); return
    end
    local previous=state.retry
    local attempts=previous and previous.sno==sno and previous.bag==bag and previous.attempts+1 or 1
    -- Capture every field BEFORE the call: a moved wrapper can expire immediately.
    local pending={sno=sno,amount=amount,name=tostring(name),bag=bag,source=source,destination=destination,
        sent=state.time,attempts=attempts}
    state.pending=pending; state.retry=nil
    if not stash_open() then state.pending=nil; return end
    -- Alfred issues the move directly: vendor_action requires the vendor-screen
    -- flag, which the stash panel may not raise.
    local called,result=pcall(loot_manager.move_item_to_stash,item)
    pending.result=called and result or false
    tracker.last_task=task.name
    log('Deposit requested: '..pending.name..' (sno='..sno..', attempt='..attempts..', host='..tostring(pending.result)..').')
end

function task.shouldExecute()
    return utils.is_in_town() and tracker.trigger_tasks and not tracker.stash_failed and not tracker.stash_done
        and (tracker.sell_done or tracker.sell_failed) and (tracker.salvage_done or tracker.salvage_failed)
        and (tracker.salvage_talisman_done or tracker.salvage_talisman_failed)
end
return task
