-- Generated by tools/build-rosie.mjs; edit the reviewed source or transform.
local utils=require 'rosie.private.town.core.utils'
local settings=require 'rosie.private.town.core.settings'
local tracker=require 'rosie.private.town.core.tracker'
local lifecycle=require 'rosie.private.town.core.lifecycle'
local task={name='Status',status='Idle'}
local function complete()
    for _,key in ipairs({'sell','salvage','salvage_talisman','repair','stash'}) do
        if not tracker[key..'_done'] and not tracker[key..'_failed'] then return false end
    end
    if tracker.service_pulls~=false and #(tracker.pending_pulls or {})>0 and not tracker.stash_pull_done and not tracker.stash_pull_failed then return false end
    return not tracker.return_required or tracker.teleport_done or tracker.teleport_failed
end
-- QQT_Warpigz_v3: a failed service step (sell_failed, salvage_failed, ...)
-- no longer ends the trip at once: this task runs first on every pulse, so
-- finishing on the first failure skipped repair, stash and the return portal
-- and left the character in Temis. The remaining steps already accept X_done
-- or X_failed; the trip finishes (as failed, with the first failure) once
-- complete() is true. Only a failure that stops the remaining steps finishes
-- at once: the trip never started its service (trigger_tasks false) or never
-- reached town (outbound teleport_failed). Host errors, the 240 s and pause
-- bounds and cancellation finish directly in lifecycle/controller.
local function stops_now(failure)
    if failure==nil then return false end
    return not tracker.trigger_tasks or not tracker.visited_town
end
function task.shouldExecute()
    return tracker.external_pause or not tracker.trigger_tasks or stops_now(lifecycle.failure()) or complete()
end
function task.Execute()
    local player=get_local_player()
    if not player or player:is_dead() or tracker.external_pause then task.status='Paused'; return end
    local failure=lifecycle.failure()
    if failure and not stops_now(failure) and not complete() then
        -- QQT_Warpigz_v3: continue with the remaining steps and the return.
        task.status='Continuing after '..failure
        return
    end
    -- QQT_Warpigz_v3: every service leg done and only the way back failed
    -- (no TownPortal): the service itself completed; never a fail_streak.
    if failure=='teleport_failed' and tracker.failure_reason==nil and tracker.trigger_tasks
        and tracker.visited_town and complete() then
        if not tracker.return_missing_logged then
            tracker.return_missing_logged=true
            console.print('[Rosie] return portal missing: town service completed; the caller travels back itself')
        end
        failure=nil
    end
    if failure then task.status='Failed: '..failure; lifecycle.finish(false,failure); return end
    if tracker.trigger_tasks and complete() then
        if tracker.need_trigger then
            task.status='Service needs remain'
            -- QQT_Warpigz_v3 (Q5): items the stash skipped this trip (not
            -- confirmed or unreadable) may go on the next trip: a retryable
            -- failure (cooldown, fail streak), never the permanent latch.
            -- QQT_Warpigz_v3 1.0.25 (stash passes): the stash did not take them.
            local skipped=tracker.stash_skipped
            if type(skipped)=='table' and #skipped>0 then
                lifecycle.finish(false,'Stash left '..#skipped..' item(s) in the bag ('
                    ..table.concat(skipped,', ')..'); bag needs remain')
                return
            end
            -- QQT_Warpigz_v2: a complete service that cannot clear the need will
            -- not clear it on a retry either (protected items, settings).
            -- QQT_Warpigz_v3 3.3.1: say which need is left and what the bag holds.
            local t=tracker
            local left={}
            if t.inventory_full then left[#left+1]='equipment bag '..tostring(t.inventory_count) end
            if t.talisman_inventory_full then left[#left+1]='talisman bag '..tostring(t.talisman_inventory_count) end
            if t.need_repair then left[#left+1]='repair' end
            if t.need_stash_socketables or t.need_stash_consumables or t.need_stash_keys then left[#left+1]='socketables/materials/keys' end
            lifecycle.finish(false,string.format('Town service left needs unresolved (%s; still to stash %d+%d, sell %d, salvage %d+%d, max bag %s); check protected items and service settings',
                table.concat(left,', '),tonumber(t.stash_count) or 0,tonumber(t.stash_talisman_count) or 0,tonumber(t.sell_count) or 0,
                tonumber(t.salvage_count) or 0,tonumber(t.salvage_talisman_count) or 0,tostring(settings.max_inventory)),'permanent')
            return
        end
        task.status='Service completed'; lifecycle.finish(true); return
    end
    if tracker.external_trigger or tracker.manual_trigger then
        if not tracker.trigger_tasks then
            tracker.stash_socketables=settings.stash_socketables==utils.stash_extra_enum.ALWAYS or tracker.need_stash_socketables
            tracker.stash_boss_materials=settings.stash_consumables==utils.stash_extra_enum.ALWAYS or tracker.need_stash_consumables
            tracker.stash_keys=settings.stash_keys==utils.stash_extra_enum.ALWAYS or tracker.need_stash_keys
            tracker.stash_sigils=tracker.stash_keys and settings.stash_sigils
            tracker.salvage_sigils=settings.salvage_sigils
            tracker.stash_talisman_seal,tracker.stash_talisman_charm=true,true
            tracker.salvage_talisman_seal=settings.talisman_seal_action==utils.item_enum.SALVAGE
            tracker.salvage_talisman_charm=settings.talisman_charm_action==utils.item_enum.SALVAGE
            tracker.trigger_tasks=true; tracker.all_task_done=false
            lifecycle.hold_peers()
        end
        task.status='Servicing and returning'
    else task.status='Idle' end
end
return task
