-- Generated by tools/build-rosie.mjs; edit the reviewed source or transform.
local utils=require 'rosie.private.town.core.utils'
local settings=require 'rosie.private.town.core.settings'
local tracker=require 'rosie.private.town.core.tracker'
local lifecycle=require 'rosie.private.town.core.lifecycle'
local task={name='Status',status='Idle'}
local function complete()
    for _,key in ipairs({'sell','salvage','salvage_talisman','repair','stash'}) do
        if not tracker[key..'_done'] and not tracker[key..'_failed'] then return false end
    end
    if tracker.service_pulls~=false and #(tracker.pending_pulls or {})>0 and not tracker.stash_pull_done and not tracker.stash_pull_failed then return false end
    return not tracker.return_required or tracker.teleport_done or tracker.teleport_failed
end
function task.shouldExecute()
    return tracker.external_pause or not tracker.trigger_tasks or lifecycle.failure()~=nil or complete()
end
function task.Execute()
    local player=get_local_player()
    if not player or player:is_dead() or tracker.external_pause then task.status='Paused'; return end
    local failure=lifecycle.failure()
    if failure then task.status='Failed: '..failure; lifecycle.finish(false,failure); return end
    if tracker.trigger_tasks and complete() then
        if tracker.need_trigger then
            task.status='Service needs remain'
            -- QQT_Warpigz_v2: a complete service that cannot clear the need will
            -- not clear it on a retry either (protected items, settings).
            lifecycle.finish(false,'Town service left inventory or repair needs unresolved; check protected items and service settings','permanent')
            return
        end
        task.status='Service completed'; lifecycle.finish(true); return
    end
    if tracker.external_trigger or tracker.manual_trigger then
        if not tracker.trigger_tasks then
            tracker.stash_socketables=settings.stash_socketables==utils.stash_extra_enum.ALWAYS or tracker.need_stash_socketables
            tracker.stash_boss_materials=settings.stash_consumables==utils.stash_extra_enum.ALWAYS or tracker.need_stash_consumables
            tracker.stash_keys=settings.stash_keys==utils.stash_extra_enum.ALWAYS or tracker.need_stash_keys
            tracker.stash_sigils=tracker.stash_keys and settings.stash_sigils
            tracker.salvage_sigils=settings.salvage_sigils
            tracker.stash_talisman_seal,tracker.stash_talisman_charm=true,true
            tracker.salvage_talisman_seal=settings.talisman_seal_action==utils.item_enum.SALVAGE
            tracker.salvage_talisman_charm=settings.talisman_charm_action==utils.item_enum.SALVAGE
            tracker.trigger_tasks=true; tracker.all_task_done=false
            lifecycle.hold_peers()
        end
        task.status='Servicing and returning'
    else task.status='Idle' end
end
return task
