-- Generated by tools/build-rosie.mjs; edit the reviewed source or transform.
local BatmobilePlugin=nil -- Rosie owns native movement.
local plugin_label = 'alfred_the_butler'

local utils = require 'rosie.private.town.core.utils'
local settings = require 'rosie.private.town.core.settings'
local tracker = require 'rosie.private.town.core.tracker'
local explorerlite = require 'rosie.private.town.core.explorerlite'
local base_task = require 'rosie.private.town.tasks.base'
local lifecycle = require 'rosie.private.town.core.lifecycle'
local town_movement = require 'rosie.private.town.core.town_movement'

local task = base_task.new_task()
local status_enum = {
    IDLE = 'Idle',
    WAITING = 'Waiting ',
    EXECUTE = 'Teleporting',
    MOVING = 'Moving to portal',
    INTERACTING = 'Interacting with portal',
    RESETTING = 'Re-trying teleport',
    FAILED = 'Failed to teleport'
}
local debounce_time = -1
local debounce_timeout = 3
local outbound_attempts = 0
local outbound = false
local reset_session = task.reset_session
function task.reset_session()
    reset_session(); debounce_time=-1; outbound_attempts=0; outbound=false
end
local function teleport_with_debounce()
    local local_player = get_local_player()
    if not local_player or local_player:is_dead() then return end
    if local_player:get_active_spell_id() == 186139 then
        task.set_status(status_enum['EXECUTE'])
    else
        local status = status_enum['WAITING'] ..
        string.format("%.2f", debounce_time + debounce_timeout - get_time_since_inject()) .. 's'
        task.set_status(status)
    end
    if debounce_time + debounce_timeout > get_time_since_inject() then return end
    if outbound_attempts>=8 then return end
    outbound_attempts=outbound_attempts+1
    debounce_time = get_time_since_inject()
    teleport_to_waypoint(utils.get_town().waypoint_sno)
    task.set_status(status_enum['EXECUTE'])
end
local extension = {}
function extension.get_npc()
    return utils.get_npc(utils.npc_enum['PORTAL'])
end
function extension.move()
    if utils.player_in_zone('[sno none]') then return end
    local npc_location = town_movement.target('PORTAL')
    if not npc_location then return false end
    if BatmobilePlugin then
        BatmobilePlugin.set_target(plugin_label, npc_location)
        BatmobilePlugin.move(plugin_label)
    else
        explorerlite:set_custom_target(npc_location)
        explorerlite:move_to_target()
    end
end
function extension.interact()
    local npc = extension.get_npc()
    if npc then interact_object(npc) end
end
function extension.execute()
    local npc = extension.get_npc()
    if npc then interact_object(npc) end
end

function extension.reset()
    local local_player = get_local_player()
    if not local_player then return end
    local resets = utils.get_town().reset_positions
    local new_position = resets.default
    if tracker.last_task == 'stash' then
        new_position = resets.stash
    elseif tracker.last_task == 'salvage' then
        new_position = resets.salvage
    elseif tracker.last_task ==  'sell' or tracker.last_task == 'gamble' then
        new_position = resets.sell_gamble
    end
    if BatmobilePlugin then
        BatmobilePlugin.set_target(plugin_label, new_position)
        BatmobilePlugin.move(plugin_label)
    else
        explorerlite:set_custom_target(new_position)
        explorerlite:move_to_target()
    end
end
function extension.is_done()
    return lifecycle.returned()
end
function extension.done()
    if BatmobilePlugin then
        BatmobilePlugin.clear_target(plugin_label)
    end
    tracker.teleport_done = true
end
function extension.failed()
    if BatmobilePlugin then
        BatmobilePlugin.clear_target(plugin_label)
    end
    tracker.teleport_failed = true
end
function extension.is_in_vendor_screen() return false end

task.name = 'teleport'
task.extension = extension
task.status_enum = status_enum
task.max_retries = 5
task.teleport_time = nil

task.shouldExecute = function ()
    if not tracker.return_required or tracker.teleport_done or tracker.teleport_failed then return false end
    if tracker.trigger_tasks == false then
        task.retry = 0
    end
    if tracker.teleport and not utils.is_in_town()
    then
        return true
    elseif utils.is_in_town() and
        tracker.trigger_tasks and
        not tracker.teleport_failed and
        not tracker.teleport_done and
        (tracker.sell_done or tracker.sell_failed) and
        (tracker.salvage_done or tracker.salvage_failed) and
        (tracker.repair_done or tracker.repair_failed) and
        (tracker.stash_done or tracker.stash_failed) and
        (tracker.salvage_talisman_done or tracker.salvage_talisman_failed) and
        (tracker.service_pulls==false or #(tracker.pending_pulls or {})==0 or tracker.stash_pull_done or tracker.stash_pull_failed)
    then
        if task.check_status(task.status_enum['FAILED']) then
            task.set_status(task.status_enum['IDLE'])
        end
        return true
    end
    return false
end
task.baseExecute = task.Execute
task.Execute = function ()
    local player=get_local_player()
    if not player or player:is_dead() or tracker.external_pause then return end
    if tracker.visited_town and not utils.is_in_town() then
        if lifecycle.returned() then extension.done()
        elseif not utils.player_in_zone('[sno none]') then extension.failed() end
        return
    end
    if tracker.teleport and not utils.is_in_town() then
        if tracker.service_elapsed>=60 then extension.failed(); return end
        outbound=true
        task.retry = 0
        lifecycle.hold_peers()
        teleport_with_debounce()
    else
        if outbound then reset_session(); outbound=false end
        task.baseExecute()
    end
end

return task
