-- Generated by tools/build-rosie.mjs; edit the reviewed source or transform.
local BatmobilePlugin=nil -- Rosie owns native movement.
local plugin_label = 'alfred_the_butler'

local utils = require 'rosie.private.town.core.utils'
local settings = require 'rosie.private.town.core.settings'
local tracker = require 'rosie.private.town.core.tracker'
local explorerlite = require 'rosie.private.town.core.explorerlite'
local base_task = require 'rosie.private.town.tasks.base'
local lifecycle = require 'rosie.private.town.core.lifecycle'
local town_movement = require 'rosie.private.town.core.town_movement'
local pathfinder = require('rosie.movement').for_owner('town') -- QQT_Warpigz_v3
local foreign = require 'rosie.private.foreign' -- QQT_Warpigz_v3 1.0.21
local ItemManager = require 'rosie.private.pickup.src.item_manager' -- QQT_Warpigz_v3 1.0.24
local PickupSettings = require 'rosie.private.pickup.src.settings' -- QQT_Warpigz_v3 1.0.24
local Pickup = require 'rosie.private.pickup.src.pickup' -- QQT_Warpigz_v3 1.0.24 (read-only: fight_deferred)

local task = base_task.new_task()
local status_enum = {
    IDLE = 'Idle',
    WAITING = 'Waiting ',
    EXECUTE = 'Teleporting',
    MOVING = 'Moving to portal',
    INTERACTING = 'Interacting with portal',
    RESETTING = 'Re-trying teleport',
    FAILED = 'Failed to teleport'
}
local debounce_time = -1
-- QQT_Warpigz_v3 1.0.24: 3 -> 8 s between casts; a channel younger than
-- CHANNEL_MAX s is never re-cast (see teleport_with_debounce).
local debounce_timeout = 8
local CHANNEL_MAX = 15
local outbound_attempts = 0
local outbound = false
local cast = {refunded = false, logged = false, request = nil} -- QQT_Warpigz_v3 1.0.21
-- QQT_Warpigz_v3 1.0.22: at most MAX_REFUNDS interrupted casts are refunded per
-- trip. A nudge after every cast (orbwalker/rotation in a fight) made the 8-cast
-- cap moot (27 casts, one every 3 s, until the 60 s outbound bound); now 12 at most.
local MAX_REFUNDS = 4
cast.refunds = 0
-- Exported for audit/tests/test_rosie_foreign_mover.lua (the stop-and-go case
-- needs more than 8 and at most 8+MAX_REFUNDS-1 interrupts).
task.MAX_REFUNDS = MAX_REFUNDS
local reset_session = task.reset_session
function task.reset_session()
    reset_session(); debounce_time=-1; outbound_attempts=0; outbound=false; cast.refunded=false
    cast.refunds=0 -- QQT_Warpigz_v3 1.0.22: per trip
end
local function teleport_with_debounce()
    local local_player = get_local_player()
    if not local_player or local_player:is_dead() then return end
    if cast.request ~= tracker.request_id then cast.request, cast.logged = tracker.request_id, false end
    -- QQT_Warpigz_v3 1.0.21: Worldstone re-issues Navigator requests on its own.
    foreign.quiet_navigator(tracker.request_id)
    -- QQT_Warpigz_v3 1.0.24 (Undercity "~5 teleports", cause 3; the WonderCity
    -- 2.1.1 / Arkham 3.3.3 rule): a running channel is never re-cast (it was
    -- re-cast every 3 s: a channel over 3 s cost up to 8 casts), and a load
    -- screen restarts the debounce.
    local now = get_time_since_inject()
    local world = get_current_world()
    local wname = world and world:get_name() or ''
    if type(wname) == 'string' and (wname:find('Limbo', 1, true) or wname:find('Loading', 1, true)) then
        debounce_time = now; return
    end
    if local_player:get_active_spell_id() == 186139 and debounce_time >= 0 and now - debounce_time < CHANNEL_MAX then
        task.set_status(status_enum['EXECUTE']); return
    end
    if local_player:get_active_spell_id() == 186139 then
        task.set_status(status_enum['EXECUTE'])
    else
        local status = status_enum['WAITING'] ..
        string.format("%.2f", debounce_time + debounce_timeout - get_time_since_inject()) .. 's'
        task.set_status(status)
    end
    -- QQT_Warpigz_v3 1.0.21: a cast the player was moved out of (another
    -- addon, e.g. Navigator, kept walking) is no attempt; re-cast only once
    -- the player has stood still (the live trip spent 8 casts in 24 s).
    if debounce_time>=0 and not cast.refunded and lifecycle.moved_since(debounce_time) then
        cast.refunded=true
        -- QQT_Warpigz_v3 1.0.22: capped per trip; later interrupted casts count.
        if cast.refunds<MAX_REFUNDS then
            cast.refunds=cast.refunds+1; outbound_attempts=math.max(0,outbound_attempts-1)
            if cast.refunds==MAX_REFUNDS then
                console.print(string.format('[Rosie] Town Portal: %d interrupted casts were not counted; the next ones count as attempts', MAX_REFUNDS))
            end
        end
    end
    if lifecycle.still_for()<lifecycle.STILL then
        if not cast.logged then
            cast.logged=true
            console.print('[Rosie] Town Portal waits: another addon moves the player; casting once it stands still')
        end
        task.set_status('Waiting for the player to stand still')
        return
    end
    if debounce_time + debounce_timeout > get_time_since_inject() then return end
    if outbound_attempts>=8 then return end
    outbound_attempts=outbound_attempts+1
    cast.refunded=false
    debounce_time = get_time_since_inject()
    console.print(string.format('[Rosie] Town Portal cast %d', outbound_attempts)) -- QQT_Warpigz_v3 1.0.24
    -- QQT_Warpigz_v3 1.0.24 (Auditor 7aa276a): the return portal leads back to
    -- where the cast went; a pre-cast pickup walk may have crossed a subzone.
    local cw = get_current_world()
    if cw then tracker.request_world, tracker.request_name, tracker.request_zone = cw:get_world_id(), cw:get_name(), cw:get_current_zone_name() end
    teleport_to_waypoint(utils.get_town().waypoint_sno)
    task.set_status(status_enum['EXECUTE'])
end
-- QQT_Warpigz_v3 1.0.24 (owner, live 3.3.5: a Mythic dropped during the Town
-- Portal cast; Rosie went to town and Worldstone moved on, the drop was lost).
-- On the outbound leg a wanted drop in pickup range is never left behind:
--  * it fits the bag: the trip lends the player to pickup (the cast waits, or
--    the pickup walk interrupts it: that cast is refunded), at most
--    PICK_BUDGET s per trip, then the cast goes on;
--  * the bag is full (the trip's reason): its spot is remembered and, back
--    through the Town Portal, pickup takes it before the trip completes (at
--    most RETURN_WAIT s; skipped when the world changed). The trip stays busy
--    meanwhile, so Worldstone and the farm plugins keep waiting.
local PICK_BUDGET, RETURN_WAIT, RETURN_GRACE = 20, 30, 1.5
local tp = {request = nil}
task.PICK_BUDGET, task.RETURN_WAIT = PICK_BUDGET, RETURN_WAIT -- tests
local function item_label(item)
    local ok, name = pcall(function() return item:get_skin_name() end)
    return ok and name or 'a drop'
end
local function tp_scan(now)
    if tp.scan_at and now >= tp.scan_at and now - tp.scan_at < 0.25 then return end
    tp.scan_at = now
    local ok, fits, room = pcall(ItemManager.trip_drops)
    if ok then tp.fits, tp.room = fits, room else tp.fits, tp.room = nil, nil end
end
local function pickup_busy() return PickupSettings.get().looting == true end
-- QQT_Warpigz_v3 1.0.24 (Auditor 7aa276a): why pickup would not work a drop
-- right now, whatever the trip lends it (nil: it would). The trip holds the
-- cast or waits on the way back only for a drop pickup can take now.
local function pickup_gate(item)
    local ok_e, run = pcall(PickupSettings.should_execute)
    if not ok_e or run ~= true then return 'the pickup Behavior setting (Clear mode only)' end
    local ok_i, inv = pcall(function() return is_inventory_open() or is_chat_open() end)
    if ok_i and inv then return 'chat or inventory open' end
    local loop = rawget(_G, 'TRISTRAM_LOOP_STATE')
    if type(loop) == 'table' and type(loop.status) == 'function' then
        local ok_s, st = pcall(loop.status)
        if ok_s and type(st) == 'table' and st.running == true and st.owns_activity == true and st.controls_loot == true then
            return 'another activity owns the loot'
        end
    end
    if foreign.scavenger_busy() then return 'the Scavenger addon is looting' end
    local ok_f, held = pcall(Pickup.fight_deferred, item)
    if ok_f and held then return 'a fight holds it' end
    return nil
end
local function pause_owners()
    local ok, st = pcall(PickupSettings.pause_state)
    local names = {}
    if ok and type(st) == 'table' and type(st.owners) == 'table' then
        for who in pairs(st.owners) do if who ~= 'Rosie' then names[#names + 1] = tostring(who) end end
    end
    table.sort(names)
    return #names > 0 and table.concat(names, ', ') or 'another plugin'
end
local function tp_session()
    if tp.request ~= tracker.request_id then
        tp.request, tp.spent, tp.since, tp.last, tp.capped = tracker.request_id, 0, nil, nil, false
        tp.left, tp.back, tp.fits, tp.room, tp.scan_at, tp.named, tp.spot = nil, nil, nil, nil, nil, nil, nil
    end
end
local function tp_spot(item)
    local world = get_current_world()
    local okp, x, y = pcall(function() local p = item:get_position(); return p:x(), p:y() end)
    if not world or not okp then return nil end
    return {id = world:get_world_id(), name = world:get_name(), zone = world:get_current_zone_name(),
        x = x, y = y, label = item_label(item)}
end
local function tp_remember(item)
    tp.left = tp_spot(item)
    if tp.left then
        console.print(string.format('[Rosie] %s dropped near the Town Portal, but the bag is full: Rosie picks it up when it comes back',
            tp.left.label))
    end
end
-- In town while the outbound pickup still held the player (the cast landed
-- before the pickup walk interrupted it): the lend ends, and the drop is
-- taken on the way back.
local function tp_arrived()
    if not tp.since then return end
    tp.since = nil
    lifecycle.lend_pickup(false)
    if tp.spot and not tp.left and tracker.return_required then
        tp.left = tp.spot
        console.print('[Rosie] The Town Portal landed before '..tp.left.label..' was picked up: Rosie picks it up when it comes back')
    end
end
-- True while the outbound leg picks up a drop (the cast waits).
local function outbound_pickup()
    tp_session()
    local now = get_time_since_inject()
    if tp.since then tp.spent = tp.spent + math.max(0, now - tp.last); tp.last = now end
    tp_scan(now)
    if tp.room and not tp.left and tracker.return_required then tp_remember(tp.room) end
    -- A drop pickup cannot work now holds nothing: it is tried on the way back.
    if tp.fits and not tp.since then
        local why = pickup_gate(tp.fits)
        if why then
            if not tp.left and tracker.return_required then
                tp.left = tp_spot(tp.fits)
                if tp.left then
                    console.print('[Rosie] '..tp.left.label..' lies near the Town Portal but pickup cannot take it now ('..why..'): Rosie tries on the way back')
                end
            end
            tp.fits = nil
        end
    end
    local want = not tp.capped and tp.spent < PICK_BUDGET and (tp.fits ~= nil or tp.since ~= nil and pickup_busy())
    if want and not tp.since then
        if not lifecycle.lend_pickup(true) then
            tp.capped = true
            if tp.fits and not tp.left and tracker.return_required then
                tp.left = tp_spot(tp.fits)
                if tp.left then
                    console.print('[Rosie] '..tp.left.label..' lies near the Town Portal but pickup is paused by '..pause_owners()..': Rosie tries on the way back')
                end
            end
            return false
        end
        tp.since, tp.last = now, now
        tp.spot = tp.fits and tp_spot(tp.fits) or nil
        -- A cast still in flight is interrupted by the pickup walk: refunded
        -- like any interrupted cast (counted under MAX_REFUNDS).
        if debounce_time >= 0 and not cast.refunded and outbound_attempts > 0
            and now - debounce_time < debounce_timeout and cast.refunds < MAX_REFUNDS then
            cast.refunded = true; outbound_attempts = outbound_attempts - 1; cast.refunds = cast.refunds + 1
        end
        local label = tp.fits and item_label(tp.fits) or 'a drop'
        if tp.named ~= label then
            tp.named = label
            console.print('[Rosie] '..label..' dropped near the Town Portal: picking it up before the cast')
        end
    end
    if want then task.set_status('Picking up a drop before the Town Portal'); return true end
    if tp.since then
        tp.since = nil
        lifecycle.lend_pickup(false)
        if tp.spent >= PICK_BUDGET and not tp.capped then
            tp.capped = true
            console.print(string.format('[Rosie] Pickup before the Town Portal took %ds; casting now', PICK_BUDGET))
        end
        -- A drop pickup did not take (a fight holds it, the game refused it):
        -- one bounded try on the way back, never left silently.
        if tp.fits and not tp.left and tracker.return_required then
            tp.left = tp_spot(tp.fits)
            if tp.left then
                console.print('[Rosie] '..tp.left.label..' was not picked up before the cast: Rosie picks it up when it comes back')
            end
        end
    end
    return false
end
-- True while the return leg picks up the drop the full bag left behind.
local function return_pickup()
    tp_session()
    if not tp.left then return false end
    local now = get_time_since_inject()
    if not tp.back then
        local world = get_current_world()
        if not world or world:get_world_id() ~= tp.left.id or world:get_name() ~= tp.left.name
            or world:get_current_zone_name() ~= tp.left.zone then
            console.print('[Rosie] '..tp.left.label..' was left in another world; not going back for it')
            tp.left = nil; return false
        end
        tp_scan(now)
        local why = tp.fits and pickup_gate(tp.fits) or nil
        if why then
            console.print('[Rosie] '..tp.left.label..' is left: pickup cannot take it now ('..why..')')
            tp.left = nil; return false
        end
        if not lifecycle.lend_pickup(true) then
            console.print('[Rosie] '..tp.left.label..' is left: pickup is paused by '..pause_owners())
            tp.left = nil; return false
        end
        tp.back = now; tracker.return_pickup = true
        console.print(string.format('[Rosie] Back from town: picking up %s (at most %ds)', tp.left.label, RETURN_WAIT))
    end
    tp_scan(now)
    if tp.fits and pickup_gate(tp.fits) then tp.fits = nil end
    local waiting = now - tp.back < RETURN_WAIT and (now - tp.back < RETURN_GRACE or tp.fits ~= nil or pickup_busy())
    if waiting then task.set_status('Picking up the drop left at the Town Portal'); return true end
    lifecycle.lend_pickup(false); tracker.return_pickup = nil
    if now - tp.back >= RETURN_WAIT then
        console.print(string.format('[Rosie] %s was not picked up within %ds; the trip completes', tp.left.label, RETURN_WAIT))
    end
    tp.left = nil
    return false
end
local extension = {}
function extension.get_npc()
    return utils.get_npc(utils.npc_enum['PORTAL'])
end
function extension.move()
    if utils.player_in_zone('[sno none]') then return end
    local npc_location = town_movement.target('PORTAL')
    if not npc_location then return false end
    if BatmobilePlugin then
        BatmobilePlugin.set_target(plugin_label, npc_location)
        BatmobilePlugin.move(plugin_label)
    else
        explorerlite:set_custom_target(npc_location)
        explorerlite:move_to_target()
    end
end
function extension.interact()
    local npc = extension.get_npc()
    if npc then tracker.portal_taken=true; interact_object(npc) end -- QQT_Warpigz_v3 1.0.27: lifecycle.tick (sweep R1)
end
function extension.execute()
    local npc = extension.get_npc()
    if npc then tracker.portal_taken=true; interact_object(npc) end -- QQT_Warpigz_v3 1.0.27: lifecycle.tick (sweep R1)
end

function extension.reset()
    local local_player = get_local_player()
    if not local_player then return end
    local resets = utils.get_town().reset_positions
    local new_position = resets.default
    if tracker.last_task == 'stash' then
        new_position = resets.stash
    elseif tracker.last_task == 'salvage' then
        new_position = resets.salvage
    elseif tracker.last_task ==  'sell' or tracker.last_task == 'gamble' then
        new_position = resets.sell_gamble
    end
    if BatmobilePlugin then
        BatmobilePlugin.set_target(plugin_label, new_position)
        BatmobilePlugin.move(plugin_label)
    else
        explorerlite:set_custom_target(new_position)
        explorerlite:move_to_target()
    end
end
function extension.is_done()
    return lifecycle.returned()
end
function extension.done()
    if BatmobilePlugin then
        BatmobilePlugin.clear_target(plugin_label)
    end
    tracker.teleport_done = true
end
function extension.failed()
    if BatmobilePlugin then
        BatmobilePlugin.clear_target(plugin_label)
    end
    tracker.teleport_failed = true
end
function extension.is_in_vendor_screen() return false end

-- QQT_Warpigz_v3: while any trip runs, SilentRaven's auto-fire holds on
-- 'alfred_busy', and a standalone activity may never stand in Temis
-- otherwise. Once per trip, after every service and before the walk to the
-- return portal, Rosie stops moving and queues the Whisper claim (only when
-- SilentRaven is enabled, takes the hand-off (auto-fire on standalone, or
-- WarPigs delegating: QQT_Warpigz_v3 Q8), a reward ready and not
-- yet claimed this visit), then waits for its callback: at most RAVEN_WAIT
-- seconds, which are not service time (lifecycle.tick, tracker.raven_wait).
local RAVEN_WAIT = 100
local raven = {request = nil, done = true, since = nil}
-- QQT_Warpigz_v3 (Q8): SilentRaven publishes whether it takes the hand-off
-- (`handoff`: its auto-fire standalone, WarPigs' delegation when WarPigs
-- manages Whispers; the night run skipped every managed SilentRaven
-- silently). An older SilentRaven without the field keeps the standalone
-- rule. A ready reward that is not handed over names why (once per trip).
local function raven_plugin()
    local p = rawget(_G, 'SilentRavenPlugin')
    if type(p) ~= 'table' or type(p.get_status) ~= 'function' or type(p.trigger_tasks) ~= 'function' then return nil end
    local ok, s = pcall(p.get_status)
    if not ok or type(s) ~= 'table' or s.enabled ~= true or s.ready ~= true then return nil end
    local consent = s.handoff
    if consent == nil then consent = s.auto_fire == true and s.managed_by == nil end
    local why = (consent ~= true and tostring(s.handoff_reason or 'SilentRaven auto-fire is off or it is managed'))
        or ((s.running == true or s.pending == true) and 'SilentRaven already has a request')
        or (s.paused == true and 'SilentRaven is paused')
        or (s.last_zone_handled == 'Skov_Temis' and 'this Temis visit is already handled') or nil
    if why then return nil, why end
    return p
end
local function raven_finish(message)
    raven.done, tracker.raven_wait = true, nil
    if message then console.print('[Rosie] ' .. message) end
    return false
end
-- True while Rosie waits for SilentRaven (the teleport task does nothing else).
local function raven_handoff()
    local id = tracker.request_id
    if raven.request ~= id then
        raven.request, raven.done, raven.since = id, true, nil
        local p, skip = raven_plugin()
        if not p then
            if skip then console.print('[Rosie] no SilentRaven hand-off: ' .. skip) end -- QQT_Warpigz_v3 (Q8)
            return false
        end
        pathfinder.clear_stored_path()
        local ok, accepted, why = pcall(p.trigger_tasks, settings.plugin_label, function(result)
            if raven.request == id and not raven.done then
                raven_finish('SilentRaven finished (' .. tostring(result) .. '); walking to the return portal')
            end
        end)
        if not ok or accepted ~= true then
            return raven_finish('SilentRaven hand-off refused: ' .. tostring(ok and why or accepted))
        end
        raven.done, raven.since, tracker.raven_wait = false, get_time_since_inject(), true
        console.print('[Rosie] waiting for SilentRaven to claim the Whisper reward before the return portal')
    end
    if raven.done then
        -- The walk to the portal starts from a clean approach state.
        if raven.since then raven.since = nil; task.reset_session() end
        return false
    end
    if get_time_since_inject() - raven.since >= RAVEN_WAIT then
        local p = rawget(_G, 'SilentRavenPlugin')
        if type(p) == 'table' and type(p.cancel) == 'function' then pcall(p.cancel, settings.plugin_label) end
        raven_finish(string.format('SilentRaven did not finish within %ds; walking to the return portal', RAVEN_WAIT))
        raven.since = nil; task.reset_session()
        return false
    end
    task.set_status('Waiting for SilentRaven')
    task.suspend()
    return true
end

task.name = 'teleport'
task.extension = extension
task.status_enum = status_enum
task.max_retries = 5
task.teleport_time = nil

task.shouldExecute = function ()
    if tracker.teleport_done or tracker.teleport_failed then return false end
    -- QQT_Warpigz_v3: a request from another town has no return leg, only
    -- the outbound hop to Temis (until the first town visit).
    if not tracker.return_required and not (tracker.teleport and not tracker.visited_town) then return false end
    if tracker.trigger_tasks == false then
        task.retry = 0
    end
    if tracker.teleport and not utils.is_in_town()
    then
        return true
    elseif utils.is_in_town() and
        tracker.trigger_tasks and
        not tracker.teleport_failed and
        not tracker.teleport_done and
        (tracker.sell_done or tracker.sell_failed) and
        (tracker.salvage_done or tracker.salvage_failed) and
        (tracker.repair_done or tracker.repair_failed) and
        (tracker.stash_done or tracker.stash_failed) and
        (tracker.salvage_talisman_done or tracker.salvage_talisman_failed) and
        (tracker.service_pulls==false or #(tracker.pending_pulls or {})==0 or tracker.stash_pull_done or tracker.stash_pull_failed)
    then
        if task.check_status(task.status_enum['FAILED']) then
            task.set_status(task.status_enum['IDLE'])
        end
        return true
    end
    return false
end
task.baseExecute = task.Execute
task.Execute = function ()
    local player=get_local_player()
    if not player or player:is_dead() or tracker.external_pause then return end
    if tracker.visited_town and not utils.is_in_town() then
        if not tracker.return_required then return end -- QQT_Warpigz_v3: no return leg
        -- QQT_Warpigz_v3 1.0.24: a return pickup that walks across a zone
        -- border still ends as a return (the trip did come back).
        local picking = tp.back ~= nil and tp.left ~= nil and tp.request == tracker.request_id
        if picking or lifecycle.returned() then
            if return_pickup() then return end
            extension.done()
        elseif not utils.player_in_zone('[sno none]') then extension.failed() end
        return
    end
    if tracker.teleport and not utils.is_in_town() then
        if tracker.service_elapsed>=60 then extension.failed(); return end
        outbound=true
        task.retry = 0
        lifecycle.hold_peers()
        if outbound_pickup() then return end -- QQT_Warpigz_v3 1.0.24
        teleport_with_debounce()
    else
        if outbound then reset_session(); outbound=false end
        if tp.request == tracker.request_id then tp_arrived() end -- QQT_Warpigz_v3 1.0.24
        if tracker.return_required and raven_handoff() then return end -- QQT_Warpigz_v3
        task.baseExecute()
    end
end

return task
