-- Generated by tools/build-rosie.mjs; edit the reviewed source or transform.
local BatmobilePlugin=nil -- Rosie owns native movement.
local plugin_label = 'alfred_the_butler'

local utils = require 'rosie.private.town.core.utils'
local settings = require 'rosie.private.town.core.settings'
local tracker = require 'rosie.private.town.core.tracker'
local explorerlite = require 'rosie.private.town.core.explorerlite'
local base_task = require 'rosie.private.town.tasks.base'
local lifecycle = require 'rosie.private.town.core.lifecycle'
local town_movement = require 'rosie.private.town.core.town_movement'
local pathfinder = require('rosie.movement').for_owner('town') -- QQT_Warpigz_v3

local task = base_task.new_task()
local status_enum = {
    IDLE = 'Idle',
    WAITING = 'Waiting ',
    EXECUTE = 'Teleporting',
    MOVING = 'Moving to portal',
    INTERACTING = 'Interacting with portal',
    RESETTING = 'Re-trying teleport',
    FAILED = 'Failed to teleport'
}
local debounce_time = -1
local debounce_timeout = 3
local outbound_attempts = 0
local outbound = false
local reset_session = task.reset_session
function task.reset_session()
    reset_session(); debounce_time=-1; outbound_attempts=0; outbound=false
end
local function teleport_with_debounce()
    local local_player = get_local_player()
    if not local_player or local_player:is_dead() then return end
    if local_player:get_active_spell_id() == 186139 then
        task.set_status(status_enum['EXECUTE'])
    else
        local status = status_enum['WAITING'] ..
        string.format("%.2f", debounce_time + debounce_timeout - get_time_since_inject()) .. 's'
        task.set_status(status)
    end
    if debounce_time + debounce_timeout > get_time_since_inject() then return end
    if outbound_attempts>=8 then return end
    outbound_attempts=outbound_attempts+1
    debounce_time = get_time_since_inject()
    teleport_to_waypoint(utils.get_town().waypoint_sno)
    task.set_status(status_enum['EXECUTE'])
end
local extension = {}
function extension.get_npc()
    return utils.get_npc(utils.npc_enum['PORTAL'])
end
function extension.move()
    if utils.player_in_zone('[sno none]') then return end
    local npc_location = town_movement.target('PORTAL')
    if not npc_location then return false end
    if BatmobilePlugin then
        BatmobilePlugin.set_target(plugin_label, npc_location)
        BatmobilePlugin.move(plugin_label)
    else
        explorerlite:set_custom_target(npc_location)
        explorerlite:move_to_target()
    end
end
function extension.interact()
    local npc = extension.get_npc()
    if npc then interact_object(npc) end
end
function extension.execute()
    local npc = extension.get_npc()
    if npc then interact_object(npc) end
end

function extension.reset()
    local local_player = get_local_player()
    if not local_player then return end
    local resets = utils.get_town().reset_positions
    local new_position = resets.default
    if tracker.last_task == 'stash' then
        new_position = resets.stash
    elseif tracker.last_task == 'salvage' then
        new_position = resets.salvage
    elseif tracker.last_task ==  'sell' or tracker.last_task == 'gamble' then
        new_position = resets.sell_gamble
    end
    if BatmobilePlugin then
        BatmobilePlugin.set_target(plugin_label, new_position)
        BatmobilePlugin.move(plugin_label)
    else
        explorerlite:set_custom_target(new_position)
        explorerlite:move_to_target()
    end
end
function extension.is_done()
    return lifecycle.returned()
end
function extension.done()
    if BatmobilePlugin then
        BatmobilePlugin.clear_target(plugin_label)
    end
    tracker.teleport_done = true
end
function extension.failed()
    if BatmobilePlugin then
        BatmobilePlugin.clear_target(plugin_label)
    end
    tracker.teleport_failed = true
end
function extension.is_in_vendor_screen() return false end

-- QQT_Warpigz_v3: while any trip runs, SilentRaven's auto-fire holds on
-- 'alfred_busy', and a standalone activity may never stand in Temis
-- otherwise. Once per trip, after every service and before the walk to the
-- return portal, Rosie stops moving and queues the Whisper claim (only when
-- SilentRaven is enabled, takes the hand-off (auto-fire on standalone, or
-- WarPigs delegating: QQT_Warpigz_v3 Q8), a reward ready and not
-- yet claimed this visit), then waits for its callback: at most RAVEN_WAIT
-- seconds, which are not service time (lifecycle.tick, tracker.raven_wait).
local RAVEN_WAIT = 100
local raven = {request = nil, done = true, since = nil}
-- QQT_Warpigz_v3 (Q8): SilentRaven publishes whether it takes the hand-off
-- (`handoff`: its auto-fire standalone, WarPigs' delegation when WarPigs
-- manages Whispers; the night run skipped every managed SilentRaven
-- silently). An older SilentRaven without the field keeps the standalone
-- rule. A ready reward that is not handed over names why (once per trip).
local function raven_plugin()
    local p = rawget(_G, 'SilentRavenPlugin')
    if type(p) ~= 'table' or type(p.get_status) ~= 'function' or type(p.trigger_tasks) ~= 'function' then return nil end
    local ok, s = pcall(p.get_status)
    if not ok or type(s) ~= 'table' or s.enabled ~= true or s.ready ~= true then return nil end
    local consent = s.handoff
    if consent == nil then consent = s.auto_fire == true and s.managed_by == nil end
    local why = (consent ~= true and tostring(s.handoff_reason or 'SilentRaven auto-fire is off or it is managed'))
        or ((s.running == true or s.pending == true) and 'SilentRaven already has a request')
        or (s.paused == true and 'SilentRaven is paused')
        or (s.last_zone_handled == 'Skov_Temis' and 'this Temis visit is already handled') or nil
    if why then return nil, why end
    return p
end
local function raven_finish(message)
    raven.done, tracker.raven_wait = true, nil
    if message then console.print('[Rosie] ' .. message) end
    return false
end
-- True while Rosie waits for SilentRaven (the teleport task does nothing else).
local function raven_handoff()
    local id = tracker.request_id
    if raven.request ~= id then
        raven.request, raven.done, raven.since = id, true, nil
        local p, skip = raven_plugin()
        if not p then
            if skip then console.print('[Rosie] no SilentRaven hand-off: ' .. skip) end -- QQT_Warpigz_v3 (Q8)
            return false
        end
        pathfinder.clear_stored_path()
        local ok, accepted, why = pcall(p.trigger_tasks, settings.plugin_label, function(result)
            if raven.request == id and not raven.done then
                raven_finish('SilentRaven finished (' .. tostring(result) .. '); walking to the return portal')
            end
        end)
        if not ok or accepted ~= true then
            return raven_finish('SilentRaven hand-off refused: ' .. tostring(ok and why or accepted))
        end
        raven.done, raven.since, tracker.raven_wait = false, get_time_since_inject(), true
        console.print('[Rosie] waiting for SilentRaven to claim the Whisper reward before the return portal')
    end
    if raven.done then
        -- The walk to the portal starts from a clean approach state.
        if raven.since then raven.since = nil; task.reset_session() end
        return false
    end
    if get_time_since_inject() - raven.since >= RAVEN_WAIT then
        local p = rawget(_G, 'SilentRavenPlugin')
        if type(p) == 'table' and type(p.cancel) == 'function' then pcall(p.cancel, settings.plugin_label) end
        raven_finish(string.format('SilentRaven did not finish within %ds; walking to the return portal', RAVEN_WAIT))
        raven.since = nil; task.reset_session()
        return false
    end
    task.set_status('Waiting for SilentRaven')
    task.suspend()
    return true
end

task.name = 'teleport'
task.extension = extension
task.status_enum = status_enum
task.max_retries = 5
task.teleport_time = nil

task.shouldExecute = function ()
    if tracker.teleport_done or tracker.teleport_failed then return false end
    -- QQT_Warpigz_v3: a request from another town has no return leg, only
    -- the outbound hop to Temis (until the first town visit).
    if not tracker.return_required and not (tracker.teleport and not tracker.visited_town) then return false end
    if tracker.trigger_tasks == false then
        task.retry = 0
    end
    if tracker.teleport and not utils.is_in_town()
    then
        return true
    elseif utils.is_in_town() and
        tracker.trigger_tasks and
        not tracker.teleport_failed and
        not tracker.teleport_done and
        (tracker.sell_done or tracker.sell_failed) and
        (tracker.salvage_done or tracker.salvage_failed) and
        (tracker.repair_done or tracker.repair_failed) and
        (tracker.stash_done or tracker.stash_failed) and
        (tracker.salvage_talisman_done or tracker.salvage_talisman_failed) and
        (tracker.service_pulls==false or #(tracker.pending_pulls or {})==0 or tracker.stash_pull_done or tracker.stash_pull_failed)
    then
        if task.check_status(task.status_enum['FAILED']) then
            task.set_status(task.status_enum['IDLE'])
        end
        return true
    end
    return false
end
task.baseExecute = task.Execute
task.Execute = function ()
    local player=get_local_player()
    if not player or player:is_dead() or tracker.external_pause then return end
    if tracker.visited_town and not utils.is_in_town() then
        if not tracker.return_required then return end -- QQT_Warpigz_v3: no return leg
        if lifecycle.returned() then extension.done()
        elseif not utils.player_in_zone('[sno none]') then extension.failed() end
        return
    end
    if tracker.teleport and not utils.is_in_town() then
        if tracker.service_elapsed>=60 then extension.failed(); return end
        outbound=true
        task.retry = 0
        lifecycle.hold_peers()
        teleport_with_debounce()
    else
        if outbound then reset_session(); outbound=false end
        if tracker.return_required and raven_handoff() then return end -- QQT_Warpigz_v3
        task.baseExecute()
    end
end

return task
