-- Generated by tools/build-rosie.mjs; edit the reviewed source or transform.
local native_tree=tree_node
local tree_node={new=function(_,depth) return native_tree:new(depth+1) end}
local plugin_label = 'alfred_the_butler'
local plugin_version = '1.0.6-local'
-- console.print("Lua Plugin - Rosie the Butler - Leoric - v" .. plugin_version)

local utils = require 'rosie.private.town.core.utils'
local town = require 'rosie.private.town.core.town'
local gui = {}
local previous=rawget(_G,'AlfredTheButlerPlugin')
local cached=type(previous)=='table' and previous._gui

gui.town_options = town.options

local affix_types = utils.get_item_affixes()
local item_aspects = utils.get_item_aspects()
local unique_items = utils.get_unique_items()
local legacy_unique_items = utils.get_legacy_unique_items()
local mythic_items = utils.get_mythic_items()
local unique_charm_items = utils.get_unique_charm_items()
local mythic_seal_items  = utils.get_mythic_seal_items()
local set_charm_items    = utils.get_set_charm_items()

local function create_checkbox(value, key)
    return checkbox:new(value, get_hash(plugin_label .. '_' .. key))
end

local function add_tree(name)
    local tree_name = tostring(name)
    tree_name = tree_name .. '_tree'
    gui.elements[tree_name] = tree_node:new(2)
end

local function add_checkbox(name, data, default)
    for _,item in pairs(data) do
        local checkbox_name = tostring(name)
        checkbox_name = checkbox_name .. '_' .. tostring(item.sno_id)
        if not gui.elements[checkbox_name] then gui.elements[checkbox_name] = create_checkbox(default, checkbox_name) end
    end
end

local function add_search(name)
    local search_name = tostring(name)
    search_name = search_name .. '_search'
    if not gui.elements[search_name] then gui.elements[search_name] = input_text:new(get_hash(plugin_label .. tostring(name) .. '_search_input')) end
    local scope_name=tostring(name)..'_scope'
    if not gui.elements[scope_name] then gui.elements[scope_name]=combo_box:new(0,get_hash(plugin_label..'_'..scope_name)) end
end

local function render_checkbox(name,data, show_item_type)
    local search_name = tostring(name)..'_search'
    local search_string=string.lower(gui.elements[search_name]:get())
    local character_class=utils.get_character_class()
    local scope=gui.elements[tostring(name)..'_scope']
    scope:render('Show',{'Current class + selected','All classes','Selected only'},'Selected choices stay visible even when searching or playing a different class.')
    local shown,selected,total=0,0,0
    for _,item in pairs(data) do
        total=total+1
        local checked=gui.elements[tostring(name)..'_'..tostring(item.sno_id)]:get()
        if checked then selected=selected+1 end
        local item_name = item.name
        if show_item_type and item.item_type then
            item_name = item.name .. ' - ' .. item.item_type
        end
        local visible=false
        for _,class in pairs(item.class) do
            if string.lower(class)=='all' or string.lower(class)==character_class then visible=true end
        end
        visible=checked or scope:get()==1 or scope:get()~=2 and visible
        if visible then
            local checkbox_name=tostring(name)..'_'..tostring(item.sno_id)
            local searchable=string.lower(table.concat({item_name,item.item_type or '',item.description or '',
                table.concat(item.class,' '),item.set or '',tostring(item.sno_id)},' '))
            if search_string=='' or searchable:find(search_string,1,true) or gui.elements[checkbox_name]:get() then
                gui.elements[checkbox_name]:render(item_name,(item.description or item_name)..
                    ' | '..table.concat(item.class,', ')..' | Item ID: '..tostring(item.sno_id))
                shown=shown+1
            end
        end
    end
    render_menu_header(string.format('%d shown / %d total; %d selected. Selected choices stay visible.',shown,total,selected))
    if shown==0 then render_menu_header('No matching items. Clear the search or choose All classes.') end
end

gui.plugin_label = plugin_label
gui.plugin_version = plugin_version

gui.stash_options = {
    'Inventory',
    'Stash'
}

gui.item_options = {
    'Keep',
    'Salvage',
    'Sell'
}

gui.stash_extra_options= {
    'Never',
    'When full',
    'Always',
}

gui.failed_options= {
    'Log',
    'Forced Retry',
}

gui.gamble_language= {
    'English',
    'Chinese',
    'Other'
}

gui.gamble_categories = {
    ['sorcerer'] = {'Cap', 'Whispering Key', 'Tunic', 'Gloves', 'Boots', 'Pants', 'Amulet', 'Ring', 'Sword', 'Mace', 'Dagger', 'Staff', 'Wand', 'Focus'},
    ['barbarian'] = {'Cap', 'Whispering Key', 'Tunic', 'Gloves', 'Boots', 'Pants', 'Amulet', 'Ring', 'Axe', 'Sword', 'Mace', 'Two-Handed Axe', 'Two-Handed Sword', 'Two-Handed Mace', 'Polearm'},
    ['rogue'] = {'Cap', 'Whispering Key', 'Tunic', 'Gloves', 'Boots', 'Pants', 'Amulet', 'Ring', 'Sword', 'Dagger', 'Bow', 'Crossbow'},
    ['druid'] = {'Cap', 'Whispering Key', 'Tunic', 'Gloves', 'Boots', 'Pants', 'Amulet', 'Ring', 'Axe', 'Sword', 'Mace', 'Two-Handed Axe', 'Two-Handed Mace', 'Polearm', 'Dagger', 'Staff', 'Totem'},
    ['necromancer'] = {'Cap', 'Whispering Key', 'Tunic', 'Gloves', 'Boots', 'Pants', 'Amulet', 'Ring', 'Axe', 'Sword', 'Mace', 'Two-Handed Axe', 'Two-Handed Sword', 'Scythe', 'Two-Handed Mace', 'Two-Handed Scythe', 'Dagger', 'Shield', 'Wand', 'Focus'},
    ['spiritborn'] = {'Quarterstaff', 'Cap', 'Whispering Key', 'Tunic', 'Gloves', 'Boots', 'Pants', 'Amulet', 'Ring', 'Polearm', 'Glaive'},
    ['paladin'] = {"Cap", "Whispering Key", "Tunic", "Gloves", "Boots", "Pants", "Amulet", "Ring", "Axe", "Sword", "Mace", "Shield", "Flail", "Two-Handed Axe", "Two-Handed Sword", "Two-Handed Mace"},
    ['default'] = {'CLASS NOT LOADED'}
}

gui.gamble_categories_chinese = {
    ['sorcerer'] = {"è½¯å¸½", "ä½Žè¯­é’¥åŒ™", "çŸ­è¡£", "æ‰‹å¥—", "é´å­", "è£¤å­", "æŠ¤ç¬¦", "æˆ’æŒ‡", "å‰‘", "é’‰é”¤", "åŒ•é¦–", "æ–", "é­”æ–", "èšèƒ½å™¨"},
    ['barbarian'] = {"è½¯å¸½", "ä½Žè¯­é’¥åŒ™", "çŸ­è¡£", "æ‰‹å¥—", "é´å­", "è£¤å­", "æŠ¤ç¬¦", "æˆ’æŒ‡", "æ–§", "å‰‘", "é’‰é”¤", "åŒæ‰‹æ–§", "åŒæ‰‹å‰‘", "åŒæ‰‹é’‰é”¤", "é•¿æŸ„æ­¦å™¨"},
    ['rogue'] = {"è½¯å¸½", "ä½Žè¯­é’¥åŒ™", "çŸ­è¡£", "æ‰‹å¥—", "é´å­", "è£¤å­", "æŠ¤ç¬¦", "æˆ’æŒ‡", "å‰‘", "åŒ•é¦–", "å¼“", "å¼©"},
    ['druid'] = {"è½¯å¸½", "ä½Žè¯­é’¥åŒ™", "çŸ­è¡£", "æ‰‹å¥—", "é´å­", "è£¤å­", "æŠ¤ç¬¦", "æˆ’æŒ‡", "æ–§", "å‰‘", "é’‰é”¤", "åŒæ‰‹æ–§", "åŒæ‰‹é’‰é”¤", "é•¿æŸ„æ­¦å™¨", "åŒ•é¦–", "æ–", "å›¾è…¾"},
    ['necromancer'] = {"è½¯å¸½", "ä½Žè¯­é’¥åŒ™", "çŸ­è¡£", "æ‰‹å¥—", "é´å­", "è£¤å­", "æŠ¤ç¬¦", "æˆ’æŒ‡", "æ–§", "å‰‘", "é’‰é”¤", "åŒæ‰‹æ–§", "åŒæ‰‹å‰‘", "é•°åˆ€", "åŒæ‰‹é’‰é”¤", "åŒæ‰‹é•°åˆ€", "åŒ•é¦–", "ç›¾ç‰Œ", "é­”æ–", "èšèƒ½å™¨"},
    ['spiritborn'] = {"é•¿æ–", "è½¯å¸½", "ä½Žè¯­é’¥åŒ™", "çŸ­è¡£", "æ‰‹å¥—", "é´å­", "è£¤å­", "æŠ¤ç¬¦", "æˆ’æŒ‡", "é•¿æŸ„æ­¦å™¨", "å‰‘åˆƒæˆŸ"},
    ['paladin'] = {"è½¯å¸½", "ä½Žè¯­é’¥åŒ™", "çŸ­è¡£", "æ‰‹å¥—", "é´å­", "è£¤å­", "æŠ¤ç¬¦", "æˆ’æŒ‡", "æ–§", "å‰‘", "é’‰é”¤", "ç›¾", "è¿žæž·", "åŒæ‰‹æ–§", "åŒæ‰‹å‰‘", "åŒæ‰‹é’‰é”¤"},
    ['default'] = {"CLASS NOT LOADED"}
}

gui.elements = cached and cached.elements or {
    main_tree = tree_node:new(0),
    main_toggle = create_checkbox(true, 'main_toggle'),
    run_service = button:new(get_hash(plugin_label .. '_run_service')),

    use_keybind = create_checkbox(false, 'use_keybind'),
    keybind_toggle = keybind:new(0x0A, true, get_hash(plugin_label .. '_keybind_toggle' )),
    export_keybind_toggle = keybind:new(0x0A, true, get_hash(plugin_label .. '_export_keybind_toggle' )),
    dump_keybind = keybind:new(0x0A, true, get_hash(plugin_label .. '_dump_keybind')),
    manual_keybind = keybind:new(0x0A, true, get_hash(plugin_label .. '_manual_keybind')),

    item_tree = tree_node:new(1),
    item_legendary_or_lower = combo_box:new(1, get_hash(plugin_label .. '_item_legendary_or_lower')),
    item_unique = combo_box:new(2, get_hash(plugin_label .. '_item_unique')),
    item_junk = combo_box:new(1, get_hash(plugin_label .. '_item_junk')),

    ancestral_item_tree = tree_node:new(1),
    ancestral_item_legendary = combo_box:new(1, get_hash(plugin_label .. '_ancestral_item_legendary')),
    ancestral_item_unique = combo_box:new(1, get_hash(plugin_label .. '_ancestral_item_unique')),
    ancestral_item_junk = combo_box:new(1, get_hash(plugin_label .. '_ancestral_item_junk')),
    ancestral_item_mythic = combo_box:new(0, get_hash(plugin_label .. '_ancestral_item_mythic')),
    -- QQT_Warpigz_v2 local patch: the old WarPigz Alfred's key and default (on).
    mythic_always_keep = create_checkbox(true, 'mythic_always_keep'),
    ancestral_keep_max_aspect_toggle = create_checkbox(true, 'max_aspect'),
    ancestral_aspect_filter_toggle = create_checkbox(false, 'aspect_filter'),
    ancestral_ga_count_slider = slider_int:new(0, 4, 1, get_hash(plugin_label .. '_ga_slider')),
    ancestral_unique_ga_count_slider = slider_int:new(0, 4, 1, get_hash(plugin_label .. '_unique_ga_slider')),
    ancestral_mythic_ga_count_slider = slider_int:new(0, 4, 1, get_hash(plugin_label .. '_mythic_ga_slider')),
    ancestral_filter_toggle = create_checkbox(false, 'use_filter'),
    ancestral_unique_filter_toggle = create_checkbox(false, 'use_unique_filter'),

    ancestral_affix_count_slider = slider_int:new(1, 4, 2, get_hash(plugin_label .. '_affix_slider')),

    affix_export_button = button:new(get_hash(plugin_label .. '_affix_export_button')),
    affix_import_button = button:new(get_hash(plugin_label .. '_affix_import_button')),
    affix_import_name = input_text:new(get_hash(plugin_label .. '_affix_import_name')),

    socketable_tree = tree_node:new(1),
    stash_socketables = combo_box:new(0, get_hash(plugin_label .. '_stash_socketables')),

    consumeable_tree = tree_node:new(1),
    stash_consumables = combo_box:new(0, get_hash(plugin_label .. '_stash_consumables')),

    key_tree = tree_node:new(1),
    stash_keys = combo_box:new(0, get_hash(plugin_label .. '_stash_keys')),
    stash_sigils = create_checkbox(false, 'stash_sigils'),
    salvage_sigils = create_checkbox(false, 'salvage_sigils'),

    gamble_tree = tree_node:new(1),
    gamble_toggle = create_checkbox(false, 'gamble_toggle'),
    gamble_language = combo_box:new(0, get_hash(plugin_label .. '_gamble_language')),
    gamble_non_english = input_text:new(get_hash(plugin_label .. '_gamble_custom_text')),
    gamble_threshold = slider_int:new(10, 2580, 1000, get_hash(plugin_label .. '_gamble_threshold')),
    gamble_category = {
        ['sorcerer'] = combo_box:new(0, get_hash(plugin_label .. '_gamble_sorcerer_category')),
        ['barbarian'] = combo_box:new(0, get_hash(plugin_label .. '_gamble_barbarian_category')),
        ['rogue'] = combo_box:new(0, get_hash(plugin_label .. '_gamble_rogue_category')),
        ['druid'] = combo_box:new(0, get_hash(plugin_label .. '_gamble_druid_category')),
        ['necromancer'] = combo_box:new(0, get_hash(plugin_label .. '_gamble_necromancer_category')),
        ['spiritborn'] = combo_box:new(0, get_hash(plugin_label .. '_gamble_spiritborn_category')),
        ['paladin'] = combo_box:new(0, get_hash(plugin_label .. '_gamble_paladin_category')),
        ['default'] = combo_box:new(0, get_hash(plugin_label .. '_gamble_default_category')),
    },

    loot_filter_tree      = tree_node:new(1),
    loot_filter_toggle    = create_checkbox(false, 'loot_filter_mode'),
    loot_filter_equipment = create_checkbox(false, 'loot_filter_equipment'),
    loot_filter_seal  = create_checkbox(false, 'loot_filter_seal'),
    loot_filter_charm = create_checkbox(false, 'loot_filter_charm'),

    general_tree = tree_node:new(1),
    town_choice = combo_box:new(0, get_hash(plugin_label .. '_town_choice_v2')),
    explorer_path_angle_slider = slider_int:new(0, 360, 10, get_hash(plugin_label .. '_explorer_path_angle_slider')),
    max_inventory = slider_int:new(20,33, 25, get_hash(plugin_label .. '_max_inventory')),
    max_stash_items = slider_int:new(1, 350, 350, get_hash(plugin_label .. '_max_stash_items')),
    failed_action = combo_box:new(0, get_hash(plugin_label .. '_failed_action')),
    skip_cache = create_checkbox(false, 'skip_cache'),
    skip_favorite = create_checkbox(false, 'skip_favorite'),

    drawing_tree = tree_node:new(1),
    draw_status = create_checkbox(true, 'draw_status'),
    draw_status_offset_x = slider_int:new(0, 1200, 0, get_hash(plugin_label .. "draw_status_offset_x")),
    draw_status_offset_y = slider_int:new(0, 600, 0, get_hash(plugin_label .. "draw_status_offset_y")),
    draw_stash = create_checkbox(false, 'draw_stash'),
    draw_sell = create_checkbox(false, 'draw_sell'),
    draw_salvage = create_checkbox(false, 'draw_salvage'),
    draw_box_space = slider_float:new(0, 1.0, 1.0, get_hash(plugin_label .. "draw_box_space")),
    draw_inventory_origin_x = slider_int:new(0, 4000, 1270, get_hash(plugin_label .. "draw_inventory_origin_x")),
    draw_inventory_origin_y = slider_int:new(0, 2500, 720,  get_hash(plugin_label .. "draw_inventory_origin_y")),
    draw_offset_x = slider_int:new(0, 150, 54, get_hash(plugin_label .. "draw_offset_x")),
    draw_offset_y = slider_int:new(0, 150, 75, get_hash(plugin_label .. "draw_offset_y")),
    draw_box_height = slider_int:new(0, 100, 79, get_hash(plugin_label .. "draw_box_height")),
    draw_box_width = slider_int:new(0, 100, 52, get_hash(plugin_label .. "draw_box_width")),

    seperator = combo_box:new(0, get_hash(plugin_label .. '_seperator')),

    talisman_seal_tree  = tree_node:new(1),
    talisman_charm_tree = tree_node:new(1),

    talisman_seal_action              = combo_box:new(1, get_hash(plugin_label .. '_talisman_seal_action')),
    talisman_seal_affix_filter_toggle = create_checkbox(false, 'talisman_seal_affix_filter'),
    talisman_seal_affix_count_slider  = slider_int:new(1, 4, 1, get_hash(plugin_label .. '_talisman_seal_affix_count')),
    talisman_charm_action              = combo_box:new(1, get_hash(plugin_label .. '_talisman_charm_action')),
    talisman_charm_affix_filter_toggle = create_checkbox(false, 'talisman_charm_affix_filter'),
    talisman_charm_affix_count_slider  = slider_int:new(1, 4, 1, get_hash(plugin_label .. '_talisman_charm_affix_count')),
    talisman_charm_unique_filter_toggle = create_checkbox(false, 'talisman_charm_unique_filter'),
    talisman_charm_set_filter_toggle    = create_checkbox(false, 'talisman_charm_set_filter'),
    talisman_seal_mythic_filter_toggle  = create_checkbox(false, 'talisman_seal_mythic_filter'),
    talisman_tab_x             = slider_int:new(0, 3840, 1466, get_hash(plugin_label .. '_talisman_tab_x')),
    talisman_tab_y             = slider_int:new(0, 2160, 650,  get_hash(plugin_label .. '_talisman_tab_y')),
}

if cached then
    -- Preserve settings widgets, but renew native presentation containers after
    -- refresh. The retired GUI must not supply this generation's tree handles.
    local elements={}
    for key,value in pairs(gui.elements) do elements[key]=value end
    gui.elements=elements
    local depths={main_tree=0,item_tree=1,ancestral_item_tree=1,socketable_tree=1,
        consumeable_tree=1,key_tree=1,gamble_tree=1,loot_filter_tree=1,general_tree=1,
        drawing_tree=1,talisman_seal_tree=1,talisman_charm_tree=1}
    for key,depth in pairs(depths) do gui.elements[key]=tree_node:new(depth) end
end

gui.elements.stop_service=gui.elements.stop_service or button:new(get_hash(plugin_label..'_stop_service'))

for _,affix_type in pairs(affix_types) do
    local name = affix_type.name .. '_affix'
    add_tree(name)
    add_checkbox(name, affix_type.data, false)
    add_search(name)
end
add_tree('aspect')
add_checkbox('aspect', item_aspects, false)
add_search('aspect')
add_tree('unique')
add_checkbox('unique', legacy_unique_items, false)
add_checkbox('unique', unique_items, false)
add_search('unique')
add_tree('mythic')
add_checkbox('mythic', mythic_items, true)
add_search('mythic')
-- Preserve a checked keep choice made in the former duplicate Unique picker,
-- then leave one visible, editable control for that exact SNO.
for _,item in ipairs(mythic_items) do
    local old=gui.elements['unique_'..tostring(item.sno_id)]
    local current=gui.elements['mythic_'..tostring(item.sno_id)]
    if old and old~=current and old:get() then current:set(true); old:set(false) end
end
add_tree('charm_unique')
add_checkbox('charm_unique', unique_charm_items, false)
add_search('charm_unique')
add_tree('charm_set')
add_checkbox('charm_set', set_charm_items, false)
add_search('charm_set')
add_tree('seal_mythic')
add_checkbox('seal_mythic', mythic_seal_items, false)
add_search('seal_mythic')
local menu_stack = {}
local menu_error
local function push_tree(node, label)
    if not node:push(label) then return false end
    menu_stack[#menu_stack+1] = node
    return true
end
local function pop_tree(node)
    node:pop()
    menu_stack[#menu_stack] = nil
end
local function render_settings()
    if not push_tree(gui.elements.main_tree, 'Keep, storage & town') then return false end
    gui.elements.main_toggle:render('Enable town service','Allow automatic and requested service when Rosie is enabled.')
    if push_tree(gui.elements.general_tree, 'General settings') then
        gui.elements.town_choice:render('Home town', gui.town_options, 'Which town Rosie runs his errands in')
        gui.elements.use_keybind:render('Use automatic-service keybind', 'Gate automatic town trips with a keybind. Pickup and Run town service remain available; use Enable Rosie to stop the whole product.')
        if gui.elements.use_keybind:get() then
            gui.elements.keybind_toggle:render('Automatic town service', 'Allow or pause new automatic town trips. An accepted trip finishes; the Rosie master switch cancels all work.')
            gui.elements.dump_keybind:render('Dump tracker info', 'Dump all tracker info to log')
            gui.elements.manual_keybind:render('Run town service keybind', 'Start an explicit town trip, including the pending stash-pull queue, while Rosie and town service are enabled.')
            render_menu_header('Assign distinct keys. Manual service and diagnostics ignore unassigned or conflicting keys, and pause while typing in chat.')
        end
        render_menu_header('Leave bag space for the next drops. A threshold of 25 reserves 8 equipment slots in a 33-slot bag.')
        gui.elements.max_inventory:render("Max inventory items", "No. of items in inventory to trigger Rosie tasks")
        gui.elements.max_stash_items:render("Max stash items", "Rosie stops stashing when the observed stash reaches this configured limit")
        render_menu_header('Town actions retry briefly. If a trip fails, correct the reported cause and use Run town service.')
        gui.elements.skip_cache:render('Skip stashing cache', 'Keep caches in inventory')
        if gui.elements.skip_cache:get() then
            render_menu_header('If retained caches leave the bag full, Rosie reports the unresolved need and waits for Run town service.')
        end
        gui.elements.skip_favorite:render('Skip favorited items', 'When enabled, favorited (locked) items are ignored by all Rosie operations — not sold, salvaged, or stashed')
        pop_tree(gui.elements.general_tree)
    end
    if push_tree(gui.elements.loot_filter_tree, '[In-game Loot Filter]') then
        gui.elements.loot_filter_toggle:render('Enable (Universal)', 'Use the in-game filter for equipment, seals and charms. Protected or unreadable items are retained.')
        if gui.elements.loot_filter_toggle:get() then
            render_menu_header('Rejected equipment is salvaged. Rejected seals and charms follow their category action. Accepted or unreadable items are kept; locks remain protected.')
        end
        gui.elements.loot_filter_equipment:render('Enable (Equipment Only)', 'Use in-game loot filter for armor/weapons/jewelry. Ignored if Universal is on.')
        gui.elements.loot_filter_seal:render('Enable (Seals Only)', 'Use in-game loot filter for seals. Ignored if Universal is on.')
        gui.elements.loot_filter_charm:render('Enable (Charms Only)', 'Use in-game loot filter for charms. Ignored if Universal is on.')
        if (gui.elements.loot_filter_equipment:get() or gui.elements.loot_filter_seal:get() or gui.elements.loot_filter_charm:get()) and not gui.elements.loot_filter_toggle:get() then
            render_menu_header('Selective mode: loot filter applies to checked categories. Everything else uses Rosie\'s normal rules.')
        end
        pop_tree(gui.elements.loot_filter_tree)
    end
    if push_tree(gui.elements.drawing_tree, 'Display settings') then
        gui.elements.draw_stash:render('Draw Keep items', 'Draw blue box around items that Rosie will keep/stash')
        if gui.elements.draw_stash:get() then
            render_menu_header('Items to keep/stash are drawn with blue box')
        end
        gui.elements.draw_salvage:render('Draw Salvage items', 'Draw orange box around items that Rosie will salvage')
        if gui.elements.draw_salvage:get() then
            render_menu_header('Items to salvage are drawn with orange box')
        end
        gui.elements.draw_sell:render('Draw Sell items', 'Draw pink box around items that Rosie will sell')
        if gui.elements.draw_sell:get() then
            render_menu_header('Items to sell are drawn with pink box')
        end
        gui.elements.draw_inventory_origin_x:render("Inventory Origin X", "X pixel of the top-left inventory slot — open inventory and align until box overlaps slot 0,0")
        gui.elements.draw_inventory_origin_y:render("Inventory Origin Y", "Y pixel of the top-left inventory slot")
        gui.elements.draw_offset_x:render("Slot Width", "Pixel distance between inventory columns")
        gui.elements.draw_offset_y:render("Slot Height", "Pixel distance between inventory rows")
        gui.elements.draw_box_height:render("Box Height", "Height of the colored item box")
        gui.elements.draw_box_width:render("Box Width", "Width of the colored item box")
        pop_tree(gui.elements.drawing_tree)
    end
    if push_tree(gui.elements.item_tree, 'Non-Ancestral') then
        render_menu_header('Select the default action for the following item types for non-ancestral items')
        gui.elements.item_unique:render('unique items', gui.item_options, 'Select what to do with non-ancestral unique items')
        gui.elements.item_legendary_or_lower:render('Common / Magic / Rare / Legendary', gui.item_options, 'Default action for non-ancestral common, magic, rare and legendary equipment, including crafting bases. Keep preserves them.')
        gui.elements.item_junk:render('junk items', gui.item_options, 'Select what to do with junk items')
        pop_tree(gui.elements.item_tree)
    end
    if push_tree(gui.elements.ancestral_item_tree, 'Ancestral') then
        render_menu_header('Select the default action for the following item types for ancestral items')
        gui.elements.mythic_always_keep:render('Always keep mythics', 'Mythic items, charms and seals are never sold or salvaged. Overrides every other rule, loot filter and junk mark included. Off: mythics follow the mythic rules below (never the loot filter or junk action).')
        gui.elements.ancestral_item_mythic:render('mythic items', gui.item_options, 'Select what to do with mythic items')
        gui.elements.ancestral_item_unique:render('unique items', gui.item_options, 'Select what to do with unique items')
        gui.elements.ancestral_item_legendary:render('Common / Magic / Rare / Legendary', gui.item_options, 'Default action for ancestral common, magic, rare and legendary equipment, including crafting bases, when no keep override applies.')
        gui.elements.ancestral_item_junk:render('junk items', gui.item_options, 'Select what to do with junk items')
        render_menu_header('Select the number of greater affixes on items you want to keep (override the default actions above to keep)')
        gui.elements.ancestral_mythic_ga_count_slider:render('Mythic Greater Affix', 'Minimum greater affixes to keep a mythic. 0 disables this override.')
        gui.elements.ancestral_unique_ga_count_slider:render('Unique Greater Affix', 'Minimum greater affixes to keep an ancestral unique. 0 disables this override.')
        gui.elements.ancestral_ga_count_slider:render('Non-Unique/Non-Mythic Min GA to Keep', 'Items with this many or more GAs are kept regardless of default action. 0 = disabled.')
        gui.elements.ancestral_filter_toggle:render('Use affix filter', 'Sub-filter within GA gate: also require matching affixes to keep')
        if gui.elements.ancestral_filter_toggle:get() then
            render_menu_header('Item keeps only if GA gate passes AND it has >= N of your checked affixes')
            gui.elements.ancestral_affix_count_slider:render('Min matching affixes', 'How many checked affixes must be present')
            for _, affix_type in pairs(affix_types) do
                if not affix_type.name:match('talisman') then
                    local name = affix_type.name .. '_affix'
                    if push_tree(gui.elements[name .. '_tree'], affix_type.name) then
                        gui.elements[name .. '_search']:render('Search', 'Filter by name', false, '', '')
                        render_checkbox(name, affix_type.data, false)
                        pop_tree(gui.elements[name .. '_tree'])
                    end
                end
            end
        end
        gui.elements.ancestral_unique_filter_toggle:render('Use unique/mythic filter', 'Checked ancestral uniques and mythics are kept. Unchecked items still use the GA override and default action above.')
        if gui.elements.ancestral_unique_filter_toggle:get() then
            render_menu_header('Check the uniques/mythics you want to keep. Unchecked items use the GA override and default action above.')
            if push_tree(gui.elements['unique_tree'], 'Unique items') then
                gui.elements['unique_search']:render('Search', 'Current class: search name, class, item type or item ID', false, '', '')
                render_checkbox('unique', unique_items, true)
                pop_tree(gui.elements['unique_tree'])
            end
            if push_tree(gui.elements['mythic_tree'], 'Mythic items') then
                gui.elements['mythic_search']:render('Search', 'Search name, class, item type or item ID', false, '', '')
                render_checkbox('mythic',mythic_items,true)
                pop_tree(gui.elements['mythic_tree'])
            end
        end
        pop_tree(gui.elements.ancestral_item_tree)
    end
    if push_tree(gui.elements.socketable_tree, 'Socketables') then
        gui.elements.stash_socketables:render('Stash socketables', gui.stash_extra_options, 'Select when to stash socketables')
        if gui.elements.stash_socketables:get() == utils.stash_extra_enum['NEVER'] then
            render_menu_header('Never stash socketables')
        elseif gui.elements.stash_socketables:get() == utils.stash_extra_enum['FULL'] then
            render_menu_header('Stash all socketables when Rosie is stashing equipment if socketables inventory is full')
        elseif gui.elements.stash_socketables:get() == utils.stash_extra_enum['ALWAYS'] then
            render_menu_header('Stash all socketables when Rosie is stashing')
        end
        pop_tree(gui.elements.socketable_tree)
    end
    if push_tree(gui.elements.consumeable_tree, 'Consumables') then
        gui.elements.stash_consumables:render('Stash consumables', gui.stash_extra_options, 'Select when to stash consumables')
        if gui.elements.stash_consumables:get() == utils.stash_extra_enum['NEVER'] then
            render_menu_header('Never stash consumables')
        elseif gui.elements.stash_consumables:get() == utils.stash_extra_enum['FULL'] then
            render_menu_header('Stash extra boss materials when Rosie is stashing equipment if consumables inventory is full')
        elseif gui.elements.stash_consumables:get() == utils.stash_extra_enum['ALWAYS'] then
            render_menu_header('Stash extra boss materials when Rosie is stashing')
        end
        pop_tree(gui.elements.consumeable_tree)
    end
    if push_tree(gui.elements.key_tree, 'Dungeon Keys') then
        gui.elements.stash_keys:render('Stash dungeon keys', gui.stash_extra_options, 'Select when to stash dungeon keys')
        gui.elements.stash_sigils:render('Stash Favourited sigils', 'stash favourited sigils')
        gui.elements.salvage_sigils:render('Salvage Non-Favourited sigils', 'salvage non-favourited sigils')
        if gui.elements.stash_keys:get() == utils.stash_extra_enum['NEVER'] then
            render_menu_header('Never stash dungeon keys')
        elseif gui.elements.stash_keys:get() == utils.stash_extra_enum['FULL'] then
            render_menu_header('Stash extra compasses and tributes when Rosie is stashing equipment if dungeon keys inventory is full')
        elseif gui.elements.stash_keys:get() == utils.stash_extra_enum['ALWAYS'] then
            render_menu_header('Stash extra compasses and tributes when Rosie is stashing')
        end
        pop_tree(gui.elements.key_tree)
    end
    if push_tree(gui.elements.talisman_seal_tree, 'Talisman (Seal)') then
        gui.elements.talisman_seal_action:render('Seal default action', {'Keep', 'Salvage', 'Sell'}, 'What to do with seals by default')
        gui.elements.talisman_seal_affix_filter_toggle:render('Use affix filter', 'Keep seals that have >= N of your checked affixes')
        if gui.elements.talisman_seal_affix_filter_toggle:get() then
            gui.elements.talisman_seal_affix_count_slider:render('Min matching affixes', 'How many checked seal affixes must match to keep')
            local name = 'talisman_seal_affix'
            if push_tree(gui.elements[name .. '_tree'], 'Seal Affixes') then
                gui.elements[name .. '_search']:render('Search', 'Filter by name', false, '', '')
                render_checkbox(name, (function()
                    for _, at in pairs(affix_types) do
                        if at.name == 'talisman_seal' then return at.data end
                    end
                    return {}
                end)(), false)
                pop_tree(gui.elements[name .. '_tree'])
            end
        end
        gui.elements.talisman_seal_mythic_filter_toggle:render('Use unique/mythic seal filter', 'When enabled, checked unique and mythic seals are kept; unchecked ones follow the seal action and affix rules. Filter off keeps all unique/mythic seals.')
        if gui.elements.talisman_seal_mythic_filter_toggle:get() then
            if push_tree(gui.elements['seal_mythic_tree'], 'Unique and Mythic Seals') then
                gui.elements['seal_mythic_search']:render('Search','Search name, class or item ID',false,'','')
                render_checkbox('seal_mythic',mythic_seal_items,false)
                pop_tree(gui.elements['seal_mythic_tree'])
            end
        end
        pop_tree(gui.elements.talisman_seal_tree)
    end
    if push_tree(gui.elements.talisman_charm_tree, 'Talisman (Charm)') then
        gui.elements.talisman_charm_action:render('Charm default action', {'Keep', 'Salvage', 'Sell'}, 'What to do with charms by default')
        gui.elements.talisman_charm_affix_filter_toggle:render('Use affix filter', 'Keep charms that have >= N of your checked affixes')
        if gui.elements.talisman_charm_affix_filter_toggle:get() then
            gui.elements.talisman_charm_affix_count_slider:render('Min matching affixes', 'How many checked charm affixes must match to keep')
            local name = 'talisman_charm_affix'
            if push_tree(gui.elements[name .. '_tree'], 'Charm Affixes') then
                gui.elements[name .. '_search']:render('Search', 'Filter by name', false, '', '')
                render_checkbox(name, (function()
                    for _, at in pairs(affix_types) do
                        if at.name == 'talisman_charm' then return at.data end
                    end
                    return {}
                end)(), false)
                pop_tree(gui.elements[name .. '_tree'])
            end
        end
        gui.elements.talisman_charm_unique_filter_toggle:render('Use unique/mythic charm filter', 'When enabled, checked unique and mythic charms are kept; unchecked ones follow the charm action and affix rules. Filter off keeps all unique/mythic charms.')
        if gui.elements.talisman_charm_unique_filter_toggle:get() then
            if push_tree(gui.elements['charm_unique_tree'], 'Unique and Mythic Charms') then
                gui.elements['charm_unique_search']:render('Search', 'Filter by name or class', false, '', '')
                render_checkbox('charm_unique', unique_charm_items, false)
                pop_tree(gui.elements['charm_unique_tree'])
            end
        end
        gui.elements.talisman_charm_set_filter_toggle:render('Use set charm filter', 'Checked set charms are kept. When the charm affix filter is enabled, checked set charms must also meet its matching-affix requirement. Unchecked set charms follow Charm default action.')
        if gui.elements.talisman_charm_set_filter_toggle:get() then
            if push_tree(gui.elements['charm_set_tree'], 'Set Charms') then
                gui.elements['charm_set_search']:render('Search', 'Filter by name or set', false, '', '')
                render_checkbox('charm_set', set_charm_items, false)
                pop_tree(gui.elements['charm_set_tree'])
            end
        end
        pop_tree(gui.elements.talisman_charm_tree)
    end
    -- Gambling UI hidden pending API update
    -- if push_tree(gui.elements.gamble_tree, 'Gambling settings') then
    --     gui.elements.gamble_toggle:render('Enable gambling', 'enable gambling')
    --     if gui.elements.gamble_toggle:get() then
    --         render_menu_header('remember to disable gambling in piteer so that it doesnt clash')
    --     end
    --     gui.elements.gamble_threshold:render('Obols threshold', 'amount of obols before starting gambling')
    --     gui.elements.gamble_language:render('Language', gui.gamble_language, "Select your client language")
    --     if gui.gamble_language[gui.elements.gamble_language:get()+1] == 'English' then
    --         local class = utils.get_character_class()
    --         gui.elements.gamble_category[class]:render("Gamble Category", gui.gamble_categories[class], "Select the item category to gamble")
    --     elseif gui.gamble_language[gui.elements.gamble_language:get()+1] == 'Chinese' then
    --         local class = utils.get_character_class()
    --         gui.elements.gamble_category[class]:render("Gamble Category", gui.gamble_categories_chinese[class], "Select the item category to gamble")
    --     else
    --         render_menu_header('type in the gamble category including any spaces in between')
    --         gui.elements.gamble_non_english:render('Gamble category', 'type in the gamble category including any spaces in between', false, '', '')
    --     end
    --     pop_tree(gui.elements.gamble_tree)
    -- end

    -- if push_tree(gui.elements.gamble_tree, 'Gamble') then
    --     gui.elements.gamble_toggle:render('Gambling', 'Enable gambling items')
    --     pop_tree(gui.elements.gamble_tree)
    -- end
    pop_tree(gui.elements.main_tree)
    return true
end

-- A widget failure must not strand this addon's trees in the host's shared GUI.
-- Returning false also prevents main from consuming stale action-button state.
function gui.render()
    local ok, result = pcall(render_settings)
    for i=#menu_stack,1,-1 do
        local node = menu_stack[i]
        local popped, why = pcall(function() node:pop() end)
        menu_stack[i] = nil
        if not popped and ok then ok, result = false, why end
    end
    if not ok then
        gui.render_error=true
        local message = tostring(result)
        if menu_error ~= message then
            console.print('[Rosie] Settings error: ' .. message)
            menu_error = message
        end
        pcall(render_menu_header, 'Rosie settings could not be displayed. See the console for details.')
        return false
    end
    gui.render_error=false
    menu_error = nil
    return result == true
end

return gui
