-- Generated by tools/build-rosie.mjs; edit the reviewed source or transform.
local callbacks=require('rosie.runtime').callbacks('town')
local plugin_label = 'alfred_the_butler'

local gui          = require 'rosie.private.town.gui'
local utils        = require 'rosie.private.town.core.utils'
local settings     = require 'rosie.private.town.core.settings'
local task_manager = require 'rosie.private.town.core.task_manager'
local tracker      = require 'rosie.private.town.core.tracker'
local external     = require 'rosie.private.town.core.external'
local drawing      = require 'rosie.private.town.core.drawing'
local lifecycle    = require 'rosie.private.town.core.lifecycle'
local active = true
local previous = rawget(_G,'AlfredTheButlerPlugin')
if type(previous)=='table' and type(previous.shutdown)=='function' then previous.shutdown() end
if type(previous)=='table' and type(previous._take_cleanup)=='function' then lifecycle.adopt_cleanup(previous._take_cleanup()) end

local local_player
local debounce_time = nil
local debounce_timeout = 1
local keybind_data = type(previous)=='table' and previous._keybind_data or checkbox:new(false, get_hash(plugin_label .. '_keybind_data'))
if PERSISTENT_MODE ~= nil and PERSISTENT_MODE ~= false then
    gui.elements.keybind_toggle:set(keybind_data:get())
end

-- QQT_Warpigz_v3 3.3.1: a bag that needs town and why no trip starts, logged
-- once per reason (the old silence hid hours of farming with a full bag).
local DEFER_TOWN,DEFER_ANY=60,600
local need_since,wait_logged=nil,nil
local function auto_wait(why)
    if why==nil then
        if not tracker.need_trigger then need_since=nil end
        wait_logged=nil; return
    end
    if wait_logged==why then return end
    wait_logged=why
    console.print(string.format('[Rosie] Bag needs a town trip (bag %s/%s, talismans %s) but it waits: %s',
        tostring(tracker.inventory_count),tostring(settings.max_inventory),tostring(tracker.talisman_inventory_count),why))
end

-- QQT_Warpigz_v3 1.0.27 (contract C-boss, scenario sweep §2.4): an activity
-- that publishes boss_fight=true (WonderCity/Arkham get_status(), Reaper
-- status()) holds Rosie's automatic trip, at most BOSS.max s per fight (a
-- Town Portal cast in melee, glyph chances lost). Manual, keybind and farm
-- plugin requests are not held. Returns the activity's name while it holds.
local BOSS={max=90,since=nil,capped=false,list={{'WonderCityPlugin','get_status','WonderCity'},
    {'ArkhamAsylumPlugin','get_status','ArkhamAsylum'},{'ReaperPlugin','status','Reaper'}}}
local function boss_hold(now)
    local who=nil
    for _,p in ipairs(BOSS.list) do
        local api=rawget(_G,p[1])
        local fn=type(api)=='table' and api[p[2]]
        if type(fn)=='function' then
            local ok,st=pcall(fn)
            if ok and type(st)=='table' and st.boss_fight==true then who=p[3]; break end
        end
    end
    if not who then BOSS.since,BOSS.capped=nil,false; return nil end
    BOSS.since=BOSS.since or now
    if BOSS.capped then return nil end
    if now-BOSS.since<BOSS.max then return who end
    BOSS.capped=true
    console.print(string.format('[Rosie] %s has reported a live boss fight for %ds; starting the town trip',who,BOSS.max))
    return nil
end

local function update_locals()
    local_player = get_local_player()
end

local function main_pulse()
    if not lifecycle.retry_cleanup() then return end
    settings:update_settings()
    if PERSISTENT_MODE ~= nil and PERSISTENT_MODE ~= false  then
        if keybind_data:get() ~= (gui.elements.keybind_toggle:get_state() == 1) then
            keybind_data:set(gui.elements.keybind_toggle:get_state() == 1)
        end
    end

    if not settings.enabled then
        if lifecycle.busy() then lifecycle.cancel('Rosie town service disabled during service') end
        return
    end
    local world=get_current_world()
    if not local_player or local_player:is_dead()~=false or not world or world:get_current_zone_name()=='[sno none]' then
        task_manager.execute_tasks(); return
    end
    utils.update_tracker_count(local_player,lifecycle.busy())

    if settings.action_key_active(gui.elements.manual_keybind) then
        if debounce_time ~= nil and debounce_time + debounce_timeout > get_time_since_inject() then return end
        gui.elements.manual_keybind:set(false)
        debounce_time = get_time_since_inject()
        -- orbwalker.set_clear_toggle(false)
        -- QQT_Warpigz_v2: like the menu's Run town service, the keybind never
        -- clears another plugin's pause; a refusal is reported.
        if not lifecycle.busy() then
            local accepted,reason=lifecycle.request('manual',nil,true,true)
            if not accepted then console.print('[Rosie] Cannot start: '..tostring(reason)) end
        end
    end

    if settings.action_key_active(gui.elements.dump_keybind) then
        if debounce_time ~= nil and debounce_time + debounce_timeout > get_time_since_inject() then return end
        gui.elements.dump_keybind:set(false)
        debounce_time = get_time_since_inject()
        utils.dump_tracker_info(tracker)
    end

    if not (settings.get_keybind_state() or tracker.external_trigger or tracker.manual_trigger) then
        -- QQT_Warpigz_v3 1.0.22: only a bag that needs town logs this wait (a
        -- bag 3/30 logged it and latched it, so the real need later logged nothing).
        if tracker.need_trigger then auto_wait('automatic service is off (keybind toggle)') else auto_wait(nil) end
        return
    end

    if not lifecycle.busy() then
        if not tracker.need_trigger then auto_wait(nil)
        else
            -- QQT_Warpigz_v3 3.3.1: another activity owning the run, or a
            -- plugin's town pause, no longer holds a full bag forever (a
            -- Worldstone loop ran for hours with a full bag): after DEFER_TOWN
            -- s it is served the next time the player stands in a town (between
            -- runs), after DEFER_ANY s anywhere (never during a revive).
            local now=get_time_since_inject()
            need_since=need_since or now
            local waited=now-need_since
            local activity=rawget(_G,'TRISTRAM_LOOP_STATE')
            local ok,state=false,nil
            if type(activity)=='table' and type(activity.status)=='function' then ok,state=pcall(activity.status) end
            local owner=ok and type(state)=='table' and state.running and state.owns_activity and state
            local held=owner and 'another activity owns the run' or tracker.external_pause
                and ('paused by '..tostring(tracker.pause_caller or 'another plugin')) or nil
            -- QQT_Warpigz_v3 1.0.22: "never during a revive" is now at most
            -- REVIVE_LIMIT s of revive (lifecycle.revive_holds: one clock with the trip).
            local deferring=not (waited>=DEFER_ANY or waited>=DEFER_TOWN and lifecycle.in_any_town())
            local reviving=lifecycle.revive_holds(owner and owner.phase=='revive',now,held and deferring)
            if held and (reviving or deferring) then
                auto_wait(held)
                return
            end
            local boss=boss_hold(now) -- QQT_Warpigz_v3 1.0.27: C-boss
            if boss then auto_wait(boss..' is in a live boss fight'); return end
            if lifecycle.auto_blocked() then auto_wait('last trip '..tostring(tracker.outcome)..': '..tostring(tracker.failure_reason))
            else
                -- QQT_Warpigz_v3 1.0.22: the override is logged, and a foreign
                -- pause cleared, only for a trip that starts: it printed every
                -- pulse while the start was blocked or refused, and cleared the
                -- pause for nothing. A refused start restores the pause (the
                -- request refuses while it is set) and logs its reason once.
                local paused_by=tracker.pause_caller
                local cleared=held and tracker.external_pause and lifecycle.resume()
                local accepted,why=lifecycle.request('automatic',nil,true,true)
                if accepted then
                    if held then console.print(string.format('[Rosie] Bag needs a town trip for %ds (%s): starting it now',math.floor(waited),held)) end
                    need_since=nil; auto_wait(nil)
                else
                    if cleared and not tracker.external_pause then tracker.external_pause=true; tracker.pause_caller=paused_by end
                    auto_wait(tostring(why))
                end
            end
        end
    end
    task_manager.execute_tasks()
end

local function render_pulse()
    if not settings.enabled then return end
    if gui.elements.draw_status:get() then
        drawing.draw_status()
    end
    if gui.elements.draw_stash:get() or gui.elements.draw_sell:get() or gui.elements.draw_salvage:get() then
        drawing.draw_inventory_boxes()
    end
end

local last_idle_error=nil
callbacks.on_update(function()
    if not active then lifecycle.retry_cleanup(); return end
    update_locals()
    local ok,why=pcall(main_pulse)
    if not ok then
        local message='Host error: '..tostring(why)
        if lifecycle.busy() then lifecycle.finish(false,message)
        elseif last_idle_error~=message then console.print('[Rosie] '..message) end
        last_idle_error=message
    else
        last_idle_error=nil
    end
end)
callbacks.on_render_menu(function ()
    if not active then return end
    if not gui.render() then return end
    settings:update_settings()
    if not settings.enabled and lifecycle.busy() then lifecycle.cancel('Rosie town service disabled during service') end
    if not settings.enabled then gui.feedback=nil end
    if not gui.elements.main_toggle:get() then return end
    if lifecycle.busy() and gui.elements.stop_service:get() then
        lifecycle.cancel('Cancelled by user')
        gui.feedback=nil
        return
    end
    if not lifecycle.busy() and gui.elements.run_service:get() then
        local accepted,reason=lifecycle.request('manual',nil,true,true)
        gui.feedback=not accepted and 'Cannot start: '..tostring(reason) or nil
        if not accepted then console.print('[Rosie] '..gui.feedback) end
    end
end)
callbacks.on_render(function() if active then render_pulse() end end)

-- incase for some reason settings is not set for utils
if not utils.settings then
    utils.settings = settings
end
PLUGIN_alfred_the_butler = external
AlfredTheButlerPlugin = external
AlfredTheButlerPlugin._gui=gui
AlfredTheButlerPlugin._keybind_data=keybind_data
AlfredTheButlerPlugin._take_cleanup=lifecycle.take_cleanup

-- =============================================================================
-- Rosie Global Calls API
-- Call these from any other script to interact with Rosie.
-- =============================================================================

-- --- Plugin Control ---
AlfredTheButlerPlugin.enable = function()
    if not active then return false end
    lifecycle.clear_cancel() -- QQT_Warpigz_v3 3.3.1: as the Rosie enable does
    gui.elements.main_toggle:set(true)
    gui.elements.keybind_toggle:set(true)
    settings:update_settings()
    return true
end
AlfredTheButlerPlugin.disable = function()
    if not active then return false end
    gui.elements.main_toggle:set(false)
    gui.elements.keybind_toggle:set(false)
    settings:update_settings()
    if lifecycle.busy() then lifecycle.cancel('Rosie town service disabled during service') end
    return true
end
AlfredTheButlerPlugin.shutdown = function()
    active=false
    lifecycle.retire()
    return true
end

-- --- Stash Pull Queue ---
-- Queue all matching unlocked stash copies for the next explicitly requested town run.
-- sno_id : number  — item SNO ID
-- action : string  — 'salvage' | 'sell'
-- returns true on success, false if args are invalid
AlfredTheButlerPlugin.queue_stash_pull = function(sno_id, action)
    if not active or lifecycle.busy() or type(sno_id) ~= 'number' or sno_id<=0 or sno_id==math.huge or sno_id~=math.floor(sno_id) then return false end
    if action ~= 'salvage' and action ~= 'sell' then return false end
    for _,entry in ipairs(tracker.pending_pulls) do if entry.sno_id==sno_id then return false end end
    table.insert(tracker.pending_pulls, { sno_id = sno_id, action = action })
    return true
end
AlfredTheButlerPlugin.get_pending_pulls = function()
    local copy={}
    for i,entry in ipairs(tracker.pending_pulls) do copy[i]={sno_id=entry.sno_id,action=entry.action} end
    return copy
end
AlfredTheButlerPlugin.clear_pending_pulls = function()
    if not active or lifecycle.busy() then return false end
    tracker.pending_pulls = {}
    return true
end
