-- Generated by tools/build-rosie.mjs; edit the reviewed source or transform.
local callbacks=require('rosie.runtime').callbacks('town')
local plugin_label = 'alfred_the_butler'

local gui          = require 'rosie.private.town.gui'
local utils        = require 'rosie.private.town.core.utils'
local settings     = require 'rosie.private.town.core.settings'
local task_manager = require 'rosie.private.town.core.task_manager'
local tracker      = require 'rosie.private.town.core.tracker'
local external     = require 'rosie.private.town.core.external'
local drawing      = require 'rosie.private.town.core.drawing'
local lifecycle    = require 'rosie.private.town.core.lifecycle'
local active = true
local previous = rawget(_G,'AlfredTheButlerPlugin')
if type(previous)=='table' and type(previous.shutdown)=='function' then previous.shutdown() end
if type(previous)=='table' and type(previous._take_cleanup)=='function' then lifecycle.adopt_cleanup(previous._take_cleanup()) end

local local_player
local debounce_time = nil
local debounce_timeout = 1
local keybind_data = type(previous)=='table' and previous._keybind_data or checkbox:new(false, get_hash(plugin_label .. '_keybind_data'))
if PERSISTENT_MODE ~= nil and PERSISTENT_MODE ~= false then
    gui.elements.keybind_toggle:set(keybind_data:get())
end

local function update_locals()
    local_player = get_local_player()
end

local function main_pulse()
    if not lifecycle.retry_cleanup() then return end
    settings:update_settings()
    if PERSISTENT_MODE ~= nil and PERSISTENT_MODE ~= false  then
        if keybind_data:get() ~= (gui.elements.keybind_toggle:get_state() == 1) then
            keybind_data:set(gui.elements.keybind_toggle:get_state() == 1)
        end
    end

    if not settings.enabled then
        if lifecycle.busy() then lifecycle.cancel('Rosie town service disabled during service') end
        return
    end
    local world=get_current_world()
    if not local_player or local_player:is_dead()~=false or not world or world:get_current_zone_name()=='[sno none]' then
        task_manager.execute_tasks(); return
    end
    utils.update_tracker_count(local_player,lifecycle.busy())

    if settings.action_key_active(gui.elements.manual_keybind) then
        if debounce_time ~= nil and debounce_time + debounce_timeout > get_time_since_inject() then return end
        gui.elements.manual_keybind:set(false)
        debounce_time = get_time_since_inject()
        -- orbwalker.set_clear_toggle(false)
        -- QQT_Warpigz_v2: like the menu's Run town service, the keybind never
        -- clears another plugin's pause; a refusal is reported.
        if not lifecycle.busy() then
            local accepted,reason=lifecycle.request('manual',nil,true,true)
            if not accepted then console.print('[Rosie] Cannot start: '..tostring(reason)) end
        end
    end

    if settings.action_key_active(gui.elements.dump_keybind) then
        if debounce_time ~= nil and debounce_time + debounce_timeout > get_time_since_inject() then return end
        gui.elements.dump_keybind:set(false)
        debounce_time = get_time_since_inject()
        utils.dump_tracker_info(tracker)
    end

    if not (settings.get_keybind_state() or tracker.external_trigger or tracker.manual_trigger) then
        return
    end

    if not lifecycle.busy() then
        local activity=rawget(_G,'TRISTRAM_LOOP_STATE')
        local ok,state=false,nil
        if type(activity)=='table' and type(activity.status)=='function' then ok,state=pcall(activity.status) end
        if ok and type(state)=='table' and state.running and state.owns_activity then return end
        if tracker.need_trigger and not lifecycle.auto_blocked() then lifecycle.request('automatic',nil,true,true) end
    end
    task_manager.execute_tasks()
end

local function render_pulse()
    if not settings.enabled then return end
    if gui.elements.draw_status:get() then
        drawing.draw_status()
    end
    if gui.elements.draw_stash:get() or gui.elements.draw_sell:get() or gui.elements.draw_salvage:get() then
        drawing.draw_inventory_boxes()
    end
end

local last_idle_error=nil
callbacks.on_update(function()
    if not active then lifecycle.retry_cleanup(); return end
    update_locals()
    local ok,why=pcall(main_pulse)
    if not ok then
        local message='Host error: '..tostring(why)
        if lifecycle.busy() then lifecycle.finish(false,message)
        elseif last_idle_error~=message then console.print('[Rosie] '..message) end
        last_idle_error=message
    else
        last_idle_error=nil
    end
end)
callbacks.on_render_menu(function ()
    if not active then return end
    if not gui.render() then return end
    settings:update_settings()
    if not settings.enabled and lifecycle.busy() then lifecycle.cancel('Rosie town service disabled during service') end
    if not settings.enabled then gui.feedback=nil end
    if not gui.elements.main_toggle:get() then return end
    if lifecycle.busy() and gui.elements.stop_service:get() then
        lifecycle.cancel('Cancelled by user')
        gui.feedback=nil
        return
    end
    if not lifecycle.busy() and gui.elements.run_service:get() then
        local accepted,reason=lifecycle.request('manual',nil,true,true)
        gui.feedback=not accepted and 'Cannot start: '..tostring(reason) or nil
        if not accepted then console.print('[Rosie] '..gui.feedback) end
    end
end)
callbacks.on_render(function() if active then render_pulse() end end)

-- incase for some reason settings is not set for utils
if not utils.settings then
    utils.settings = settings
end
PLUGIN_alfred_the_butler = external
AlfredTheButlerPlugin = external
AlfredTheButlerPlugin._gui=gui
AlfredTheButlerPlugin._keybind_data=keybind_data
AlfredTheButlerPlugin._take_cleanup=lifecycle.take_cleanup

-- =============================================================================
-- Rosie Global Calls API
-- Call these from any other script to interact with Rosie.
-- =============================================================================

-- --- Plugin Control ---
AlfredTheButlerPlugin.enable = function()
    if not active then return false end
    gui.elements.main_toggle:set(true)
    gui.elements.keybind_toggle:set(true)
    settings:update_settings()
    return true
end
AlfredTheButlerPlugin.disable = function()
    if not active then return false end
    gui.elements.main_toggle:set(false)
    gui.elements.keybind_toggle:set(false)
    settings:update_settings()
    if lifecycle.busy() then lifecycle.cancel('Rosie town service disabled during service') end
    return true
end
AlfredTheButlerPlugin.shutdown = function()
    active=false
    lifecycle.retire()
    return true
end

-- --- Stash Pull Queue ---
-- Queue all matching unlocked stash copies for the next explicitly requested town run.
-- sno_id : number  — item SNO ID
-- action : string  — 'salvage' | 'sell'
-- returns true on success, false if args are invalid
AlfredTheButlerPlugin.queue_stash_pull = function(sno_id, action)
    if not active or lifecycle.busy() or type(sno_id) ~= 'number' or sno_id<=0 or sno_id==math.huge or sno_id~=math.floor(sno_id) then return false end
    if action ~= 'salvage' and action ~= 'sell' then return false end
    for _,entry in ipairs(tracker.pending_pulls) do if entry.sno_id==sno_id then return false end end
    table.insert(tracker.pending_pulls, { sno_id = sno_id, action = action })
    return true
end
AlfredTheButlerPlugin.get_pending_pulls = function()
    local copy={}
    for i,entry in ipairs(tracker.pending_pulls) do copy[i]={sno_id=entry.sno_id,action=entry.action} end
    return copy
end
AlfredTheButlerPlugin.clear_pending_pulls = function()
    if not active or lifecycle.busy() then return false end
    tracker.pending_pulls = {}
    return true
end
