-- Generated by tools/build-rosie.mjs; edit the reviewed source or transform.
local native_tree=tree_node
local tree_node={new=function(_,depth) return native_tree:new(depth+1) end}
local plugin_label = "Looter (Pirated Edition) "
local gui = {}
local options = require("rosie.private.pickup.data.gui_options")
local version = "v1.3.12-local"
local data_build = require("rosie.data.items").build
local previous=rawget(_G,'LooteerPlugin')
local cached=type(previous)=='table' and previous._elements


gui.elements = cached or {
   main_tree = tree_node:new(0),
   main_toggle = checkbox:new(true, get_hash(plugin_label .. "_main_toggle")),
   
   general = {
      tree = tree_node:new(1),
      behavior_combo = combo_box:new(0, get_hash(plugin_label .. "_behavior_combo")),
      loot_priority_combo = combo_box:new(0, get_hash(plugin_label .. "_loot_priority_combo")), 
      rarity_combo = combo_box:new(0, get_hash(plugin_label .. "_rarity_combo")),
      distance_slider = slider_int:new(1, 30, 2, get_hash(plugin_label .. "_distance_slider")),
      skip_dropped_toggle = checkbox:new(false, get_hash(plugin_label .. "_skipped_dropped_toggle")),
      respect_filter_toggle = checkbox:new(true, get_hash(plugin_label .. "_respect_filter_toggle")),
   },

   affix_settings = {
      tree = tree_node:new(1),
      greater_affix_slider = slider_int:new(0, 3, 0, get_hash(plugin_label .. "_greater_affix_slider")),
      unique_greater_affix_slider = slider_int:new(0, 4, 0, get_hash(plugin_label .. "_unique_greater_affix_slider")),
      magic_greater_affix_slider = slider_int:new(0, 4, 0, get_hash(plugin_label .. "_magic_greater_affix_slider")),
      rare_greater_affix_slider = slider_int:new(0, 4, 0, get_hash(plugin_label .. "_rare_greater_affix_slider")),
      innerTree = tree_node:new(2),
      custom_toggle = checkbox:new(false, get_hash(plugin_label .. "_custom_toggle")),
      armorsTree = tree_node:new(3),
      jewerlyTree = tree_node:new(3),
      weaponsTree = tree_node:new(3),
      oneHandedTree = tree_node:new(4),
      twoHandedTree = tree_node:new(4),
      offHandsTree = tree_node:new(4),
      --armors
         legendary_helm_slider = slider_int:new(0, 3, 2, get_hash(plugin_label .. "_legendary_helm_slider")),
         legendary_chest_slider = slider_int:new(0, 3, 2, get_hash(plugin_label .. "_legendary_chest_slider")),
         legendary_gloves_slider = slider_int:new(0, 3, 2, get_hash(plugin_label .. "_legendary_gloves_slider")),
         legendary_pants_slider = slider_int:new(0, 3, 2, get_hash(plugin_label .. "_legendary_pants_slider")),
         legendary_boots_slider = slider_int:new(0, 3, 2, get_hash(plugin_label .. "_legendary_boots_slider")),
         unique_helm_slider = slider_int:new(0, 4, 2, get_hash(plugin_label .. "_unique_helm_slider")),
         unique_chest_slider = slider_int:new(0, 4, 2, get_hash(plugin_label .. "_unique_chest_slider")),
         unique_gloves_slider = slider_int:new(0, 4, 2, get_hash(plugin_label .. "_unique_gloves_slider")),
         unique_pants_slider = slider_int:new(0, 4, 2, get_hash(plugin_label .. "_unique_pants_slider")),
         unique_boots_slider = slider_int:new(0, 4, 2, get_hash(plugin_label .. "_unique_boots_slider")),
      --jewerly
         legendary_amulet_slider = slider_int:new(0, 3, 2, get_hash(plugin_label .. "_legendary_amulet_slider")),
         unique_amulet_slider = slider_int:new(0, 4, 2, get_hash(plugin_label .. "_unique_amulet_slider")),
         legendary_ring_slider = slider_int:new(0, 3, 2, get_hash(plugin_label .. "_legendary_ring_slider")),
         unique_ring_slider = slider_int:new(0, 4, 2, get_hash(plugin_label .. "_unique_ring_slider")),
      --offhand
         legendary_focus_slider = slider_int:new(0, 3, 2, get_hash(plugin_label .. "_legendary_focus_slider")),
         legendary_totem_slider = slider_int:new(0, 3, 2, get_hash(plugin_label .. "_legendary_totem_slider")),
      
         --weapons
         --1h
         legendary_1h_mace_slider = slider_int:new(0, 3, 2, get_hash(plugin_label .. "_legendary_1h_mace_slider")),
         legendary_1h_sword_slider = slider_int:new(0, 3, 2, get_hash(plugin_label .. "_legendary_1h_sword_slider")),
         legendary_1h_axe_slider = slider_int:new(0, 3, 2, get_hash(plugin_label .. "_legendary_1h_axe_slider")),
         legendary_dagger_slider = slider_int:new(0, 3, 2, get_hash(plugin_label .. "_legendary_dagger_slider")),
         legendary_wand_slider = slider_int:new(0, 3, 2, get_hash(plugin_label .. "_legendary_wand_slider")),
         unique_1h_mace_slider = slider_int:new(0, 4, 2, get_hash(plugin_label .. "_unique_1h_mace_slider")),
         unique_1h_sword_slider = slider_int:new(0, 4, 2, get_hash(plugin_label .. "_unique_1h_sword_slider")),
         unique_1h_axe_slider = slider_int:new(0, 4, 2, get_hash(plugin_label .. "_unique_1h_axe_slider")),
         unique_dagger_slider = slider_int:new(0, 4, 2, get_hash(plugin_label .. "_unique_dagger_slider")),
         unique_wand_slider = slider_int:new(0, 4, 2, get_hash(plugin_label .. "_unique_wand_slider")),
         --2h
         legendary_2h_mace_slider = slider_int:new(0, 3, 2, get_hash(plugin_label .. "_legendary_2h_mace_slider")),
         legendary_2h_sword_slider = slider_int:new(0, 3, 2, get_hash(plugin_label .. "_legendary_2h_sword_slider")),
         legendary_2h_axe_slider = slider_int:new(0, 3, 2, get_hash(plugin_label .. "_legendary_2h_axe_slider")),
         legendary_2h_polearm_slider = slider_int:new(0, 3, 2, get_hash(plugin_label .. "_legendary_2h_polearm_slider")),
         legendary_staff_slider = slider_int:new(0, 3, 2, get_hash(plugin_label .. "_legendary_staff_slider")),
         legendary_bow_slider = slider_int:new(0, 3, 2, get_hash(plugin_label .. "_legendary_bow_slider")),
         legendary_crossbow_slider = slider_int:new(0, 3, 2, get_hash(plugin_label .. "_legendary_crossbow_slider")),
         legendary_glaive_slider = slider_int:new(0, 3, 2, get_hash(plugin_label .. "_legendary_glaive_slider")),
         legendary_quarterstaff_slider = slider_int:new(0, 3, 2, get_hash(plugin_label .. "_legendary_quarterstaff_slider")),
         unique_2h_mace_slider = slider_int:new(0, 4, 2, get_hash(plugin_label .. "_unique_2h_mace_slider")),
         unique_2h_sword_slider = slider_int:new(0, 4, 2, get_hash(plugin_label .. "_unique_2h_sword_slider")),
         unique_2h_axe_slider = slider_int:new(0, 4, 2, get_hash(plugin_label .. "_unique_2h_axe_slider")),
         unique_2h_polearm_slider = slider_int:new(0, 4, 2, get_hash(plugin_label .. "_unique_2h_polearm_slider")),
         unique_staff_slider = slider_int:new(0, 4, 2, get_hash(plugin_label .. "_unique_staff_slider")),
         unique_bow_slider = slider_int:new(0, 4, 2, get_hash(plugin_label .. "_unique_bow_slider")),
         unique_crossbow_slider = slider_int:new(0, 4, 2, get_hash(plugin_label .. "_unique_crossbow_slider")),
         unique_glaive_slider = slider_int:new(0, 4, 2, get_hash(plugin_label .. "_unique_glaive_slider")),
         unique_quarterstaff_slider = slider_int:new(0, 4, 2, get_hash(plugin_label .. "_unique_quarterstaff_slider")),
         
      --ubers
      uber_unique_greater_affix_slider = slider_int:new(0, 4, 0,get_hash(plugin_label .. "_uber_unique_greater_affix_slider")),
   },

   item_types = {
      tree = tree_node:new(1),
      event_items_toggle = checkbox:new(false, get_hash(plugin_label .. "_event_items_toggle")),
      quest_items_toggle = checkbox:new(false, get_hash(plugin_label .. "_quest_items_toggle")),
      crafting_items_toggle = checkbox:new(false, get_hash(plugin_label .. "_crafting_items_toggle")),
      boss_items_toggle = checkbox:new(false, get_hash(plugin_label .. "_boss_items_toggle")),
      rare_elixir_items_toggle = checkbox:new(false, get_hash(plugin_label .. "_rare_elixir_items_toggle")),
      basic_elixir_items_toggle = checkbox:new(false, get_hash(plugin_label .. "_basic_elixir_items_toggle")),
      advanced_elixir_items_toggle = checkbox:new(false, get_hash(plugin_label .. "_advanced_elixir_items_toggle")),
      sigil_items_toggle = checkbox:new(false, get_hash(plugin_label .. "_sigil_items_toggle")),
      compass_items_toggle = checkbox:new(false, get_hash(plugin_label .. "_compass_items_toggle")),
      rune_items_toggle = checkbox:new(false, get_hash(plugin_label .. "_rune_items_toggle")),
      tribute_items_toggle = checkbox:new(false, get_hash(plugin_label .. "_tribute_items_toggle")),
      scroll_items_toggle = checkbox:new(false, get_hash(plugin_label .. "_scroll_items_toggle")),
      cinders_toggle = checkbox:new(false, get_hash(plugin_label .. "_cinders_toggle")),
      heavenly_sigil_toggle = checkbox:new(false, get_hash(plugin_label .. "_heavenly_sigil_toggle")),
      charm_items_toggle = checkbox:new(true, get_hash(plugin_label .. "_charm_items_toggle")),
      seal_items_toggle = checkbox:new(true, get_hash(plugin_label .. "_seal_items_toggle")),
      splinter_items_toggle = checkbox:new(true, get_hash(plugin_label .. "_splinter_items_toggle")),
      lair_key_items_toggle = checkbox:new(true, get_hash(plugin_label .. "_lair_key_items_toggle")),
      gemstone_items_toggle = checkbox:new(false, get_hash(plugin_label .. "_gemstone_items_toggle")),
      fish_items_toggle = checkbox:new(false, get_hash(plugin_label .. "_fish_items_toggle")),
      cache_items_toggle = checkbox:new(true, get_hash(plugin_label .. "_cache_items_toggle")),
   },

   debug = {
      tree = tree_node:new(1),
      draw_wanted_toggle = checkbox:new(false, get_hash(plugin_label .. "_draw_wanted_toggle")),
      diagnose = button:new(get_hash(plugin_label .. "_diagnose_pickup")),
   },
}
-- Native tree handles belong to the current menu generation. Keep saved controls,
-- but recreate containers after refresh so a retired tree cannot block rendering.
if cached then
   gui.elements.main_tree=tree_node:new(0)
   gui.elements.general.tree=tree_node:new(1)
   gui.elements.affix_settings.tree=tree_node:new(1)
   gui.elements.affix_settings.innerTree=tree_node:new(2)
   gui.elements.affix_settings.armorsTree=tree_node:new(3)
   gui.elements.affix_settings.jewerlyTree=tree_node:new(3)
   gui.elements.affix_settings.weaponsTree=tree_node:new(3)
   gui.elements.affix_settings.oneHandedTree=tree_node:new(4)
   gui.elements.affix_settings.twoHandedTree=tree_node:new(4)
   gui.elements.affix_settings.offHandsTree=tree_node:new(4)
   gui.elements.item_types.tree=tree_node:new(1)
   gui.elements.debug.tree=tree_node:new(1)
end
-- Refreshes retain the existing widget objects and saved IDs. New slot controls
-- must be merged into that cached group rather than only the fresh table above.
local function add_slot_control(key,maximum)
   local controls=gui.elements.affix_settings
   controls[key.."_slider"]=controls[key.."_slider"]
      or slider_int:new(-1,maximum,-1,get_hash(plugin_label.."_"..key.."_slider"))
end
for _,slot in ipairs({"1h_scythe","2h_scythe","flail","shield"}) do
   add_slot_control("legendary_"..slot,3)
   add_slot_control("unique_"..slot,4)
end
add_slot_control("unique_focus",4)
add_slot_control("unique_totem",4)
gui.elements.item_types.other_consumable_items_toggle=gui.elements.item_types.other_consumable_items_toggle
   or checkbox:new(false,get_hash(plugin_label.."_other_consumable_items_toggle"))

local menu_stack,menu_error={},nil
local function push_tree(node,label)
   if not node:push(label) then return false end
   menu_stack[#menu_stack+1]=node
   return true
end
local function pop_tree(node)
   node:pop()
   menu_stack[#menu_stack]=nil
end
local function render_settings(status)
   if not push_tree(gui.elements.main_tree,"Pickup rules") then
      return
   end

   gui.elements.main_toggle:render("Enable pickup", "Start or stop standalone pickup. Settings stay editable while off.")
   if type(status)=='function' then
      local current=status()
      render_menu_header(current.detail)
   end
   render_menu_header("Turn host Auto Loot off to use these pickup filters.")

   if push_tree(gui.elements.general.tree,"General Settings") then
      gui.elements.general.behavior_combo:render("Behavior", options.behaviors,
         "When do you want the autolooter to execute?")
      gui.elements.general.rarity_combo:render("Minimum Equipment Rarity", options.rarities,
         "Minimum rarity for equipment only. Other item types use their category controls; Charms and Seals also use the optional ingame filter.")
      gui.elements.general.distance_slider:render("Distance", "Distance from the loot to execute pickup")
      gui.elements.general.skip_dropped_toggle:render("Skip gear with visible affixes (legacy)",
         "Legacy dropped-item heuristic. It can also skip fresh gear; leave off unless verified in your client.")
      gui.elements.general.respect_filter_toggle:render("Respect Ingame Loot Filter",
         "Skip filtered equipment, Charms and Seals. Materials and keys use their category controls.")
      gui.elements.general.loot_priority_combo:render("Loot Priority", {"Closest First", "Best First"},
         "Select the priority for looting items")
      pop_tree(gui.elements.general.tree)
   end
       
   if push_tree(gui.elements.affix_settings.tree,"Equipment Greater Affixes") then
      render_menu_header("Ancestral is an item tier, not a rarity or a GA count. An ancestral Unique follows Unique GA rules.")
      render_menu_header("Charms and Seals use their category switches and the optional ingame filter.")
      gui.elements.affix_settings.magic_greater_affix_slider:render("Magic GA Count", "Minimum Greater Affixes for Magic gear.")
      gui.elements.affix_settings.rare_greater_affix_slider:render("Rare GA Count", "Minimum Greater Affixes for Rare gear.")
      gui.elements.affix_settings.greater_affix_slider:render("Legendary GA Count",
      "Minimum GA's to consider picking up legendary")
      gui.elements.affix_settings.unique_greater_affix_slider:render("Unique GA Count",
      "Minimum GA's to consider picking up unique")
      gui.elements.affix_settings.uber_unique_greater_affix_slider:render("Mythic GA Count",
      "Minimum Greater Affixes for Mythic Unique equipment. Per-slot overrides do not replace this setting.")
      if push_tree(gui.elements.affix_settings.innerTree,"Advanced Settings") then
         gui.elements.affix_settings.custom_toggle:render("Use Legendary and Unique Slot Overrides",
            "When enabled, the slot sliders replace BOTH general Legendary and Unique equipment GA minimums. Existing saved slot values still apply. Mythic gear keeps its separate minimum.")
         render_menu_header("Where available, -1 inherits the general minimum; 0 accepts any GA count.")
         if push_tree(gui.elements.affix_settings.armorsTree,"Armor") then
            gui.elements.affix_settings.legendary_helm_slider:render("Legendary Helm GA Count",
               "Minimum GA's to consider picking up legendary helms")
            gui.elements.affix_settings.legendary_chest_slider:render("Legendary Chest GA Count",
               "Minimum GA's to consider picking up legendary chests")
            gui.elements.affix_settings.legendary_gloves_slider:render("Legendary Gloves GA Count",
               "Minimum GA's to consider picking up legendary gloves")
            gui.elements.affix_settings.legendary_pants_slider:render("Legendary Pants GA Count",
               "Minimum GA's to consider picking up legendary Pants")
            gui.elements.affix_settings.legendary_boots_slider:render("Legendary Boots GA Count",
               "Minimum GA's to consider picking up legendary Boots")
            gui.elements.affix_settings.unique_helm_slider:render("Unique Helm GA Count",
               "Minimum GA's to consider picking up unique helms")
            gui.elements.affix_settings.unique_chest_slider:render("Unique Chest GA Count",
               "Minimum GA's to consider picking up unique chests")
            gui.elements.affix_settings.unique_gloves_slider:render("Unique Gloves GA Count",
               "Minimum GA's to consider picking up unique gloves")
            gui.elements.affix_settings.unique_pants_slider:render("Unique Pants GA Count",
               "Minimum GA's to consider picking up unique Pants")
            gui.elements.affix_settings.unique_boots_slider:render("Unique Boots GA Count",
               "Minimum GA's to consider picking up unique Boots")
            pop_tree(gui.elements.affix_settings.armorsTree)
         end
         if push_tree(gui.elements.affix_settings.jewerlyTree,"Jewelry") then
            gui.elements.affix_settings.legendary_amulet_slider:render("Legendary Amulet GA Count",
               "Minimum GA's to consider picking up legendary amulets")
            gui.elements.affix_settings.unique_amulet_slider:render("Unique Amulet GA Count",
               "Minimum GA's to consider picking up unique amulets")
            gui.elements.affix_settings.legendary_ring_slider:render("Legendary Ring GA Count",
               "Minimum GA's to consider picking up legendary rings")
            gui.elements.affix_settings.unique_ring_slider:render("Unique Ring GA Count",
               "Minimum GA's to consider picking up unique rings")
            pop_tree(gui.elements.affix_settings.jewerlyTree)
         end
         if push_tree(gui.elements.affix_settings.weaponsTree,"Weapons") then
            if push_tree(gui.elements.affix_settings.oneHandedTree,"One-handed") then
               gui.elements.affix_settings.legendary_1h_mace_slider:render("Legendary 1H Mace GA Count",
                  "Minimum GA's to consider picking up legendary 1H maces")
               gui.elements.affix_settings.legendary_1h_axe_slider:render("Legendary 1H Axe GA Count",
                  "Minimum GA's to consider picking up legendary 1H axes")
               gui.elements.affix_settings.legendary_1h_sword_slider:render("Legendary 1H Sword GA Count",
                  "Minimum GA's to consider picking up legendary 1H swords")
               gui.elements.affix_settings.legendary_dagger_slider:render("Legendary Dagger GA Count",
                  "Minimum GA's to consider picking up legendary Dagger")
               gui.elements.affix_settings.legendary_wand_slider:render("Legendary wand GA Count",
                  "Minimum GA's to consider picking up legendary wand")
               gui.elements.affix_settings.unique_1h_mace_slider:render("Unique 1H Mace GA Count",
                  "Minimum GA's to consider picking up unique 1H maces")
               gui.elements.affix_settings.unique_1h_axe_slider:render("Unique 1H Axe GA Count",
                  "Minimum GA's to consider picking up unique 1H axes")
               gui.elements.affix_settings.unique_1h_sword_slider:render("Unique 1H Sword GA Count",
                  "Minimum GA's to consider picking up unique 1H swords")
               gui.elements.affix_settings.unique_dagger_slider:render("Unique Dagger GA Count",
                  "Minimum GA's to consider picking up unique Dagger")
               gui.elements.affix_settings.unique_wand_slider:render("Unique wand GA Count",
                  "Minimum GA's to consider picking up unique wand")
               gui.elements.affix_settings.legendary_1h_scythe_slider:render("Legendary 1H Scythe GA Count",
                  "-1 inherits Legendary GA Count; otherwise use this minimum for 1H scythes.")
               gui.elements.affix_settings.unique_1h_scythe_slider:render("Unique 1H Scythe GA Count",
                  "-1 inherits Unique GA Count; otherwise use this minimum for 1H scythes.")
               gui.elements.affix_settings.legendary_flail_slider:render("Legendary Flail GA Count",
                  "-1 inherits Legendary GA Count; otherwise use this minimum for flails.")
               gui.elements.affix_settings.unique_flail_slider:render("Unique Flail GA Count",
                  "-1 inherits Unique GA Count; otherwise use this minimum for flails.")
               pop_tree(gui.elements.affix_settings.oneHandedTree)
            end
            if push_tree(gui.elements.affix_settings.twoHandedTree,"Two-handed") then
               gui.elements.affix_settings.legendary_2h_mace_slider:render("Legendary 2H Mace GA Count",
                  "Minimum GA's to consider picking up legendary 2H maces")
               gui.elements.affix_settings.legendary_2h_axe_slider:render("Legendary 2H Axe GA Count",
                  "Minimum GA's to consider picking up legendary 2H axes")
               gui.elements.affix_settings.legendary_2h_sword_slider:render("Legendary 2H Sword GA Count",
                  "Minimum GA's to consider picking up legendary 2H swords")
               gui.elements.affix_settings.legendary_2h_polearm_slider:render("Legendary 2H Polearm GA Count",
                  "Minimum GA's to consider picking up legendary 2H polearms")
               gui.elements.affix_settings.legendary_staff_slider:render("Legendary Staff GA Count",
                  "Minimum GA's to consider picking up legendary staffs")
               gui.elements.affix_settings.legendary_bow_slider:render("Legendary Bow GA Count",
                  "Minimum GA's to consider picking up legendary bows")
               gui.elements.affix_settings.legendary_crossbow_slider:render("Legendary Crossbow GA Count",
                  "Minimum GA's to consider picking up legendary crossbows")
               gui.elements.affix_settings.legendary_glaive_slider:render("Legendary Glaive GA Count",
                  "Minimum GA's to consider picking up legendary glaive")
               gui.elements.affix_settings.legendary_quarterstaff_slider:render("Legendary Quarterstaff GA Count",
                  "Minimum GA's to consider picking up legendary quarterstaff")
               gui.elements.affix_settings.unique_2h_mace_slider:render("Unique 2H Mace GA Count",
                  "Minimum GA's to consider picking up unique 2H maces")
               gui.elements.affix_settings.unique_2h_axe_slider:render("Unique 2H Axe GA Count",
                  "Minimum GA's to consider picking up unique 2H axes")
               gui.elements.affix_settings.unique_2h_sword_slider:render("Unique 2H Sword GA Count",
                  "Minimum GA's to consider picking up unique 2H swords")
               gui.elements.affix_settings.unique_2h_polearm_slider:render("Unique 2H Polearm GA Count",
                  "Minimum GA's to consider picking up unique 2H polearms")
               gui.elements.affix_settings.unique_staff_slider:render("Unique Staff GA Count",
                  "Minimum GA's to consider picking up unique staffs")
               gui.elements.affix_settings.unique_bow_slider:render("Unique Bow GA Count",
                  "Minimum GA's to consider picking up unique bows")
               gui.elements.affix_settings.unique_crossbow_slider:render("Unique Crossbow GA Count",
                  "Minimum GA's to consider picking up unique crossbows")
               gui.elements.affix_settings.unique_glaive_slider:render("Unique Glaive GA Count",
                  "Minimum GA's to consider picking up unique glaive")
               gui.elements.affix_settings.unique_quarterstaff_slider:render("Unique Quarterstaff GA Count",
                  "Minimum GA's to consider picking up unique quarterstaff")
               gui.elements.affix_settings.legendary_2h_scythe_slider:render("Legendary 2H Scythe GA Count",
                  "-1 inherits Legendary GA Count; otherwise use this minimum for 2H scythes.")
               gui.elements.affix_settings.unique_2h_scythe_slider:render("Unique 2H Scythe GA Count",
                  "-1 inherits Unique GA Count; otherwise use this minimum for 2H scythes.")
               pop_tree(gui.elements.affix_settings.twoHandedTree)
            end
            if push_tree(gui.elements.affix_settings.offHandsTree,"Offhands") then
               gui.elements.affix_settings.legendary_focus_slider:render("Legendary Focus GA Count",
                  "Minimum GA's to consider picking up legendary Focuses")
               gui.elements.affix_settings.legendary_totem_slider:render("Legendary Totem GA Count",
                  "Minimum GA's to consider picking up legendary Totems")
               gui.elements.affix_settings.unique_focus_slider:render("Unique Focus GA Count",
                  "-1 inherits Unique GA Count; otherwise use this minimum for focuses, including class offhands.")
               gui.elements.affix_settings.unique_totem_slider:render("Unique Totem GA Count",
                  "-1 inherits Unique GA Count; otherwise use this minimum for totems.")
               gui.elements.affix_settings.legendary_shield_slider:render("Legendary Shield GA Count",
                  "-1 inherits Legendary GA Count; otherwise use this minimum for shields.")
               gui.elements.affix_settings.unique_shield_slider:render("Unique Shield GA Count",
                  "-1 inherits Unique GA Count; otherwise use this minimum for shields.")
               pop_tree(gui.elements.affix_settings.offHandsTree)
            end
            pop_tree(gui.elements.affix_settings.weaponsTree)
         end
         pop_tree(gui.elements.affix_settings.innerTree)
      end
      pop_tree(gui.elements.affix_settings.tree)
   end
 
   if push_tree(gui.elements.item_types.tree,"Item Types") then
      gui.elements.item_types.quest_items_toggle:render("Quest Items",
         "Do you want to pickup Quest items, this includes Objectives in dungeons.")
      gui.elements.item_types.crafting_items_toggle:render("Crafting Materials / Recipes / Unlocks",
         "Recognized crafting materials, recipes, books and supported cosmetic or mount unlocks. Keeps the existing Crafting Items preference.")
      gui.elements.item_types.boss_items_toggle:render("Boss Trophies / Legacy Boss Items", "Keep boss trophies for crafting. Lair Keys have their own control.")
      gui.elements.item_types.lair_key_items_toggle:render("Lair Keys", "Keys for opening boss hoards, including Superior Lair Keys.")
      gui.elements.item_types.charm_items_toggle:render("Charms", "Includes recognized set and unique Charms. Uses the Talisman bag and optional ingame filter, not equipment rarity/GA sliders.")
      gui.elements.item_types.seal_items_toggle:render("Seals", "Includes recognized Mythic Seals and Annihilus. Uses the Talisman bag and optional ingame filter, not equipment rarity/GA sliders.")
      gui.elements.item_types.splinter_items_toggle:render("Soul Splinters / Triad Items", "Uses the item type's socketable or consumable bag.")
      gui.elements.item_types.gemstone_items_toggle:render("Gemstones", "Uses the socketable bag.")
      gui.elements.item_types.fish_items_toggle:render("Fish", "Pick up recognized fish when there is room.")
      gui.elements.item_types.cache_items_toggle:render("Reward Caches", "Pick up recognized reward caches when there is room.")
      gui.elements.item_types.rare_elixir_items_toggle:render("Special / Legacy Elixirs and Opals",
         "Recognized special elixirs, legacy seasonal elixirs, Seething Opals and Draught of Whispers. An item record does not guarantee current drop availability.")
      gui.elements.item_types.basic_elixir_items_toggle:render("Basic Elixirs",
         "Do you wanna pickup Basic Elixirs?")
      gui.elements.item_types.advanced_elixir_items_toggle:render("Advanced Elixirs",
         "Do you wanna pickup Advanced Elixirs II?")
      gui.elements.item_types.other_consumable_items_toggle:render("Other Consumables / Incense",
         "Otherwise uncategorized consumables, elixirs and incense. Basic, Advanced, Special, Event and Triad items retain their existing controls. Off by default.")
      gui.elements.item_types.scroll_items_toggle:render("Scrolls", "Do you want to loot scrolls?")
      gui.elements.item_types.sigil_items_toggle:render("Nightmare Dungeon Sigils", "Do you want to loot dungeon sigils?")
      gui.elements.item_types.compass_items_toggle:render("Horde Compasses", "Do you want to loot horde compasses?")
      gui.elements.item_types.tribute_items_toggle:render("Tributes", "Do you want to loot tributes?")
      gui.elements.item_types.rune_items_toggle:render("Runes", "Do you want to runes?")
      gui.elements.item_types.event_items_toggle:render("Event Bags / Gileon's Brew", "Recognized event treasure bags and Gileon's Brew. Reward Caches have a separate control.")
      gui.elements.item_types.cinders_toggle:render("Cinders (Legacy)", "Compatibility control for recognized legacy Cinder skins. The current item catalog does not establish live availability.")
      gui.elements.item_types.heavenly_sigil_toggle:render("Heavenly Sigil (Legacy)", "Compatibility control for recognized legacy Heavenly Sigil skins. The current item catalog does not establish live availability.")
      pop_tree(gui.elements.item_types.tree)
   end
 
   if push_tree(gui.elements.debug.tree,"Display and diagnostics") then
      gui.elements.debug.draw_wanted_toggle:render("Highlight accepted items",
         "Draw circles around items accepted by the current filters.")
      render_menu_header("Offline item data: " .. data_build)
      pop_tree(gui.elements.debug.tree)
   end
 
   pop_tree(gui.elements.main_tree)
   return true
end
function gui.render(status)
   menu_stack={}
   local ok,result=pcall(render_settings,status)
   for i=#menu_stack,1,-1 do pcall(function() menu_stack[i]:pop() end) end
   menu_stack={}
   if not ok then
      gui.render_error=true
      if menu_error~=tostring(result) then console.print('[Rosie pickup] Menu error: '..tostring(result)) end
      menu_error=tostring(result)
      return false
   end
   gui.render_error=false
   menu_error=nil
   return result==true
end

return gui
