-- Generated by tools/build-rosie.mjs; edit the reviewed source or transform.
local callbacks=require('rosie.runtime').callbacks('pickup')
local Settings=require('rosie.private.pickup.src.settings')
local ItemManager=require('rosie.private.pickup.src.item_manager')
local Pickup=require('rosie.private.pickup.src.pickup')
local Renderer=require('rosie.private.pickup.src.renderer')
local GUI=require('rosie.private.pickup.gui')
local Utils=require('rosie.private.pickup.utils.utils')
local active=true
local published
local function activity_owns_loot()
    local peer=rawget(_G,'TRISTRAM_LOOP_STATE')
    if type(peer)~='table' or type(peer.status)~='function' then return false end
    local ok,status=pcall(peer.status)
    return ok and type(status)=='table' and status.running==true and status.owns_activity==true and status.controls_loot==true
end
local function release_pickup(reset)
    -- Another activity may already have issued its own path this frame.
    if reset then Pickup.reset(not activity_owns_loot())
    else Pickup.release_movement(not activity_owns_loot()) end
    Settings.get().looting=false
end
local previous=rawget(_G,'LooteerPlugin')
if type(previous)=='table' and type(previous.shutdown)=='function' then
    local ok,state=pcall(previous.shutdown)
    if ok then Settings.restore_pause_state(state) end
end
local function forwarding(name,...)
    local current=rawget(_G,'LooteerPlugin')
    if type(current)=='table' and current~=published and type(current[name])=='function' then
        return current[name](...)
    end
    return false
end
local function set_setting(key,value)
    if not active then return forwarding('setSettings',key,value) end
    local result=Settings.set(key,value)
    if result and (key=='enabled' and not value or key=='looting') then release_pickup(key=='enabled') end
    return result
end
local function acquire_pause(caller)
    if not active then return forwarding('acquire_pause',caller) end
    local result=Settings.acquire_pause(caller)
    if result then release_pickup() end
    return result
end
local function release_pause(caller)
    if not active then return forwarding('release_pause',caller) end
    return Settings.release_pause(caller)
end
local function main_pulse()
    if not active then return end
    Settings.update()
    Settings.get().looting=false
    if not Settings.get().enabled then release_pickup(true); return end
    local player=get_local_player()
    if not player or Utils.call(player,'is_dead')~=false or not Settings.get().enabled then release_pickup(); return end
    local world=get_current_world()
    local zone=Utils.call(world,'get_current_zone_name')
    if not world or not zone or zone=='[sno none]' or is_chat_open() or is_inventory_open() then release_pickup(); return end
    if not Settings.should_execute() then release_pickup(); return end
    -- QQT_Warpigz_v2 local patch (Rosie 1.0.7, LooteerV3 main.lua): the host's own Auto Loot would walk
    -- to drops Rosie refuses and fight its movement; keep it off while pickup runs.
    local orb=rawget(_G,'orbwalker')
    if type(orb)=='table' and type(orb.set_auto_loot_toggle)=='function' then pcall(orb.set_auto_loot_toggle,false) end
    if Settings.is_paused() then release_pickup(); return end
    -- The activity uses our filter over its arena and owns the actual movement.
    -- Its recovery/party phases must not be interrupted by standalone pickup.
    if activity_owns_loot() then Pickup.reset(false); return end
    local wanted=ItemManager.get_item_based_on_priority()
    if wanted and Settings.get().loot_priority==1 then wanted=wanted.Item end
    if wanted then Settings.get().looting=Pickup.step(wanted)
    else Pickup.release_movement() end
end
published={
    _elements=GUI.elements,
    getSettings=function(key)
        local value=Settings.get()[key]
        return value~=false and value or nil
    end,
    setSettings=set_setting,
    acquire_pause=acquire_pause,
    release_pause=release_pause,
    enable=function() return set_setting('enabled',true) end,
    disable=function() return set_setting('enabled',false) end,
    shutdown=function()
        if active then release_pickup(true); active=false end
        return Settings.pause_state()
    end,
    get_enabled=function() return GUI.elements.main_toggle:get() end,
    is_idle=function() return not Settings.get().looting end,
    is_actively_looting=function() return Settings.get().looting==true end,
    status=function()
        Settings.update()
        local enabled,paused,owned=Settings.get().enabled,Settings.is_paused(),activity_owns_loot()
        local reason,detail='ready','Ready; waiting for an accepted item in range.'
        if not enabled then reason,detail='disabled','Off. Configure below, then enable pickup.'
        elseif paused then
            local owners={}
            for owner in pairs(Settings.pause_state().owners) do owners[#owners+1]=owner end
            table.sort(owners)
            reason,detail='paused','Paused by '..(#owners>0 and table.concat(owners,', ') or 'an external caller')..'.'
        elseif owned then reason,detail='activity_owned','Tristram controls pickup and movement; these filters still apply.'
        elseif not Settings.should_execute() then reason,detail='waiting_for_clear','Waiting for orbwalker Clear mode. Change Behavior to run at any time.'
        elseif Utils.call(get_local_player(),'is_dead')~=false then reason,detail='unavailable','Waiting for a living player.'
        else
            local zone=Utils.call(get_current_world(),'get_current_zone_name')
            if not zone or zone=='[sno none]' then reason,detail='loading','Waiting for the world to load.'
            elseif is_chat_open() or is_inventory_open() then reason,detail='menu_open','Waiting for chat or inventory to close.'
            elseif Settings.get().looting then reason,detail='picking_up','Picking up accepted items.' end
        end
        return {enabled=enabled,paused=paused,ready=reason=='ready' or reason=='picking_up',
            running=reason=='picking_up',activity_owned=owned,reason=reason,detail=detail}
    end,
    evaluate_item=function(item,ignore_distance)
        local wanted,reason,decision=ItemManager.check_want_item(item,ignore_distance)
        if not wanted then ItemManager.report_rejection(item,reason) end
        return wanted,reason,decision
    end,
    observe_items=ItemManager.observe,
    diagnose=ItemManager.diagnose,
}
LooteerPlugin=published
callbacks.on_update(main_pulse)
callbacks.on_render_menu(function()
    if not active then return end
    if GUI.render(published.status) then
        Settings.update()
        if not Settings.get().enabled then release_pickup(true) end
        if GUI.elements.debug.diagnose:get() then ItemManager.diagnose() end
    end
end)
callbacks.on_render(function() if active then Renderer.draw_stuff() end end)
