-- Generated by tools/build-rosie.mjs; edit the reviewed source or transform.
local callbacks=require('rosie.runtime').callbacks('pickup')
local Settings=require('rosie.private.pickup.src.settings')
local ItemManager=require('rosie.private.pickup.src.item_manager')
local Pickup=require('rosie.private.pickup.src.pickup')
local Renderer=require('rosie.private.pickup.src.renderer')
local GUI=require('rosie.private.pickup.gui')
local Utils=require('rosie.private.pickup.utils.utils')
local active=true
local published
local fight_busy=false -- QQT_Warpigz_v3 3.3.2: busy set only by a drop waiting for the fight
local foreign=require('rosie.private.foreign') -- QQT_Warpigz_v3 1.0.21
local Mimic=require('rosie.private.scavenger_mimic') -- QQT_Warpigz_v3 1.0.23: Rosie as Scavenger
local fight_only=false -- QQT_Warpigz_v3 1.0.25: looting=true only for the fight wait (status says so)
-- QQT_Warpigz_v3 1.0.25 (Discord: pickup stopped with no line): a gate that
-- keeps pickup off while a wanted drop lies in range is logged once per zone
-- (orbwalker Clear mode, a busy Scavenger addon).
local gate={clear=nil,scav=nil,check_at=nil,last=false}
local function zone_key()
    local w=get_current_world()
    return tostring(Utils.call(w,'get_world_id'))..'|'..tostring(Utils.call(w,'get_current_zone_name'))
end
-- A wanted drop within the Distance slider. QQT_Warpigz_v3 1.0.25 (review):
-- scanned at most every 1 s (both gates share it); between scans the last
-- answer, not false.
local function wanted_in_range(now)
    if gate.check_at and now>=gate.check_at and now-gate.check_at<1.0 then return gate.last end
    gate.check_at,gate.last=now,false
    local items=Utils.host_call(rawget(_G,'actors_manager') and actors_manager.get_all_items)
    for _,item in pairs(type(items)=='table' and items or {}) do
        local ok,want=pcall(ItemManager.check_want_item,item,false)
        if ok and want==true then gate.last=true;return true end
    end
    return false
end
local function activity_owns_loot()
    -- QQT_Warpigz_v3 1.0.21: Navigator's Scavenger owns the drops while busy.
    if foreign.scavenger_busy() then return true end
    local peer=rawget(_G,'TRISTRAM_LOOP_STATE')
    if type(peer)~='table' or type(peer.status)~='function' then return false end
    local ok,status=pcall(peer.status)
    return ok and type(status)=='table' and status.running==true and status.owns_activity==true and status.controls_loot==true
end
local function release_pickup(reset)
    -- Another activity may already have issued its own path this frame.
    if reset then Pickup.reset(not activity_owns_loot())
    else Pickup.release_movement(not activity_owns_loot()) end
    Settings.get().looting=false
end
local previous=rawget(_G,'LooteerPlugin')
if type(previous)=='table' and type(previous.shutdown)=='function' then
    local ok,state=pcall(previous.shutdown)
    if ok then Settings.restore_pause_state(state) end
end
local function forwarding(name,...)
    local current=rawget(_G,'LooteerPlugin')
    if type(current)=='table' and current~=published and type(current[name])=='function' then
        return current[name](...)
    end
    return false
end
local function set_setting(key,value)
    if not active then return forwarding('setSettings',key,value) end
    local result=Settings.set(key,value)
    if result and (key=='enabled' and not value or key=='looting') then release_pickup(key=='enabled') end
    return result
end
local function acquire_pause(caller)
    if not active then return forwarding('acquire_pause',caller) end
    local result=Settings.acquire_pause(caller)
    if result then release_pickup() end
    return result
end
local function release_pause(caller)
    if not active then return forwarding('release_pause',caller) end
    return Settings.release_pause(caller)
end
local function main_pulse()
    if not active then return end
    Settings.update()
    Settings.get().looting=false
    fight_only=false -- QQT_Warpigz_v3 1.0.25
    if not Settings.get().enabled then release_pickup(true); return end
    local player=get_local_player()
    if not player or Utils.call(player,'is_dead')~=false or not Settings.get().enabled then release_pickup(); return end
    local world=get_current_world()
    local zone=Utils.call(world,'get_current_zone_name')
    if not world or not zone or zone=='[sno none]' or is_chat_open() or is_inventory_open() then release_pickup(); return end
    if not Settings.should_execute() then
        -- QQT_Warpigz_v3 1.0.25: Behavior = Orbwalk outside Clear mode, logged once per zone.
        local key=zone_key()
        if gate.clear~=key and not Settings.is_paused() and wanted_in_range(get_time_since_inject()) then
            gate.clear=key
            console.print('[Rosie pickup] Waiting for orbwalker Clear mode (Behavior = Orbwalk): a wanted drop is in range; set Behavior to Always to pick up at any time')
        end
        release_pickup(); return
    end
    -- QQT_Warpigz_v2 local patch (Rosie 1.0.7, LooteerV3 main.lua): the host's own Auto Loot would walk
    -- to drops Rosie refuses and fight its movement; keep it off while pickup runs.
    local orb=rawget(_G,'orbwalker')
    if type(orb)=='table' and type(orb.set_auto_loot_toggle)=='function' then pcall(orb.set_auto_loot_toggle,false) end
    if Settings.is_paused() then release_pickup(); return end
    -- The activity uses our filter over its arena and owns the actual movement.
    -- Its recovery/party phases must not be interrupted by standalone pickup.
    -- QQT_Warpigz_v3 1.0.25: a busy Scavenger addon while a wanted drop is in
    -- range is logged once per zone.
    local now=get_time_since_inject()
    if foreign.scavenger_busy() then
        local key=zone_key()
        if gate.scav~=key and wanted_in_range(now) then
            gate.scav=key
            console.print('[Rosie pickup] Scavenger (Navigator\'s looter) is busy: Rosie leaves the drops in range to it while it is')
        end
    end
    if activity_owns_loot() then Pickup.reset(false); return end
    Pickup.sample_cast(now) -- QQT_Warpigz_v3 1.0.25: the fight hold's engaged rule
    pcall(Pickup.nav_watch,now) -- QQT_Warpigz_v3 1.0.25 (review): the Navigator stop watchdog
    local wanted=ItemManager.get_item_based_on_priority()
    if wanted and Settings.get().loot_priority==1 then wanted=wanted.Item end
    if wanted then Settings.get().looting=Pickup.step(wanted,ItemManager.destination(wanted)) -- QQT_Warpigz_v3 (Q1): receipt bag
        -- QQT_Warpigz_v3 1.0.23: only a pulse that really works a drop
        -- (Pickup.step true) makes the Scavenger mimic busy, never the fight wait below.
        if Settings.get().looting==true then Mimic.note_work(get_time_since_inject()) end
    else Pickup.release_movement() end
    -- QQT_Warpigz_v3 1.0.22: a drop that waits for the fight no longer keeps
    -- pickup busy (farm plugins that yield to a busy Looter stood still for
    -- the whole fight). The wait is published apart, has_pending_loot() /
    -- status().loot_waiting, for exit checks; bounded by the fight hold's 45 s
    -- cap. fight_busy is the time of the last pulse that saw the wait.
    fight_busy=ItemManager.fight_waiting==true and get_time_since_inject() or false
    -- QQT_Warpigz_v3 1.0.25 (Navigator review, calm tail): the last enemy is
    -- gone but the hold waits its FIGHT.calm s; the Scavenger stand-in is busy
    -- already, so Worldstone does not leave before Rosie's first step (never
    -- while a counted enemy is within 14 m; a no-op without Worldstone).
    if fight_busy and Pickup.calm_tail() then Mimic.note_work(fight_busy) end
    if fight_busy and not wanted and Pickup.fight_wait_busy then Settings.get().looting=true;fight_only=true end -- transitional, see pickup.lua
end
-- QQT_Warpigz_v3 1.0.22: a wait no pulse has confirmed for 1 s is stale (Rosie
-- off, pickup paused / owned by an activity, reloaded).
local function loot_waiting()
    if not active or not fight_busy then return false end
    local now=get_time_since_inject()
    return now>=fight_busy and now-fight_busy<1.0
end
published={
    _elements=GUI.elements,
    getSettings=function(key)
        local value=Settings.get()[key]
        return value~=false and value or nil
    end,
    setSettings=set_setting,
    acquire_pause=acquire_pause,
    release_pause=release_pause,
    enable=function() return set_setting('enabled',true) end,
    disable=function() return set_setting('enabled',false) end,
    shutdown=function()
        if active then release_pickup(true); active=false end
        return Settings.pause_state()
    end,
    get_enabled=function() return GUI.elements.main_toggle:get() end,
    is_idle=function() return not Settings.get().looting end,
    is_actively_looting=function() return Settings.get().looting==true end,
    has_pending_loot=loot_waiting, -- QQT_Warpigz_v3 1.0.22: a wanted drop waits for the fight
    status=function()
        Settings.update()
        local enabled,paused,owned=Settings.get().enabled,Settings.is_paused(),activity_owns_loot()
        local reason,detail='ready','Ready; waiting for an accepted item in range.'
        if not enabled then reason,detail='disabled','Off. Configure below, then enable pickup.'
        elseif paused then
            local owners={}
            for owner in pairs(Settings.pause_state().owners) do owners[#owners+1]=owner end
            table.sort(owners)
            reason,detail='paused','Paused by '..(#owners>0 and table.concat(owners,', ') or 'an external caller')..'.'
        elseif owned then reason,detail='activity_owned','Tristram controls pickup and movement; these filters still apply.'
            -- QQT_Warpigz_v3 1.0.25: name the Scavenger addon when it is the owner.
            if foreign.scavenger_busy() then detail='Scavenger (Navigator\'s looter) is busy; Rosie leaves the drops to it.' end
        elseif not Settings.should_execute() then reason,detail='waiting_for_clear','Waiting for orbwalker Clear mode. Change Behavior to run at any time.'
        elseif Utils.call(get_local_player(),'is_dead')~=false then reason,detail='unavailable','Waiting for a living player.'
        else
            local zone=Utils.call(get_current_world(),'get_current_zone_name')
            if not zone or zone=='[sno none]' then reason,detail='loading','Waiting for the world to load.'
            elseif is_chat_open() or is_inventory_open() then reason,detail='menu_open','Waiting for chat or inventory to close.'
            elseif Settings.get().looting then reason,detail='picking_up','Picking up accepted items.'
                -- QQT_Warpigz_v3 1.0.25: busy only for the fight wait: nothing moves, say so.
                if fight_only then
                    detail=Pickup.fight_waiting_n and string.format('Waiting for the fight to end (%d drop(s)).',tonumber(Pickup.fight_waiting_n) or 1)
                        or 'Waiting while Navigator gets the path back (Scavenger stand-in cool-down).'
                end
            elseif loot_waiting() then detail='Ready; a drop waits for the fight to end.' end -- QQT_Warpigz_v3 1.0.22
        end
        return {enabled=enabled,paused=paused,ready=reason=='ready' or reason=='picking_up',
            running=reason=='picking_up',activity_owned=owned,reason=reason,detail=detail,
            loot_waiting=loot_waiting()} -- QQT_Warpigz_v3 1.0.22
    end,
    evaluate_item=function(item,ignore_distance)
        local wanted,reason,decision=ItemManager.check_want_item(item,ignore_distance)
        -- QQT_Warpigz_v3 (3.1.1): a caller that ignores the distance walks to the
        -- drop (HR's tear loot window); a drop pickup already settled or
        -- exhausted (not merely resting between rounds) is not worth the walk.
        if wanted and ignore_distance and Pickup.blocked(item) and not Pickup.resting(item) then
            return false,'pickup settled/exhausted',decision -- pickup logged it when it settled
        end
        if not wanted then ItemManager.report_rejection(item,reason) end
        return wanted,reason,decision
    end,
    observe_items=ItemManager.observe,
    diagnose=ItemManager.diagnose,
}
LooteerPlugin=published
-- QQT_Warpigz_v3 1.0.23: Scavenger.pause/resume; owned: no wanted items while an activity owns the loot (review).
-- QQT_Warpigz_v3 1.0.25: the mimic takes a pause only at the start of a
-- caller's pause episode (Worldstone's Scavenger.pause); that start is logged,
-- QQT_Warpigz_v3 1.0.25 (review) at most once per PAUSE_LOG_GAP s per caller
-- (a caller that alternates pause and resume would print every cycle).
local PAUSE_LOG_GAP=60
local pause_logged={}
local function acquire_through_scavenger(caller)
    local result=acquire_pause(caller)
    if result then
        local now,key=get_time_since_inject(),tostring(caller)
        local last=pause_logged[key]
        if not last or now<last or now-last>=PAUSE_LOG_GAP then
            pause_logged[key]=now
            console.print('[Rosie pickup] Paused by '..key..' (through Scavenger); pickup waits until it resumes (at most 60 s)')
        end
    end
    return result
end
Mimic.configure({acquire=acquire_through_scavenger,release=release_pause,owned=activity_owns_loot})
callbacks.on_update(main_pulse)
callbacks.on_render_menu(function()
    if not active then return end
    if GUI.render(published.status) then
        Settings.update()
        if not Settings.get().enabled then release_pickup(true) end
        if GUI.elements.debug.diagnose:get() then ItemManager.diagnose() end
    end
end)
callbacks.on_render(function() if active then Renderer.draw_stuff() end end)
