-- Generated by tools/build-rosie.mjs; edit the reviewed source or transform.
local Utils = {}

-- Host userdata members may throw while an actor is being removed.
function Utils.call(object, name, ...)
    if object == nil then return nil end
    local ok, member = pcall(function() return object[name] end)
    if not ok or type(member) ~= 'function' then return nil end
    local called, value = pcall(member, object, ...)
    if called then return value end
    return nil
end
function Utils.distance_to(object)
    local player = get_local_player()
    local position = Utils.call(object, 'get_position')
    local origin = Utils.call(player, 'get_position')
    local distance = origin and position and Utils.call(origin, 'dist_to_ignore_z', position)
    return type(distance)=='number' and distance==distance and distance or math.huge
end
function Utils.host_call(fn, ...)
    if type(fn)~='function' then return nil end
    local ok,value=pcall(fn,...)
    if ok then return value end
end
function Utils.get_greater_affix_count(display_name)
    local count = 0
    for _ in tostring(display_name or ''):gmatch('GreaterAffix') do count=count+1 end
    return count
end
function Utils.get_ga_count(info)
    local value = Utils.call(info, 'get_attribute', 'Item_Greater_Affix_Count')
    local native_count=nil
    if type(value)=='number' and value==value and value>=0 and value<100 then
        native_count=math.floor(value)
    end
    local display=Utils.call(info,'get_display_name')
    local display_readable=type(display)=='string'
    local display_count=display_readable and Utils.get_greater_affix_count(display) or nil
    -- The native attribute can read zero on a ground item whose name already
    -- exposes GA markers. Preserve either positive observation; ancestry itself
    -- is never evidence of a GA count.
    local count=math.max(native_count or 0,display_count or 0)
    local source='unavailable'
    if native_count~=nil then source='native' end
    if display_readable and (native_count==nil or display_count>native_count) then source='display' end
    local observations={native_raw=value,native_count=native_count,display_count=display_count,
        display_readable=display_readable,source=source,
        conflict=native_count~=nil and display_count~=nil and display_count>0 and native_count~=display_count}
    return count,native_count~=nil or display_readable,observations
end
function Utils.is_lowest_stack_below(inventory, item_id, max_stack, looted_stack)
    if type(inventory)~='table' or type(looted_stack)~='number' or looted_stack<=0 then return false,false end
    local room,readable=0,true
    for _, item in pairs(inventory) do
        local sno=Utils.call(item,'get_sno_id')
        if type(sno)~='number' then readable=false
        elseif sno==item_id then
            local count=Utils.call(item,'get_stack_count')
            if type(count)=='number' and count==count and count>=0 then room=room+math.max(0,max_stack-count)
            else readable=false end
        end
    end
    return room>=looted_stack,readable
end
local bags={equipment='get_inventory_items',consumable='get_consumable_items',
    sigil='get_dungeon_key_items',socketable='get_socketable_items',talisman='get_talisman_items'}
function Utils.bag_items(bag)
    local player=get_local_player()
    return player and Utils.call(player,bags[bag]) or nil
end
function Utils.bag_state(bag)
    local items=Utils.bag_items(bag)
    if type(items)~='table' then return nil,nil end
    local count=0
    for _ in pairs(items) do count=count+1 end
    -- Preserve the existing host/corpus capacity; equality failed above capacity.
    return items,count>=33
end
function Utils.bag_full(bag)
    local items,full=Utils.bag_state(bag)
    return items==nil or full
end
function Utils.is_inventory_full() return Utils.bag_full('equipment') end
function Utils.is_consumable_inventory_full() return Utils.bag_full('consumable') end
function Utils.is_sigil_inventory_full() return Utils.bag_full('sigil') end
function Utils.is_socketable_inventory_full() return Utils.bag_full('socketable') end
function Utils.is_talisman_inventory_full() return Utils.bag_full('talisman') end
function Utils.player_in_zone(zname)
    local current=get_current_world()
    return current and Utils.call(current,'get_current_zone_name')==zname or false
end
return Utils
