-- Generated by tools/build-rosie.mjs; edit the reviewed source or transform.
local Utils = {}

-- Host userdata members may throw while an actor is being removed.
function Utils.call(object, name, ...)
    if object == nil then return nil end
    local ok, member = pcall(function() return object[name] end)
    if not ok or type(member) ~= 'function' then return nil end
    local called, value = pcall(member, object, ...)
    if called then return value end
    return nil
end
function Utils.distance_to(object)
    local player = get_local_player()
    local position = Utils.call(object, 'get_position')
    local origin = Utils.call(player, 'get_position')
    local distance = origin and position and Utils.call(origin, 'dist_to_ignore_z', position)
    return type(distance)=='number' and distance==distance and distance or math.huge
end
function Utils.host_call(fn, ...)
    if type(fn)~='function' then return nil end
    local ok,value=pcall(fn,...)
    if ok then return value end
end
function Utils.get_greater_affix_count(display_name)
    local count = 0
    for _ in tostring(display_name or ''):gmatch('GreaterAffix') do count=count+1 end
    return count
end
function Utils.get_ga_count(info)
    local value = Utils.call(info, 'get_attribute', 'Item_Greater_Affix_Count')
    local native_count=nil
    if type(value)=='number' and value==value and value>=0 and value<100 then
        native_count=math.floor(value)
    end
    local display=Utils.call(info,'get_display_name')
    local display_readable=type(display)=='string'
    local display_count=display_readable and Utils.get_greater_affix_count(display) or nil
    -- The native attribute can read zero on a ground item whose name already
    -- exposes GA markers. Preserve either positive observation; ancestry itself
    -- is never evidence of a GA count.
    local count=math.max(native_count or 0,display_count or 0)
    local source='unavailable'
    if native_count~=nil then source='native' end
    if display_readable and (native_count==nil or display_count>native_count) then source='display' end
    local observations={native_raw=value,native_count=native_count,display_count=display_count,
        display_readable=display_readable,source=source,
        conflict=native_count~=nil and display_count~=nil and display_count>0 and native_count~=display_count}
    return count,native_count~=nil or display_readable,observations
end
function Utils.is_lowest_stack_below(inventory, item_id, max_stack, looted_stack)
    if type(inventory)~='table' or type(looted_stack)~='number' or looted_stack<=0 then return false,false end
    local room,readable=0,true
    for _, item in pairs(inventory) do
        local sno=Utils.call(item,'get_sno_id')
        if type(sno)~='number' then readable=false
        elseif sno==item_id then
            local count=Utils.call(item,'get_stack_count')
            if type(count)=='number' and count==count and count>=0 then room=room+math.max(0,max_stack-count)
            else readable=false end
        end
    end
    return room>=looted_stack,readable
end
local bags={equipment='get_inventory_items',consumable='get_consumable_items',
    sigil='get_dungeon_key_items',socketable='get_socketable_items',talisman='get_talisman_items'}
function Utils.bag_items(bag)
    local player=get_local_player()
    return player and Utils.call(player,bags[bag]) or nil
end
-- QQT_Warpigz_v3 (Q1): items of `sno` in `bag` (stack counts summed); nil
-- when the bag cannot be read. A rise after an interaction is a receipt.
function Utils.sno_count(bag,sno)
    local items=Utils.bag_items(bag)
    if type(items)~='table' or type(sno)~='number' then return nil end
    local n=0
    for _,item in pairs(items) do
        if Utils.call(item,'get_sno_id')==sno then
            local c=Utils.call(item,'get_stack_count')
            n=n+((type(c)=='number' and c==c and c>0) and c or 1)
        end
    end
    return n
end
-- QQT_Warpigz_v3 (Q9): does a bag list already hold this SNO? Returns held,
-- readable (readable=false when an entry's SNO cannot be read).
function Utils.list_has_sno(items,sno)
    if type(items)~='table' or type(sno)~='number' then return false,false end
    local readable=true
    for _,item in pairs(items) do
        local id=Utils.call(item,'get_sno_id')
        if id==sno then return true,true end
        if type(id)~='number' then readable=false end
    end
    return false,readable
end
-- QQT_Warpigz_v3 (Q1): false only when the host reads the point itself as
-- not walkable (proof that a drop cannot be approached); nil when unknown.
function Utils.walkable(x,y,z)
    local u=rawget(_G,'utility')
    if type(u)~='table' or type(u.is_point_walkeable)~='function' or type(x)~='number' or type(y)~='number' then return nil end
    local ok,p=pcall(function() return vec3:new(x,y,z or 0) end)
    if not ok or p==nil then return nil end
    if type(u.set_height_of_valid_position)=='function' then
        local ok2,q=pcall(u.set_height_of_valid_position,p)
        if ok2 and (type(q)=='userdata' or type(q)=='table') then p=q end
    end
    local ok3,walk=pcall(u.is_point_walkeable,p)
    if not ok3 or type(walk)~='boolean' then return nil end
    return walk
end
-- QQT_Warpigz_v3 (Q1 review): a drop only has to be within `reach` of the
-- player, not on a walkable point (a Mythic on a small prop is taken from in
-- front of it). false only when the drop's spot AND every sample on two rings
-- within `reach` read not walkable; true when any reads walkable; nil unknown.
function Utils.walkable_near(x,y,z,reach)
    local w=Utils.walkable(x,y,z)
    if w~=false then return w end
    local r,unknown=reach or 2,false
    for _,f in ipairs({0.5,0.95}) do
        for i=0,7 do
            local a=i*math.pi/4
            local s=Utils.walkable(x+math.cos(a)*r*f,y+math.sin(a)*r*f,z)
            if s==true then return true end
            if s==nil then unknown=true end
        end
    end
    if unknown then return nil end
    return false
end
-- QQT_Warpigz_v3 (Q1 review): a live enemy within `radius` m of the player
-- (the fight that swallows pickup interactions and moves). false when unknown.
function Utils.enemy_near(radius)
    local ts=rawget(_G,'target_selector')
    if type(ts)~='table' or type(ts.get_near_target_list)~='function' then return false end
    local origin=Utils.call(Utils.host_call(rawget(_G,'get_local_player')),'get_position')
    if not origin then return false end
    local ok,list=pcall(ts.get_near_target_list,origin,radius)
    if not ok or type(list)~='table' then return false end
    for _,a in pairs(list) do
        local d=Utils.call(origin,'dist_to_ignore_z',Utils.call(a,'get_position'))
        if type(d)=='number' and d<=radius and Utils.call(a,'is_dead')~=true then return true end
    end
    return false
end
function Utils.bag_state(bag)
    local items=Utils.bag_items(bag)
    if type(items)~='table' then return nil,nil end
    local count=0
    for _ in pairs(items) do count=count+1 end
    -- Preserve the existing host/corpus capacity; equality failed above capacity.
    return items,count>=33
end
function Utils.bag_full(bag)
    local items,full=Utils.bag_state(bag)
    return items==nil or full
end
function Utils.is_inventory_full() return Utils.bag_full('equipment') end
function Utils.is_consumable_inventory_full() return Utils.bag_full('consumable') end
function Utils.is_sigil_inventory_full() return Utils.bag_full('sigil') end
function Utils.is_socketable_inventory_full() return Utils.bag_full('socketable') end
function Utils.is_talisman_inventory_full() return Utils.bag_full('talisman') end
function Utils.player_in_zone(zname)
    local current=get_current_world()
    return current and Utils.call(current,'get_current_zone_name')==zname or false
end
return Utils
